unit PascalApi.TracingTests;

{$mode delphi}{$H+}

{ GENERATED FILE — produced by tools/gen_fpc_mirror.py from
  tests/Unit/PascalApi.TracingTests.pas (DUnitX). Do not edit by hand: edit the DUnitX
  master and run the script again. }

{ Tests for PascalApi.Tracing: spans and the current span, parent and child,
  sampling (flag and ratio), attributes and status, the batch processor
  (bounded queue, batch size, export failures), tracing not started, UTC
  Unix nanoseconds, key=value lists and the OTEL_* options. The exporter is a
  fake that keeps what it gets; the processor runs without its thread
  (AAutoFlush = False) and FlushNow exports.

  DUnitX master. The FPCUnit mirror (tests/Unit/fpc) is generated by
  tools/gen_fpc_mirror.py; never edit the mirror by hand. }

interface

uses
  fpcunit, testregistry,
  Classes,
  SysUtils,
  DateUtils,
  PascalApi.Text,
  PascalApi.Http,
  PascalApi.Config,
  PascalApi.Tracing;

type
  TFakeSpanExporter = class(TInterfacedObject, ISpanExporter)
  public
    Spans: TSpanDataArray;
    Calls: Integer;
    Fail: Boolean;
    function ExportSpans(const ASpans: TSpanDataArray; out AError: string): Boolean;
  end;

  TTracingTests = class(TTestCase)
  private
    FFake: TFakeSpanExporter;
    FExporter: ISpanExporter;
    FErrors: TStringList;
    procedure StartWith(const AOptions: TTracingOptions);
    procedure LogError(const ALine: string);
  protected
    procedure SetUp; override;
    procedure TearDown; override;
  published
    procedure RootSpan_IsCurrent_ExportedOnFlush;
    procedure ChildSpan_SameTrace_ParentRestored;
    procedure StartSpanWith_KeepsIds;
    procedure NotSampled_NotExported_FlagZero;
    procedure Child_FollowsParentSampledFlag;
    procedure Ratio_ZeroOneAndHalf;
    procedure Attributes_TypesAndReplace;
    procedure Status_ErrorKeepsMessage_OkClearsIt;
    procedure Finish_Twice_ExportedOnce_LaterChangesIgnored;
    procedure Queue_Full_DropsOldest;
    procedure Batches_NoLargerThanMax;
    procedure ExportFailure_Reported_SpansDropped;
    procedure NotStarted_SpansWork_NothingExported;
    procedure UnfinishedSpan_Freed_ClearsCurrent;
    procedure UnixNano_IsUtcMilliseconds;
    procedure KeyValueList_TrimsDecodesSkips;
    procedure Options_FromEnvironment;
  end;

implementation

var
  GFakeEnv: TStringList;

function FakeEnvironment(const AName: string): string;
begin
  Result := GFakeEnv.Values[AName];
end;

// The current span's id, '' when none. A helper, so the temporary interface
// TTracing.Current returns is released here: in the test body it would keep
// the span alive until the end of the procedure.
function CurrentSpanId: string;
var
  LCurrent: ISpan;
begin
  LCurrent := TTracing.Current;
  if LCurrent = nil then
    Result := ''
  else
    Result := LCurrent.SpanId;
end;

function TFakeSpanExporter.ExportSpans(const ASpans: TSpanDataArray; out AError: string): Boolean;
var
  I: Integer;
begin
  Inc(Calls);
  if Fail then
  begin
    AError := 'collector down';
    Exit(False);
  end;
  for I := 0 to High(ASpans) do
  begin
    SetLength(Spans, Length(Spans) + 1);
    Spans[High(Spans)] := ASpans[I];
  end;
  AError := '';
  Result := True;
end;

{ TTracingTests }

procedure TTracingTests.Setup;
begin
  FErrors := TStringList.Create;
  StartWith(TTracingOptions.Default('svc', '1.2.3'));
end;

procedure TTracingTests.TearDown;
begin
  TTracing.Shutdown;
  FExporter := nil;
  FErrors.Free;
end;

procedure TTracingTests.StartWith(const AOptions: TTracingOptions);
begin
  FFake := TFakeSpanExporter.Create;
  FExporter := FFake;
  TTracing.Start(AOptions, FExporter, LogError, False);
end;

procedure TTracingTests.LogError(const ALine: string);
begin
  FErrors.Add(ALine);
end;

procedure TTracingTests.RootSpan_IsCurrent_ExportedOnFlush;
var
  S: ISpan;
begin
  TAssert.AssertTrue('no current span at the start', TTracing.Current = nil);
  S := TTracing.StartSpan('work');
  TAssert.AssertTrue('the new span is the current one', TTracing.Current = S);
  TAssert.AssertEquals(32, Length(S.TraceId));
  TAssert.AssertEquals(16, Length(S.SpanId));
  TAssert.AssertEquals('', S.ParentSpanId);
  TAssert.AssertTrue(S.Sampled);
  S.Finish;
  TAssert.AssertTrue('finished: no current span', TTracing.Current = nil);
  TAssert.AssertEquals(0, Length(FFake.Spans));
  TAssert.AssertEquals(1, TTracing.PendingCount);
  TTracing.FlushNow;
  TAssert.AssertEquals(1, Length(FFake.Spans));
  TAssert.AssertEquals('work', FFake.Spans[0].Name);
  TAssert.AssertTrue(FFake.Spans[0].Kind = skInternal);
  TAssert.AssertEquals(S.SpanId, FFake.Spans[0].SpanId);
  TAssert.AssertTrue('end >= start', FFake.Spans[0].EndUnixNano >= FFake.Spans[0].StartUnixNano);
end;

procedure TTracingTests.ChildSpan_SameTrace_ParentRestored;
var
  P, C: ISpan;
begin
  P := TTracing.StartSpan('parent', skServer);
  C := TTracing.StartSpan('child');
  TAssert.AssertEquals(P.TraceId, C.TraceId);
  TAssert.AssertEquals(P.SpanId, C.ParentSpanId);
  TAssert.AssertTrue(C.SpanId <> P.SpanId);
  C.Finish;
  TAssert.AssertTrue('the parent is current again', TTracing.Current = P);
  P.Finish;
  TAssert.AssertTrue(TTracing.Current = nil);
  TTracing.FlushNow;
  TAssert.AssertEquals(2, Length(FFake.Spans));
  TAssert.AssertEquals('child', FFake.Spans[0].Name);
  TAssert.AssertTrue(FFake.Spans[1].Kind = skServer);
end;

procedure TTracingTests.StartSpanWith_KeepsIds;
var
  S: ISpan;
begin
  S := TTracing.StartSpanWith('4bf92f3577b34da6a3ce929d0e0e4736', 'b7ad6b7169203331',
    '00f067aa0ba902b7', 'vendor=1', True, 'GET /x', skServer);
  TAssert.AssertEquals('00-4bf92f3577b34da6a3ce929d0e0e4736-b7ad6b7169203331-01', S.TraceParent);
  TAssert.AssertEquals('vendor=1', S.TraceState);
  S.Finish;
  TTracing.FlushNow;
  TAssert.AssertEquals('00f067aa0ba902b7', FFake.Spans[0].ParentSpanId);
  TAssert.AssertEquals('vendor=1', FFake.Spans[0].TraceState);
end;

procedure TTracingTests.NotSampled_NotExported_FlagZero;
var
  S: ISpan;
begin
  S := TTracing.StartSpanWith('4bf92f3577b34da6a3ce929d0e0e4736', 'b7ad6b7169203331', '', '',
    False, 'x', skServer);
  TAssert.AssertEquals('00-4bf92f3577b34da6a3ce929d0e0e4736-b7ad6b7169203331-00', S.TraceParent);
  S.Finish;
  TTracing.FlushNow;
  TAssert.AssertEquals(0, Length(FFake.Spans));
end;

procedure TTracingTests.Child_FollowsParentSampledFlag;
var
  P, C: ISpan;
begin
  P := TTracing.StartSpanWith('4bf92f3577b34da6a3ce929d0e0e4736', 'b7ad6b7169203331', '', '',
    False, 'p', skServer);
  C := TTracing.StartSpan('c');
  TAssert.AssertFalse(C.Sampled);
  C.Finish;
  P.Finish;
  TTracing.FlushNow;
  TAssert.AssertEquals(0, Length(FFake.Spans));
end;

procedure TTracingTests.Ratio_ZeroOneAndHalf;
var
  O: TTracingOptions;
begin
  TAssert.AssertTrue(TTracing.ShouldSample('4bf92f3577b34da6ffffffffffffffff'));
  O := TTracingOptions.Default('svc', '1');
  O.SampleRatio := 0;
  StartWith(O);
  TAssert.AssertFalse(TTracing.ShouldSample('4bf92f3577b34da60000000000000000'));
  O.SampleRatio := 0.5;
  StartWith(O);
  // Below half of 2^64 by the last 16 hex digits: sampled.
  TAssert.AssertTrue(TTracing.ShouldSample('4bf92f3577b34da60000000000000000'));
  TAssert.AssertTrue(TTracing.ShouldSample('ffffffffffffffff7fffffffffffffff'));
  TAssert.AssertFalse(TTracing.ShouldSample('00000000000000008000000000000000'));
  TAssert.AssertFalse(TTracing.ShouldSample('4bf92f3577b34da6ffffffffffffffff'));
  // Not a trace id: never sampled.
  TAssert.AssertFalse(TTracing.ShouldSample('xyz'));
end;

procedure TTracingTests.Attributes_TypesAndReplace;
var
  S: ISpan;
  A: TSpanAttributes;
begin
  S := TTracing.StartSpan('a');
  S.SetAttribute('s', 'one');
  S.SetIntAttribute('i', 42);
  S.SetDoubleAttribute('d', 0.5);
  S.SetBoolAttribute('b', True);
  S.SetAttribute('s', 'two');
  S.Finish;
  TTracing.FlushNow;
  A := FFake.Spans[0].Attributes;
  TAssert.AssertEquals(4, Length(A));
  TAssert.AssertEquals('s', A[0].Key);
  TAssert.AssertEquals('two', A[0].StringValue);
  TAssert.AssertTrue(A[1].ValueType = satInt);
  TAssert.AssertEquals(Int64(42), A[1].IntValue);
  TAssert.AssertTrue(A[2].ValueType = satDouble);
  TAssert.AssertTrue(A[2].DoubleValue = 0.5);
  TAssert.AssertTrue(A[3].ValueType = satBool);
  TAssert.AssertTrue(A[3].BoolValue);
end;

procedure TTracingTests.Status_ErrorKeepsMessage_OkClearsIt;
var
  S: ISpan;
begin
  S := TTracing.StartSpan('a');
  S.SetStatus(ssError, 'boom');
  S.Finish;
  S := TTracing.StartSpan('b');
  S.SetStatus(ssError, 'boom');
  S.SetStatus(ssOk, 'ignored');
  S.Finish;
  TTracing.FlushNow;
  TAssert.AssertTrue(FFake.Spans[0].Status = ssError);
  TAssert.AssertEquals('boom', FFake.Spans[0].StatusMessage);
  TAssert.AssertTrue(FFake.Spans[1].Status = ssOk);
  TAssert.AssertEquals('', FFake.Spans[1].StatusMessage);
end;

procedure TTracingTests.Finish_Twice_ExportedOnce_LaterChangesIgnored;
var
  S: ISpan;
begin
  S := TTracing.StartSpan('a');
  S.Finish;
  S.SetAttribute('late', 'x');
  S.SetStatus(ssError, 'late');
  S.Finish;
  TTracing.FlushNow;
  TAssert.AssertEquals(1, Length(FFake.Spans));
  TAssert.AssertEquals(0, Length(FFake.Spans[0].Attributes));
  TAssert.AssertTrue(FFake.Spans[0].Status = ssUnset);
end;

procedure TTracingTests.Queue_Full_DropsOldest;
var
  O: TTracingOptions;
  I: Integer;
begin
  O := TTracingOptions.Default('svc', '1');
  O.QueueCapacity := 2;
  StartWith(O);
  for I := 1 to 3 do
    TTracing.StartSpan('s' + IntToStr(I)).Finish;
  TAssert.AssertEquals(Int64(1), TTracing.DroppedCount);
  TTracing.FlushNow;
  TAssert.AssertEquals(2, Length(FFake.Spans));
  TAssert.AssertEquals('s2', FFake.Spans[0].Name);
  TAssert.AssertEquals('s3', FFake.Spans[1].Name);
end;

procedure TTracingTests.Batches_NoLargerThanMax;
var
  O: TTracingOptions;
  I: Integer;
begin
  O := TTracingOptions.Default('svc', '1');
  O.MaxBatchSize := 2;
  StartWith(O);
  for I := 1 to 5 do
    TTracing.StartSpan('s').Finish;
  TTracing.FlushNow;
  TAssert.AssertEquals(3, FFake.Calls);
  TAssert.AssertEquals(5, Length(FFake.Spans));
  TAssert.AssertEquals(0, TTracing.PendingCount);
end;

procedure TTracingTests.ExportFailure_Reported_SpansDropped;
begin
  FFake.Fail := True;
  TTracing.StartSpan('a').Finish;
  TTracing.FlushNow;
  TAssert.AssertEquals(1, FErrors.Count);
  TAssert.AssertEquals('span export failed (1 spans dropped): collector down', FErrors[0]);
  TAssert.AssertEquals(0, TTracing.PendingCount);
  // A later batch goes through again.
  FFake.Fail := False;
  TTracing.StartSpan('b').Finish;
  TTracing.FlushNow;
  TAssert.AssertEquals(1, Length(FFake.Spans));
end;

procedure TTracingTests.NotStarted_SpansWork_NothingExported;
var
  P, C: ISpan;
begin
  TTracing.Shutdown;
  TAssert.AssertFalse(TTracing.Enabled);
  P := TTracing.StartSpan('p');
  C := TTracing.StartSpan('c');
  TAssert.AssertEquals(P.TraceId, C.TraceId);
  C.SetAttribute('k', 'v');
  C.Finish;
  P.Finish;
  TTracing.FlushNow;
  TAssert.AssertEquals(0, Length(FFake.Spans));
  TAssert.AssertTrue(TTracing.Current = nil);
end;

procedure TTracingTests.UnfinishedSpan_Freed_ClearsCurrent;
var
  P, C: ISpan;
  LParentId: string;
begin
  P := TTracing.StartSpan('p');
  LParentId := P.SpanId;
  C := TTracing.StartSpan('c');
  C := nil; // never finished
  TAssert.AssertEquals('the parent is current again', LParentId, CurrentSpanId);
  P := nil;
  TAssert.AssertEquals('no current span', '', CurrentSpanId);
  TTracing.FlushNow;
  TAssert.AssertEquals(0, Length(FFake.Spans));
end;

procedure TTracingTests.UnixNano_IsUtcMilliseconds;
var
  T: TDateTime;
begin
  T := EncodeDate(2026, 1, 2) + EncodeTime(3, 4, 5, 678);
  // DateTimeToUnix(T, False) is UTC seconds of a local time (PascalApi.Jwt
  // relies on it, measured on both compilers).
  TAssert.AssertEquals((DateTimeToUnix(T, False) * 1000 + 678) * 1000000, UnixNanoOfLocal(T));
end;

procedure TTracingTests.KeyValueList_TrimsDecodesSkips;
var
  L: TArray<THttpHeader>;
  B: TBytes;
begin
  L := ParseKeyValueList('a=b, c = d ,bad,=x,e=%41%C3%A3,f=1=2');
  TAssert.AssertEquals(4, Length(L));
  TAssert.AssertEquals('a', L[0].Name);
  TAssert.AssertEquals('b', L[0].Value);
  TAssert.AssertEquals('c', L[1].Name);
  TAssert.AssertEquals('d', L[1].Value);
  TAssert.AssertEquals('e', L[2].Name);
  // 'A' and U+00E3, from percent-encoded UTF-8.
  B := PaStringToUtf8Bytes(L[2].Value);
  TAssert.AssertEquals(3, Length(B));
  TAssert.AssertEquals($41, B[0]);
  TAssert.AssertEquals($C3, B[1]);
  TAssert.AssertEquals($A3, B[2]);
  TAssert.AssertEquals('1=2', L[3].Value);
  TAssert.AssertEquals(0, Length(ParseKeyValueList('')));
end;

procedure TTracingTests.Options_FromEnvironment;
var
  LSavedEnvPath: string;
  O: TTracingOptions;
begin
  LSavedEnvPath := TAppConfig.EnvFilePath;
  GFakeEnv := TStringList.Create;
  try
    TAppConfig.SetEnvFile('pascalapi_tracing_no_such.env');
    TAppConfig.SetEnvironmentReader(FakeEnvironment);
    O := TTracingOptions.FromEnvironment('default-name', '1.0');
    TAssert.AssertEquals('default-name', O.ServiceName);
    TAssert.AssertTrue(O.SampleRatio = 1);
    TAssert.AssertEquals(5000, O.FlushIntervalMs);
    GFakeEnv.Values['OTEL_SERVICE_NAME'] := 'from-env';
    GFakeEnv.Values['OTEL_TRACES_SAMPLER_ARG'] := '0.25';
    GFakeEnv.Values['OTEL_BSP_SCHEDULE_DELAY'] := '200';
    GFakeEnv.Values['OTEL_BSP_MAX_QUEUE_SIZE'] := '10';
    GFakeEnv.Values['OTEL_BSP_MAX_EXPORT_BATCH_SIZE'] := '0';
    GFakeEnv.Values['OTEL_RESOURCE_ATTRIBUTES'] := 'deployment.environment=test';
    O := TTracingOptions.FromEnvironment('default-name', '1.0');
    TAssert.AssertEquals('from-env', O.ServiceName);
    TAssert.AssertEquals('1.0', O.ServiceVersion);
    TAssert.AssertTrue(O.SampleRatio = 0.25);
    TAssert.AssertEquals(200, O.FlushIntervalMs);
    TAssert.AssertEquals(10, O.QueueCapacity);
    TAssert.AssertEquals(512, O.MaxBatchSize);
    TAssert.AssertEquals('deployment.environment=test', O.ResourceAttributes);
    GFakeEnv.Values['OTEL_TRACES_SAMPLER_ARG'] := '2';
    TAssert.AssertTrue(TTracingOptions.FromEnvironment('n', 'v').SampleRatio = 1);
  finally
    TAppConfig.SetEnvironmentReader(nil);
    TAppConfig.SetEnvFile(LSavedEnvPath);
    FreeAndNil(GFakeEnv);
  end;
end;

initialization
  RegisterTest(TTracingTests);

end.
