unit PascalApi.McpTests;

{$mode delphi}{$H+}

{ GENERATED FILE — produced by tools/gen_fpc_mirror.py from
  tests/Unit/PascalApi.McpTests.pas (DUnitX). Do not edit by hand: edit the DUnitX
  master and run the script again. }

{ Tests for PascalApi.Mcp: the origin's tool-name rule and tag filter (its
  test cases, ported), URL encoding, the catalog built from a TApiDocument
  (names, NoMcp, tags, input schemas, descriptions, duplicates) and the
  2026-07-28 dispatcher with a fake executor (server/discover, tools/list,
  tools/call building path, query string and body, the forwarded headers,
  isError results, and every protocol error with its HTTP status).

  DUnitX master. The FPCUnit mirror (tests/Unit/fpc) is generated by
  tools/gen_fpc_mirror.py; never edit the mirror by hand. }

interface

uses
  fpcunit, testregistry,
  SysUtils,
  TypInfo,
  PascalCommon.Optionals,
  PascalJsonMapper.Json,
  PascalJsonMapper.Mapper,
  PascalApi.OpenApi,
  PascalApi.Mcp;

type
  ICityIn = interface
    ['{3BC29FD7-41EA-4573-AECB-B95DDDC44841}']
  end;

  ICityOut = interface
    ['{F8C66DBC-78CB-4CFB-A912-17F428A7BFF5}']
  end;

{$M+}
  TCityIn = class(TInterfacedObject, ICityIn)
  private
    FName: string;
    FPopulation: IOptInteger;
  published
    property Name: string read FName write FName;
    property Population: IOptInteger read FPopulation write FPopulation;
  end;

  TCityOut = class(TInterfacedObject, ICityOut)
  private
    FCode: string;
    FName: string;
  published
    property Code: string read FCode write FCode;
    property Name: string read FName write FName;
  end;
{$M-}

  /// Records the last call and answers with a fixed status and body.
  TFakeExecutor = class(TInterfacedObject, IMcpToolExecutor)
  public
    Calls: Integer;
    Method, PathAndQuery, Body: string;
    Forwarded: TMcpForward;
    Status: Integer;
    Answer: string;
    Fail: Boolean;
    function Execute(const AMethod, APathAndQuery, ABody: string; const AForward: TMcpForward;
      out AStatus: Integer): string;
  end;

  TMcpTests = class(TTestCase)
  private
    FMapper: TJsonMapper;
    FDoc: TApiDocument;
    FFake: TFakeExecutor;
    FExecutor: IMcpToolExecutor;
    FServer: TMcpServer;
    FStatus: Integer;
    function Op(const AMethod, APath: string): TApiOperation;
    procedure AddParam(AOp: TApiOperation; const AName: string; ALocation: TApiParamLocation;
      AType: TApiParamType; ARequired: Boolean; const ADescription: string = '');
    procedure AddTag(AOp: TApiOperation; const ATag: string);
    procedure AddResponse(AOp: TApiOperation; ACode: Integer; AKind: TApiResponseKind;
      ASchema: PTypeInfo);
    procedure BuildCities;
    function Server(const ATags: array of string): TMcpServer;
    function Post(const ABody, AMethodHeader: string; const ANameHeader: string = '';
      const AVersionHeader: string = MCP_PROTOCOL_VERSION): string;
    function Request(const AMethod, AParams: string): string;
    function Call(const ATool, AArgs: string): string;
  protected
    procedure SetUp; override;
    procedure TearDown; override;
  published

    procedure DeriveName_OriginCases;
    procedure MatchesTags_OriginCases;
    procedure UrlEncode_ReservedAndUtf8;
    procedure Catalog_NamesNoMcpAndTags;
    procedure Catalog_InputSchema;
    procedure Catalog_DescriptionWithReturns;
    procedure Catalog_DuplicateToolName_Raises;
    procedure Catalog_DuplicateArgument_Raises;
    procedure Discover_ExactText;
    procedure ToolsList_ListsTools;
    procedure Call_Get_PathAndQueryString;
    procedure Call_Post_JsonBody;
    procedure Call_ForwardsAuthorizationAndAddress;
    procedure Call_ApiError_IsError;
    procedure Call_ExecutorRaises_IsError;
    procedure Call_MissingOrUnknownArgument_IsErrorWithoutCalling;
    procedure Call_Base64NameHeader;
    procedure Notification_202NoBody;
    procedure Initialize_404NamesVersion;
    procedure MissingMeta_400InvalidParams;
    procedure UnsupportedVersion_400WithData;
    procedure HeaderMismatch_400;
    procedure UnknownMethodAndTool;
    procedure ParseErrorAndInvalidRequest;
  end;

implementation

const
  META = '"_meta":{"io.modelcontextprotocol/protocolVersion":"2026-07-28",' +
    '"io.modelcontextprotocol/clientCapabilities":{}}';
  SERVER_META = '"_meta":{"io.modelcontextprotocol/serverInfo":{"name":"cities","version":"1.0"}}';

{ TFakeExecutor }

function TFakeExecutor.Execute(const AMethod, APathAndQuery, ABody: string;
  const AForward: TMcpForward; out AStatus: Integer): string;
begin
  Inc(Calls);
  Method := AMethod;
  PathAndQuery := APathAndQuery;
  Body := ABody;
  Forwarded := AForward;
  if Fail then
    raise Exception.Create('connection refused');
  AStatus := Status;
  Result := Answer;
end;

{ TMcpTests }

procedure TMcpTests.SetUp;
begin
  FMapper := TJsonMapper.Create;
  FMapper.RegisterMapping<ICityIn, TCityIn>;
  FMapper.RegisterMapping<ICityOut, TCityOut>;
  FDoc := TApiDocument.Create(FMapper);
  FFake := TFakeExecutor.Create;
  FFake.Status := 200;
  FFake.Answer := '{"ok":true}';
  FExecutor := FFake;
  FServer := nil;
end;

procedure TMcpTests.TearDown;
begin
  FreeAndNil(FServer);
  FExecutor := nil;
  FreeAndNil(FDoc);
  FreeAndNil(FMapper);
  TApiSchema.Clear;
end;

function TMcpTests.Op(const AMethod, APath: string): TApiOperation;
begin
  Result := TApiOperation.Create;
  Result.Method := AMethod;
  Result.Path := APath;
  FDoc.Add(Result);
end;

procedure TMcpTests.AddParam(AOp: TApiOperation; const AName: string;
  ALocation: TApiParamLocation; AType: TApiParamType; ARequired: Boolean;
  const ADescription: string);
begin
  SetLength(AOp.Params, Length(AOp.Params) + 1);
  AOp.Params[High(AOp.Params)].Name := AName;
  AOp.Params[High(AOp.Params)].Location := ALocation;
  AOp.Params[High(AOp.Params)].ParamType := AType;
  AOp.Params[High(AOp.Params)].Required := ARequired;
  AOp.Params[High(AOp.Params)].Description := ADescription;
end;

procedure TMcpTests.AddTag(AOp: TApiOperation; const ATag: string);
begin
  SetLength(AOp.Tags, Length(AOp.Tags) + 1);
  AOp.Tags[High(AOp.Tags)] := ATag;
end;

procedure TMcpTests.AddResponse(AOp: TApiOperation; ACode: Integer; AKind: TApiResponseKind;
  ASchema: PTypeInfo);
begin
  SetLength(AOp.Responses, Length(AOp.Responses) + 1);
  AOp.Responses[High(AOp.Responses)].Code := ACode;
  AOp.Responses[High(AOp.Responses)].Kind := AKind;
  AOp.Responses[High(AOp.Responses)].Schema := ASchema;
end;

// GET /cities (query state, page), GET /cities/:code, POST /cities (body),
// DELETE /cities/:code (NoMcp), GET /health (tag "ops").
procedure TMcpTests.BuildCities;
var
  LOp: TApiOperation;
begin
  LOp := Op('get', '/cities');
  LOp.Summary := 'List cities';
  AddTag(LOp, 'cities');
  AddParam(LOp, 'state', plQuery, ptString, False, 'Two-letter state');
  AddParam(LOp, 'page', plQuery, ptInteger, False);
  AddResponse(LOp, 200, rkArray, TypeInfo(ICityOut));

  LOp := Op('get', '/cities/:code');
  LOp.Summary := 'Get a city';
  AddTag(LOp, 'cities');
  AddResponse(LOp, 200, rkObject, TypeInfo(ICityOut));
  AddResponse(LOp, 404, rkError, nil);

  LOp := Op('post', '/cities');
  LOp.OperationId := 'add_city';
  AddTag(LOp, 'cities');
  LOp.Body := TypeInfo(ICityIn);
  AddResponse(LOp, 201, rkObject, TypeInfo(ICityOut));

  LOp := Op('delete', '/cities/:code');
  AddTag(LOp, 'cities');
  LOp.NoMcp := True;

  LOp := Op('get', '/health');
  AddTag(LOp, 'ops');
end;

function TMcpTests.Server(const ATags: array of string): TMcpServer;
begin
  FreeAndNil(FServer);
  FServer := TMcpServer.Create(FDoc, 'cities', '1.0', ATags, FExecutor);
  Result := FServer;
end;

function TMcpTests.Post(const ABody, AMethodHeader, ANameHeader, AVersionHeader: string): string;
var
  LHeaders: TMcpHeaders;
  LForward: TMcpForward;
begin
  if FServer = nil then
    Server([]);
  LHeaders.ProtocolVersion := AVersionHeader;
  LHeaders.Method := AMethodHeader;
  LHeaders.Name := ANameHeader;
  LForward.Authorization := 'Bearer abc';
  LForward.ForwardedFor := '10.0.0.7';
  LForward.TraceParent := '00-4bf92f3577b34da6a3ce929d0e0e4736-00f067aa0ba902b7-01';
  LForward.TraceState := 'vendor=1';
  Result := FServer.HandlePost(ABody, LHeaders, LForward, FStatus);
end;

function TMcpTests.Request(const AMethod, AParams: string): string;
var
  LParams: string;
begin
  LParams := META;
  if AParams <> '' then
    LParams := LParams + ',' + AParams;
  Result := Post('{"jsonrpc":"2.0","id":1,"method":"' + AMethod + '","params":{' + LParams + '}}',
    AMethod);
end;

function TMcpTests.Call(const ATool, AArgs: string): string;
begin
  Result := Post('{"jsonrpc":"2.0","id":7,"method":"tools/call","params":{' + META +
    ',"name":"' + ATool + '","arguments":' + AArgs + '}}', 'tools/call', ATool);
end;

procedure TMcpTests.DeriveName_OriginCases;
begin
  TAssert.AssertEquals('list_produto', McpDeriveName('GET', '/produtos'));
  TAssert.AssertEquals('list_cidade', McpDeriveName('GET', '/cidades'));
  TAssert.AssertEquals('get_produto', McpDeriveName('GET', '/produtos/{id}'));
  TAssert.AssertEquals('get_cidade', McpDeriveName('GET', '/cidades/{cod_ibge}'));
  TAssert.AssertEquals('create_produto', McpDeriveName('POST', '/produtos'));
  TAssert.AssertEquals('update_produto', McpDeriveName('PATCH', '/produtos/{id}'));
  TAssert.AssertEquals('update_produto', McpDeriveName('PUT', '/produtos/{id}'));
  TAssert.AssertEquals('delete_produto', McpDeriveName('DELETE', '/produtos/{id}'));
  TAssert.AssertEquals('list_produto', McpDeriveName('GET', '/v1/api/produtos'));
  TAssert.AssertEquals('list_meu_recurso', McpDeriveName('GET', '/meus-recursos'));
  TAssert.AssertEquals('list_pedido', McpDeriveName('get', '/pedidos'));
end;

procedure TMcpTests.MatchesTags_OriginCases;
begin
  TAssert.AssertTrue('empty filter', McpMatchesTags(['a'], []));
  TAssert.AssertTrue('match', McpMatchesTags(['a', 'b'], ['x', 'B']));
  TAssert.AssertFalse('no match', McpMatchesTags(['a'], ['x']));
  TAssert.AssertFalse('untagged op', McpMatchesTags([], ['x']));
end;

procedure TMcpTests.UrlEncode_ReservedAndUtf8;
begin
  TAssert.AssertEquals('a-b_c.d~0', McpUrlEncode('a-b_c.d~0'));
  TAssert.AssertEquals('S%20P%2Fx%3Fy%26z%3D1%25', McpUrlEncode('S P/x?y&z=1%'));
  TAssert.AssertEquals('S%C3%A3o', McpUrlEncode('São'));
end;

procedure TMcpTests.Catalog_NamesNoMcpAndTags;
var
  LNames: string;
  I: Integer;
begin
  BuildCities;
  LNames := '';
  for I := 0 to Server([]).Tools.Count - 1 do
    LNames := LNames + FServer.Tools[I].Name + ' ';
  TAssert.AssertEquals('list_citie get_citie add_city list_health ', LNames);
  LNames := '';
  for I := 0 to Server(['ops']).Tools.Count - 1 do
    LNames := LNames + FServer.Tools[I].Name + ' ';
  TAssert.AssertEquals('list_health ', LNames);
end;

procedure TMcpTests.Catalog_InputSchema;
begin
  BuildCities;
  Server([]);
  TAssert.AssertEquals('{"type":"object","properties":{' +
    '"state":{"type":"string","description":"Two-letter state"},' +
    '"page":{"type":"integer"}},"additionalProperties":false}', FServer.Tools[0].InputSchema);
  TAssert.AssertEquals('{"type":"object","properties":{"code":{"type":"string"}},' +
    '"required":["code"],"additionalProperties":false}', FServer.Tools[1].InputSchema);
  TAssert.AssertEquals('{"type":"object","properties":{"name":{"type":"string"},' +
    '"population":{"type":"integer","format":"int32"}},' +
    '"required":["name"],"additionalProperties":false}', FServer.Tools[2].InputSchema);
  TAssert.AssertEquals('{"type":"object","properties":{},"additionalProperties":false}',
    FServer.Tools[3].InputSchema);
end;

procedure TMcpTests.Catalog_DescriptionWithReturns;
begin
  BuildCities;
  Server([]);
  TAssert.AssertEquals('List cities. Returns a list of: code (string), name (string).',
    FServer.Tools[0].Description);
  TAssert.AssertEquals('Get a city. Returns: code (string), name (string).',
    FServer.Tools[1].Description);
  TAssert.AssertEquals('GET /health', FServer.Tools[3].Description);
end;

procedure TMcpTests.Catalog_DuplicateToolName_Raises;
var
  LMessage: string;
begin
  Op('get', '/cities');
  Op('get', '/v2/cities');
  LMessage := '';
  try
    Server([]);
  except
    on E: EMcpError do
      LMessage := E.Message;
  end;
  TAssert.AssertTrue(LMessage, Pos('"list_citie"', LMessage) > 0);
end;

procedure TMcpTests.Catalog_DuplicateArgument_Raises;
var
  LOp: TApiOperation;
  LMessage: string;
begin
  LOp := Op('put', '/cities/:name');
  LOp.Body := TypeInfo(ICityIn);
  LMessage := '';
  try
    Server([]);
  except
    on E: EMcpError do
      LMessage := E.Message;
  end;
  TAssert.AssertTrue(LMessage, Pos('"name"', LMessage) > 0);
end;

procedure TMcpTests.Discover_ExactText;
begin
  TAssert.AssertEquals('{"jsonrpc":"2.0","id":1,"result":{"resultType":"complete",' +
    '"ttlMs":0,"cacheScope":"private","supportedVersions":["2026-07-28"],"capabilities":{"tools":{}},' + SERVER_META + '}}',
    Request('server/discover', ''));
  TAssert.AssertEquals(200, FStatus);
end;

procedure TMcpTests.ToolsList_ListsTools;
var
  LResult, LTools: TJsonValue;
begin
  BuildCities;
  LResult := ParseJson(Request('tools/list', ''));
  try
    TAssert.AssertEquals(200, FStatus);
    TAssert.AssertEquals('complete', LResult.Find('result').Find('resultType').AsString);
    LTools := LResult.Find('result').Find('tools');
    TAssert.AssertEquals(4, LTools.Count);
    TAssert.AssertEquals('get_citie', LTools.Items[1].Find('name').AsString);
    TAssert.AssertEquals(FServer.Tools[1].InputSchema, LTools.Items[1].Find('inputSchema').ToJson);
    TAssert.AssertEquals('Get a city. Returns: code (string), name (string).',
      LTools.Items[1].Find('description').AsString);
  finally
    LResult.Free;
  end;
end;

procedure TMcpTests.Call_Get_PathAndQueryString;
begin
  BuildCities;
  FFake.Answer := '[{"code":"1","name":"A"}]';
  TAssert.AssertEquals('{"jsonrpc":"2.0","id":7,"result":{"resultType":"complete",' +
    '"content":[{"type":"text","text":"[{\"code\":\"1\",\"name\":\"A\"}]"}],"isError":false,' +
    SERVER_META + '}}', Call('list_citie', '{"state":"S P","page":2}'));
  TAssert.AssertEquals(200, FStatus);
  TAssert.AssertEquals('GET', FFake.Method);
  TAssert.AssertEquals('/cities?state=S%20P&page=2', FFake.PathAndQuery);
  TAssert.AssertEquals('', FFake.Body);

  Call('get_citie', '{"code":"42/x"}');
  TAssert.AssertEquals('/cities/42%2Fx', FFake.PathAndQuery);
  Call('list_citie', '{}');
  TAssert.AssertEquals('/cities', FFake.PathAndQuery);
  Call('list_citie', '{"state":null}');
  TAssert.AssertEquals('/cities', FFake.PathAndQuery);
end;

procedure TMcpTests.Call_Post_JsonBody;
begin
  BuildCities;
  Call('add_city', '{"name":"Lages","population":150000}');
  TAssert.AssertEquals('POST', FFake.Method);
  TAssert.AssertEquals('/cities', FFake.PathAndQuery);
  TAssert.AssertEquals('{"name":"Lages","population":150000}', FFake.Body);
end;

procedure TMcpTests.Call_ForwardsAuthorizationAndAddress;
begin
  BuildCities;
  Call('list_citie', '{}');
  TAssert.AssertEquals('Bearer abc', FFake.Forwarded.Authorization);
  TAssert.AssertEquals('10.0.0.7', FFake.Forwarded.ForwardedFor);
  TAssert.AssertEquals('00-4bf92f3577b34da6a3ce929d0e0e4736-00f067aa0ba902b7-01',
    FFake.Forwarded.TraceParent);
  TAssert.AssertEquals('vendor=1', FFake.Forwarded.TraceState);
end;

procedure TMcpTests.Call_ApiError_IsError;
begin
  BuildCities;
  FFake.Status := 404;
  FFake.Answer := '{"error":"City not found"}';
  TAssert.AssertTrue(Pos('"text":"{\"error\":\"City not found\"}"}],"isError":true',
    Call('get_citie', '{"code":"1"}')) > 0);
  TAssert.AssertEquals(200, FStatus);
end;

procedure TMcpTests.Call_ExecutorRaises_IsError;
begin
  BuildCities;
  FFake.Fail := True;
  TAssert.AssertTrue(Pos('"text":"Could not call the API: connection refused"}],"isError":true',
    Call('list_citie', '{}')) > 0);
end;

procedure TMcpTests.Call_MissingOrUnknownArgument_IsErrorWithoutCalling;
begin
  BuildCities;
  TAssert.AssertTrue(Pos('"text":"Missing required argument: code"}],"isError":true',
    Call('get_citie', '{}')) > 0);
  TAssert.AssertTrue(Pos('"text":"Missing required argument: name"}],"isError":true',
    Call('add_city', '{"population":1}')) > 0);
  TAssert.AssertTrue(Pos('"text":"Unknown argument: town"}],"isError":true',
    Call('list_citie', '{"town":"x"}')) > 0);
  TAssert.AssertEquals(0, FFake.Calls);
end;

procedure TMcpTests.Call_Base64NameHeader;
begin
  BuildCities;
  // "get_citie" in standard Base64, as a client sends a name it must encode.
  Post('{"jsonrpc":"2.0","id":7,"method":"tools/call","params":{' + META +
    ',"name":"get_citie","arguments":{"code":"1"}}}', 'tools/call', '=?base64?Z2V0X2NpdGll?=');
  TAssert.AssertEquals(200, FStatus);
  TAssert.AssertEquals(1, FFake.Calls);
end;

procedure TMcpTests.Notification_202NoBody;
begin
  TAssert.AssertEquals('', Post('{"jsonrpc":"2.0","method":"notifications/cancelled",' +
    '"params":{}}', ''));
  TAssert.AssertEquals(202, FStatus);
end;

procedure TMcpTests.Initialize_404NamesVersion;
var
  LText: string;
begin
  LText := Post('{"jsonrpc":"2.0","id":1,"method":"initialize","params":' +
    '{"protocolVersion":"2025-06-18","capabilities":{}}}', '', '', '');
  TAssert.AssertEquals(404, FStatus);
  TAssert.AssertTrue(LText, Pos('"code":-32601', LText) > 0);
  TAssert.AssertTrue(LText, Pos('2026-07-28', LText) > 0);
end;

procedure TMcpTests.MissingMeta_400InvalidParams;
var
  LText: string;
begin
  LText := Post('{"jsonrpc":"2.0","id":1,"method":"tools/list","params":{}}', 'tools/list');
  TAssert.AssertEquals(400, FStatus);
  TAssert.AssertTrue(LText, Pos('"code":-32602', LText) > 0);
  LText := Post('{"jsonrpc":"2.0","id":1,"method":"tools/list","params":{"_meta":' +
    '{"io.modelcontextprotocol/protocolVersion":"2026-07-28"}}}', 'tools/list');
  TAssert.AssertEquals(400, FStatus);
  TAssert.AssertTrue(LText, Pos('clientCapabilities', LText) > 0);
end;

procedure TMcpTests.UnsupportedVersion_400WithData;
begin
  TAssert.AssertEquals('{"jsonrpc":"2.0","id":1,"error":{"code":-32022,' +
    '"message":"Unsupported protocol version","data":{"supported":["2026-07-28"],' +
    '"requested":"2025-11-25"}}}',
    Post('{"jsonrpc":"2.0","id":1,"method":"tools/list","params":{"_meta":' +
    '{"io.modelcontextprotocol/protocolVersion":"2025-11-25",' +
    '"io.modelcontextprotocol/clientCapabilities":{}}}}', 'tools/list', '', '2025-11-25'));
  TAssert.AssertEquals(400, FStatus);
end;

procedure TMcpTests.HeaderMismatch_400;
var
  LText: string;
begin
  BuildCities;
  LText := Post('{"jsonrpc":"2.0","id":1,"method":"tools/list","params":{' + META + '}}',
    'tools/list', '', '');
  TAssert.AssertEquals(400, FStatus);
  TAssert.AssertTrue(LText, Pos('"code":-32020', LText) > 0);
  LText := Post('{"jsonrpc":"2.0","id":1,"method":"tools/list","params":{' + META + '}}',
    'server/discover');
  TAssert.AssertEquals(400, FStatus);
  TAssert.AssertTrue(LText, Pos('"code":-32020', LText) > 0);
  LText := Post('{"jsonrpc":"2.0","id":1,"method":"tools/call","params":{' + META +
    ',"name":"get_citie","arguments":{"code":"1"}}}', 'tools/call', 'list_citie');
  TAssert.AssertEquals(400, FStatus);
  TAssert.AssertTrue(LText, Pos('"code":-32020', LText) > 0);
  TAssert.AssertEquals(0, FFake.Calls);
end;

procedure TMcpTests.UnknownMethodAndTool;
var
  LText: string;
begin
  LText := Request('resources/list', '');
  TAssert.AssertEquals(404, FStatus);
  TAssert.AssertTrue(LText, Pos('"code":-32601', LText) > 0);
  LText := Call('nope', '{}');
  TAssert.AssertEquals(400, FStatus);
  TAssert.AssertTrue(LText, Pos('"code":-32602', LText) > 0);
end;

procedure TMcpTests.ParseErrorAndInvalidRequest;
var
  LText: string;
begin
  TAssert.AssertEquals('{"jsonrpc":"2.0","id":null,"error":{"code":-32700,"message":"Parse error"}}',
    Post('{nope', ''));
  TAssert.AssertEquals(400, FStatus);
  LText := Post('{"jsonrpc":"2.0","id":null,"method":"tools/list","params":{' + META + '}}',
    'tools/list');
  TAssert.AssertEquals(400, FStatus);
  TAssert.AssertTrue(LText, Pos('"code":-32600', LText) > 0);
end;

initialization
  RegisterTest(TMcpTests);

end.
