unit PascalApi.HttpTests;

{$mode delphi}{$H+}

{ GENERATED FILE — produced by tools/gen_fpc_mirror.py from
  tests/Unit/PascalApi.HttpTests.pas (DUnitX). Do not edit by hand: edit the DUnitX
  master and run the script again. }

{ Tests for PascalApi.Http: exception to status/message/log line, the error
  body, CORS headers, the Bearer header, excluded paths (whole segments),
  client IP, the request's trace context, the access log line (text and
  JSON), Retry-After and the replaceable messages.

  DUnitX master. The FPCUnit mirror (tests/Unit/fpc) is generated by
  tools/gen_fpc_mirror.py; never edit the mirror by hand. }

interface

uses
  fpcunit, testregistry,
  SysUtils,
  PascalJsonMapper.Json,
  PascalJsonMapper.Mapper,
  PascalDb.Interfaces,
  PascalApi.OrderBy,
  PascalApi.Text,
  PascalApi.Http;

type
  TErrorMappingTests = class(TTestCase)
  private
    function Map(E: Exception): TErrorResponse;
  protected
    procedure TearDown; override;
  published
    procedure HttpExceptions_KeepStatusAndMessage;
    procedure NotFound_DefaultMessage;
    procedure OrderBy_Is400;
    procedure Encoding_Is400_NotLogged;
    procedure JsonParseError_Is400;
    procedure JsonMapperErrorWithPath_Is400;
    procedure JsonMapperErrorWithoutPath_Is500;
    procedure ConstraintUniqueAndForeignKey_Are409_NotLogged;
    procedure ConstraintNotNullAndCheck_Are422_Logged;
    procedure LockConflict_Is409_Logged;
    procedure DatabaseUnavailable_Is503_DetailOnlyInLog;
    procedure Other_Is500_Logged;
    procedure Messages_CanBeReplaced;
    procedure ErrorJson_EscapesAndKeepsNonAscii;
  end;

  THttpHelpersTests = class(TTestCase)
  private
    function HeaderValue(const AHeaders: TArray<THttpHeader>; const AName: string): string;
  published
    procedure Cors_AnyOrigin;
    procedure Cors_ExactOrigin_Matches;
    procedure Cors_ExactOrigin_OtherOrigin_NoHeaders;
    procedure Cors_ExactOrigin_NoOrigin_NoHeaders;
    procedure Cors_OptionalHeaders;
    procedure Bearer_Results;
    procedure PathMatches_WholeSegments;
    procedure PathMatches_TrailingSlashPrefix;
    procedure PathMatches_IgnoresCase_AndEmpty;
    procedure ClientIp_Order;
    procedure Trace_FromTraceParent;
    procedure Trace_NotSampledParent_StaysNotSampled;
    procedure Trace_InvalidTraceParent_DropsTraceState;
    procedure Trace_FromRequestId32Hex;
    procedure Trace_OtherRequestIds_Ignored;
    procedure Trace_TraceParentWinsOverRequestId;
    procedure Trace_NewIds_Different;
    procedure AccessLogLine_Format;
    procedure AccessLogJson_Format;
    procedure AccessLogJson_LeavesOutEmpty_EscapesText;
    procedure WithTraceId_AppendsOnlyWhenPresent;
    procedure RetryAfter_NeverNegative;
  end;

implementation

{ TErrorMappingTests }

function TErrorMappingTests.Map(E: Exception): TErrorResponse;
begin
  try
    Result := MapException(E, 'POST', '/cities');
  finally
    E.Free;
  end;
end;

procedure TErrorMappingTests.TearDown;
begin
  TApiMessages.Current := TApiMessages.English;
end;

procedure TErrorMappingTests.HttpExceptions_KeepStatusAndMessage;
var
  R: TErrorResponse;
begin
  R := Map(EValidationException.Create('name is required'));
  TAssert.AssertEquals(400, R.Status);
  TAssert.AssertEquals('name is required', R.Message);
  TAssert.AssertEquals('', R.LogLine);
  TAssert.AssertEquals(409, Map(EConflictException.Create('x')).Status);
  TAssert.AssertEquals(418, Map(EHttpException.Create(418, 'teapot')).Status);
end;

procedure TErrorMappingTests.NotFound_DefaultMessage;
var
  R: TErrorResponse;
begin
  R := Map(ENotFoundException.Create);
  TAssert.AssertEquals(404, R.Status);
  TAssert.AssertEquals('Resource not found.', R.Message);
  TAssert.AssertEquals('City 7 not found.', Map(ENotFoundException.Create('City 7 not found.')).Message);
end;

procedure TErrorMappingTests.OrderBy_Is400;
var
  R: TErrorResponse;
begin
  R := Map(EOrderByException.Create('Invalid order field: "x"'));
  TAssert.AssertEquals(400, R.Status);
  TAssert.AssertEquals('Invalid order field: "x"', R.Message);
end;

procedure TErrorMappingTests.Encoding_Is400_NotLogged;
var
  R: TErrorResponse;
begin
  R := Map(EEncodingError.Create('No mapping for the Unicode character'));
  TAssert.AssertEquals(400, R.Status);
  TAssert.AssertEquals('The request text is not valid UTF-8.', R.Message);
  TAssert.AssertEquals('', R.LogLine);
  TAssert.AssertEquals(400, Map(ETextEncodingException.Create('x')).Status);
end;

procedure TErrorMappingTests.JsonParseError_Is400;
var
  R: TErrorResponse;
begin
  R := Map(EJsonParseError.CreatePos('Member name expected', 2));
  TAssert.AssertEquals(400, R.Status);
  TAssert.AssertEquals('Invalid request body: Member name expected (at position 2)', R.Message);
  TAssert.AssertEquals('', R.LogLine);
end;

procedure TErrorMappingTests.JsonMapperErrorWithPath_Is400;
var
  R: TErrorResponse;
begin
  R := Map(EJsonMapperError.Create('$.age: expected a number, found JSON string'));
  TAssert.AssertEquals(400, R.Status);
  TAssert.AssertEquals('Invalid request body: $.age: expected a number, found JSON string', R.Message);
end;

procedure TErrorMappingTests.JsonMapperErrorWithoutPath_Is500;
var
  R: TErrorResponse;
begin
  R := Map(EJsonMapperError.Create('Interface ICity has no mapping'));
  TAssert.AssertEquals(500, R.Status);
  TAssert.AssertTrue(R.LogLine <> '');
end;

procedure TErrorMappingTests.ConstraintUniqueAndForeignKey_Are409_NotLogged;
var
  R: TErrorResponse;
begin
  R := Map(EConstraintViolationException.Create(cvUnique, nil));
  TAssert.AssertEquals(409, R.Status);
  TAssert.AssertEquals('A record with these values already exists.', R.Message);
  TAssert.AssertEquals('', R.LogLine);
  R := Map(EConstraintViolationException.Create(cvForeignKey, nil));
  TAssert.AssertEquals(409, R.Status);
  TAssert.AssertEquals('', R.LogLine);
end;

procedure TErrorMappingTests.ConstraintNotNullAndCheck_Are422_Logged;
var
  R: TErrorResponse;
  LDriver: Exception;
begin
  LDriver := Exception.Create('NAME cannot be NULL');
  try
    R := Map(EConstraintViolationException.Create(cvNotNull, LDriver));
  finally
    LDriver.Free;
  end;
  TAssert.AssertEquals(422, R.Status);
  TAssert.AssertEquals('A required field is missing.', R.Message);
  TAssert.AssertTrue('method, path, status', Pos('POST /cities -> 422: EConstraintViolationException',
    R.LogLine) = 1);
  TAssert.AssertTrue('driver detail', Pos('(Exception: NAME cannot be NULL)', R.LogLine) > 0);
  TAssert.AssertEquals(422, Map(EConstraintViolationException.Create(cvCheck, nil)).Status);
end;

procedure TErrorMappingTests.LockConflict_Is409_Logged;
var
  R: TErrorResponse;
begin
  R := Map(ELockConflictException.Create(nil));
  TAssert.AssertEquals(409, R.Status);
  TAssert.AssertEquals('The record is locked or was changed by another operation. Try again.',
    R.Message);
  TAssert.AssertTrue(R.LogLine <> '');
end;

procedure TErrorMappingTests.DatabaseUnavailable_Is503_DetailOnlyInLog;
var
  R: TErrorResponse;
  LDriver: Exception;
begin
  LDriver := Exception.Create('connection refused 10.0.0.5:3050');
  try
    R := Map(EDatabaseUnavailableException.Create(LDriver));
  finally
    LDriver.Free;
  end;
  TAssert.AssertEquals(503, R.Status);
  TAssert.AssertEquals('The database is unavailable. Try again shortly.', R.Message);
  TAssert.AssertTrue('detail in the log', Pos('10.0.0.5', R.LogLine) > 0);
  TAssert.AssertTrue('never in the message', Pos('10.0.0.5', R.Message) = 0);
end;

procedure TErrorMappingTests.Other_Is500_Logged;
var
  R: TErrorResponse;
begin
  R := Map(EAccessViolation.Create('boom'));
  TAssert.AssertEquals(500, R.Status);
  TAssert.AssertEquals('boom', R.Message);
  TAssert.AssertEquals('POST /cities -> 500: EAccessViolation: boom', R.LogLine);
end;

procedure TErrorMappingTests.Messages_CanBeReplaced;
begin
  TApiMessages.Current := TApiMessages.Portuguese;
  TAssert.AssertEquals('Já existe um registro com estes dados.',
    Map(EConstraintViolationException.Create(cvUnique, nil)).Message);
  TAssert.AssertEquals('Recurso não encontrado.', Map(ENotFoundException.Create).Message);
end;

procedure TErrorMappingTests.ErrorJson_EscapesAndKeepsNonAscii;
var
  LParsed: TJsonValue;
begin
  TAssert.AssertEquals('{"error":"não encontrado"}', ErrorJson('não encontrado'));
  LParsed := ParseJson(ErrorJson('say "hi"\ now'#10));
  try
    TAssert.AssertEquals('say "hi"\ now'#10, LParsed.Find('error').AsString);
  finally
    LParsed.Free;
  end;
end;

{ THttpHelpersTests }

function THttpHelpersTests.HeaderValue(const AHeaders: TArray<THttpHeader>;
  const AName: string): string;
var
  I: Integer;
begin
  Result := '<absent>';
  for I := 0 to High(AHeaders) do
    if AHeaders[I].Name = AName then
      Exit(AHeaders[I].Value);
end;

procedure THttpHelpersTests.Cors_AnyOrigin;
var
  H: TArray<THttpHeader>;
begin
  H := CorsHeaders(TCorsOptions.Default, 'https://a.example');
  TAssert.AssertEquals('*', HeaderValue(H, 'Access-Control-Allow-Origin'));
  TAssert.AssertEquals('GET,POST,PUT,PATCH,DELETE,OPTIONS', HeaderValue(H, 'Access-Control-Allow-Methods'));
  TAssert.AssertEquals('Content-Type,Authorization', HeaderValue(H, 'Access-Control-Allow-Headers'));
  TAssert.AssertEquals('86400', HeaderValue(H, 'Access-Control-Max-Age'));
  TAssert.AssertEquals('no Vary with *', '<absent>', HeaderValue(H, 'Vary'));
  TAssert.AssertEquals('<absent>', HeaderValue(H, 'Access-Control-Allow-Credentials'));
  TAssert.AssertEquals('also without Origin', '*',
    HeaderValue(CorsHeaders(TCorsOptions.Default, ''), 'Access-Control-Allow-Origin'));
end;

procedure THttpHelpersTests.Cors_ExactOrigin_Matches;
var
  LOptions: TCorsOptions;
  H: TArray<THttpHeader>;
begin
  LOptions := TCorsOptions.Default;
  LOptions.AllowOrigin := 'https://app.example.com';
  H := CorsHeaders(LOptions, 'https://APP.example.com');
  TAssert.AssertEquals('https://APP.example.com', HeaderValue(H, 'Access-Control-Allow-Origin'));
  TAssert.AssertEquals('Origin', HeaderValue(H, 'Vary'));
end;

procedure THttpHelpersTests.Cors_ExactOrigin_OtherOrigin_NoHeaders;
var
  LOptions: TCorsOptions;
begin
  LOptions := TCorsOptions.Default;
  LOptions.AllowOrigin := 'https://app.example.com';
  TAssert.AssertEquals(0, Length(CorsHeaders(LOptions, 'https://evil.example')));
end;

procedure THttpHelpersTests.Cors_ExactOrigin_NoOrigin_NoHeaders;
var
  LOptions: TCorsOptions;
begin
  LOptions := TCorsOptions.Default;
  LOptions.AllowOrigin := 'https://app.example.com';
  TAssert.AssertEquals(0, Length(CorsHeaders(LOptions, '')));
end;

procedure THttpHelpersTests.Cors_OptionalHeaders;
var
  LOptions: TCorsOptions;
  H: TArray<THttpHeader>;
begin
  LOptions := TCorsOptions.Default;
  LOptions.AllowOrigin := 'https://app.example.com';
  LOptions.AllowCredentials := True;
  LOptions.ExposeHeaders := 'X-Total-Count';
  LOptions.MaxAge := 0;
  H := CorsHeaders(LOptions, 'https://app.example.com');
  TAssert.AssertEquals('true', HeaderValue(H, 'Access-Control-Allow-Credentials'));
  TAssert.AssertEquals('X-Total-Count', HeaderValue(H, 'Access-Control-Expose-Headers'));
  TAssert.AssertEquals('<absent>', HeaderValue(H, 'Access-Control-Max-Age'));
end;

procedure THttpHelpersTests.Bearer_Results;
var
  LToken: string;
begin
  TAssert.AssertTrue('ok', ParseBearer('Bearer abc.def', LToken) = brOk);
  TAssert.AssertEquals('abc.def', LToken);
  TAssert.AssertTrue('scheme case', ParseBearer('bearer   xyz  ', LToken) = brOk);
  TAssert.AssertEquals('xyz', LToken);
  TAssert.AssertTrue('missing', ParseBearer('', LToken) = brMissing);
  TAssert.AssertTrue('basic', ParseBearer('Basic dXNlcjpwYXNz', LToken) = brNotBearer);
  TAssert.AssertTrue('no space', ParseBearer('Bearerabc', LToken) = brNotBearer);
  TAssert.AssertTrue('empty token', ParseBearer('Bearer    ', LToken) = brEmpty);
end;

procedure THttpHelpersTests.PathMatches_WholeSegments;
begin
  TAssert.AssertTrue('equal', PathMatchesAny('/auth/login', ['/health', '/auth/login']));
  TAssert.AssertTrue('below', PathMatchesAny('/swagger/index.html', ['/swagger']));
  TAssert.AssertFalse('sibling with longer name', PathMatchesAny('/auth/login-admin', ['/auth/login']));
  TAssert.AssertFalse('healthz', PathMatchesAny('/healthz', ['/health']));
  TAssert.AssertFalse('other', PathMatchesAny('/cities', ['/health', '/swagger']));
end;

procedure THttpHelpersTests.PathMatches_TrailingSlashPrefix;
begin
  TAssert.AssertTrue(PathMatchesAny('/public/x', ['/public/']));
  TAssert.AssertFalse(PathMatchesAny('/public', ['/public/']));
end;

procedure THttpHelpersTests.PathMatches_IgnoresCase_AndEmpty;
begin
  TAssert.AssertTrue(PathMatchesAny('/Health', ['/health']));
  TAssert.AssertFalse('an empty prefix matches nothing', PathMatchesAny('/cities', ['']));
  TAssert.AssertFalse('no prefixes', PathMatchesAny('/cities', []));
end;

procedure THttpHelpersTests.ClientIp_Order;
begin
  TAssert.AssertEquals('203.0.113.7', ClientIp('203.0.113.7, 10.0.0.1', '10.0.0.2', '-'));
  TAssert.AssertEquals('203.0.113.7', ClientIp(' 203.0.113.7 ', '10.0.0.2', '-'));
  TAssert.AssertEquals('10.0.0.2', ClientIp('', '10.0.0.2', '-'));
  TAssert.AssertEquals('unknown', ClientIp('', '', 'unknown'));
end;

const
  TRACE_ID = '4bf92f3577b34da6a3ce929d0e0e4736';
  PARENT_ID = '00f067aa0ba902b7';
  TRACE_PARENT = '00-' + TRACE_ID + '-' + PARENT_ID + '-01';

function IsLowerHex(const AValue: string; ALength: Integer): Boolean;
var
  I: Integer;
begin
  Result := Length(AValue) = ALength;
  if Result then
    for I := 1 to ALength do
      if not CharInSet(AValue[I], ['0'..'9', 'a'..'f']) then
        Exit(False);
end;

procedure THttpHelpersTests.Trace_FromTraceParent;
var
  T: TRequestTrace;
begin
  T := ResolveRequestTrace(TRACE_PARENT, 'vendor=1', '');
  TAssert.AssertEquals(TRACE_ID, T.TraceId);
  TAssert.AssertEquals(PARENT_ID, T.ParentSpanId);
  TAssert.AssertTrue(T.Sampled);
  TAssert.AssertEquals('vendor=1', T.TraceState);
  TAssert.AssertTrue('span id: ' + T.SpanId, IsLowerHex(T.SpanId, 16));
  TAssert.AssertTrue('a new span, not the caller''s', T.SpanId <> PARENT_ID);
  TAssert.AssertEquals('00-' + TRACE_ID + '-' + T.SpanId + '-01', T.TraceParent);
end;

procedure THttpHelpersTests.Trace_NotSampledParent_StaysNotSampled;
var
  T: TRequestTrace;
begin
  T := ResolveRequestTrace('00-' + TRACE_ID + '-' + PARENT_ID + '-00', '', '');
  TAssert.AssertFalse(T.Sampled);
  TAssert.AssertEquals('00-' + TRACE_ID + '-' + T.SpanId + '-00', T.TraceParent);
end;

procedure THttpHelpersTests.Trace_InvalidTraceParent_DropsTraceState;
var
  T: TRequestTrace;
begin
  // Uppercase hex is invalid: a new trace, the tracestate not passed on.
  T := ResolveRequestTrace('00-4BF92F3577B34DA6A3CE929D0E0E4736-00F067AA0BA902B7-01',
    'vendor=1', '');
  TAssert.AssertTrue('trace id: ' + T.TraceId, IsLowerHex(T.TraceId, 32));
  TAssert.AssertTrue('the invalid header''s id was adopted', T.TraceId <> TRACE_ID);
  TAssert.AssertEquals('', T.ParentSpanId);
  TAssert.AssertEquals('', T.TraceState);
  TAssert.AssertTrue(T.Sampled);
end;

procedure THttpHelpersTests.Trace_FromRequestId32Hex;
var
  T: TRequestTrace;
begin
  T := ResolveRequestTrace('', '', TRACE_ID);
  TAssert.AssertEquals(TRACE_ID, T.TraceId);
  TAssert.AssertEquals('', T.ParentSpanId);
  TAssert.AssertTrue(T.Sampled);
end;

procedure THttpHelpersTests.Trace_OtherRequestIds_Ignored;
const
  IDS: array[0..4] of string = ('1a2b3c4d', 'hello world',
    '4BF92F3577B34DA6A3CE929D0E0E4736', '00000000000000000000000000000000',
    '4bf92f3577b34da6a3ce929d0e0e4736 ');
var
  I: Integer;
  T: TRequestTrace;
begin
  for I := 0 to High(IDS) do
  begin
    T := ResolveRequestTrace('', '', IDS[I]);
    TAssert.AssertTrue(IDS[I] + ' -> ' + T.TraceId, IsLowerHex(T.TraceId, 32));
    TAssert.AssertTrue(IDS[I] + ' adopted', T.TraceId <> TRACE_ID);
    TAssert.AssertTrue(IDS[I] + ' -> zeros', T.TraceId <> '00000000000000000000000000000000');
  end;
end;

procedure THttpHelpersTests.Trace_TraceParentWinsOverRequestId;
begin
  TAssert.AssertEquals(TRACE_ID,
    ResolveRequestTrace(TRACE_PARENT, '', 'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa').TraceId);
end;

procedure THttpHelpersTests.Trace_NewIds_Different;
var
  A, B: TRequestTrace;
begin
  A := ResolveRequestTrace('', '', '');
  B := ResolveRequestTrace('', '', '');
  TAssert.AssertTrue('trace id: ' + A.TraceId, IsLowerHex(A.TraceId, 32));
  TAssert.AssertTrue('span id: ' + A.SpanId, IsLowerHex(A.SpanId, 16));
  TAssert.AssertTrue(A.TraceId <> B.TraceId);
  TAssert.AssertTrue(A.SpanId <> B.SpanId);
end;

procedure THttpHelpersTests.AccessLogLine_Format;
begin
  TAssert.AssertEquals(
    '[2025-01-01 12:00:05] GET /cities 200 12ms 10.0.0.2 512 "page=2" "curl/8.0" 1a2b3c4d',
    AccessLogLine(EncodeDate(2025, 1, 1) + EncodeTime(12, 0, 5, 0), 'GET', '/cities', 200, 12,
      '10.0.0.2', '512', 'page=2', 'curl/8.0', '1a2b3c4d'));
  TAssert.AssertEquals('[2025-01-01 00:00:00] POST /x 500 0ms - - "-" "-" id',
    AccessLogLine(EncodeDate(2025, 1, 1), 'POST', '/x', 500, 0, '', '', '', '', 'id'));
end;

function SampleTrace: TRequestTrace;
begin
  Result.TraceId := TRACE_ID;
  Result.SpanId := 'b7ad6b7169203331';
  Result.ParentSpanId := PARENT_ID;
  Result.Sampled := True;
  Result.TraceState := '';
end;

procedure THttpHelpersTests.AccessLogJson_Format;
begin
  TAssert.AssertEquals('{"time":"2025-01-01T12:00:05.250","trace_id":"' + TRACE_ID +
    '","span_id":"b7ad6b7169203331","parent_span_id":"' + PARENT_ID +
    '","method":"GET","path":"/cities","status":200,"duration_ms":12,' +
    '"client_ip":"10.0.0.2","bytes":512,"query":"page=2","user_agent":"curl/8.0"}',
    AccessLogJson(EncodeDate(2025, 1, 1) + EncodeTime(12, 0, 5, 250), 'GET', '/cities', 200, 12,
      '10.0.0.2', '512', 'page=2', 'curl/8.0', SampleTrace));
end;

procedure THttpHelpersTests.AccessLogJson_LeavesOutEmpty_EscapesText;
var
  T: TRequestTrace;
begin
  T := SampleTrace;
  T.ParentSpanId := '';
  TAssert.AssertEquals('{"time":"2025-01-01T00:00:00.000","trace_id":"' + TRACE_ID +
    '","span_id":"b7ad6b7169203331","method":"POST","path":"/x","status":500,' +
    '"duration_ms":0,"user_agent":"a \"b\" São"}',
    AccessLogJson(EncodeDate(2025, 1, 1), 'POST', '/x', 500, 0, '', '', '', 'a "b" São', T));
end;

procedure THttpHelpersTests.WithTraceId_AppendsOnlyWhenPresent;
begin
  TAssert.AssertEquals('GET /x -> 500: E (E: m) trace_id=' + TRACE_ID,
    WithTraceId('GET /x -> 500: E (E: m)', TRACE_ID));
  TAssert.AssertEquals('GET /x -> 500', WithTraceId('GET /x -> 500', ''));
end;

procedure THttpHelpersTests.RetryAfter_NeverNegative;
begin
  TAssert.AssertEquals(Int64(30), RetryAfterSeconds(1030, 1000));
  TAssert.AssertEquals(Int64(0), RetryAfterSeconds(1000, 1005));
end;

initialization
  RegisterTest(TErrorMappingTests);
  RegisterTest(THttpHelpersTests);

end.
