unit PascalApi.VersionTests;

{$mode delphi}{$H+}

{ GENERATED FILE — produced by tools/gen_fpc_mirror.py from
  tests/Unit/PascalApi.VersionTests.pas (DUnitX). Do not edit by hand: edit the DUnitX
  master and run the script again. }

{ Tests for PascalApi.Version: the version constants agree with each other,
  so a release that bumps one and forgets another fails here.

  DUnitX master. The FPCUnit mirror (tests/Unit/fpc) is generated by
  tools/gen_fpc_mirror.py; never edit the mirror by hand. }

interface

uses
  fpcunit, testregistry,
  SysUtils,
  PascalApi.Version;

type
  TVersionTests = class(TTestCase)
  published
    procedure Number_MatchesTheParts;
    procedure Text_MatchesTheParts;
  end;

implementation

procedure TVersionTests.Number_MatchesTheParts;
begin
  TAssert.AssertEquals(PASCALAPI_VERSION_MAJOR * 10000 + PASCALAPI_VERSION_MINOR * 100 +
    PASCALAPI_VERSION_PATCH, PASCALAPI_VERSION);
end;

procedure TVersionTests.Text_MatchesTheParts;
begin
  TAssert.AssertEquals(Format('%d.%d.%d', [PASCALAPI_VERSION_MAJOR, PASCALAPI_VERSION_MINOR,
    PASCALAPI_VERSION_PATCH]), PASCALAPI_VERSION_STRING);
end;

initialization
  RegisterTest(TVersionTests);

end.
