unit PascalApi.CryptoTests;

{$mode delphi}{$H+}

{ GENERATED FILE — produced by tools/gen_fpc_mirror.py from
  tests/Unit/PascalApi.CryptoTests.pas (DUnitX). Do not edit by hand: edit the DUnitX
  master and run the script again. }

{ Tests for PascalApi.Crypto (SHA-256, HMAC-SHA256, Base64url) and
  PascalApi.Jwt (HS256 sign/verify, alg check, exp/nbf).

  Vectors: SHA-256 from FIPS 180-4's examples plus lengths around the
  64-byte block (computed with Python's hashlib); HMAC from RFC 4231 test
  cases 1, 2, 3, 6 and 7; Base64url from RFC 4648 section 10; the HS256
  token is jwt.io's well-known example, recomputed with Python's hmac.
  Time for exp/nbf comes from a fixed clock installed in TClock.

  DUnitX master. The FPCUnit mirror (tests/Unit/fpc) is generated by
  tools/gen_fpc_mirror.py; never edit the mirror by hand. }

interface

uses
  fpcunit, testregistry,
  SysUtils,
  DateUtils,
  PascalCommon.SystemContext,
  PascalJsonMapper.Json,
  PascalApi.Text,
  PascalApi.Crypto,
  PascalApi.Jwt;

type
  TJwtClock = class(TInterfacedObject, IClock)
  private
    FTime: TDateTime;
  public
    constructor Create(AUnix: Int64);
    function Now: TDateTime;
    function Date: TDateTime;
  end;

  TCryptoTests = class(TTestCase)
  published
    procedure Sha256_Fips180Examples;
    procedure Sha256_AroundBlockBoundary;
    procedure Sha256_OneMillionA;
    procedure Sha256_NonAsciiHashesUtf8;
    procedure Hmac_Rfc4231;
    procedure Base64Url_Rfc4648;
    procedure Base64Url_UrlAlphabet;
    procedure Base64Url_DecodeRoundTrip;
    procedure Base64Url_DecodeRejectsInvalid;
    procedure SameBytes;
  end;

  TJwtTests = class(TTestCase)
  protected
    procedure TearDown; override;
  published
    procedure Sign_JwtIoExample;
    procedure Decode_Valid_ReturnsClaims;
    procedure Decode_NonAsciiClaimsAndSecret;
    procedure Decode_WrongSecret_BadSignature;
    procedure Decode_TamperedPayload_BadSignature;
    procedure Decode_AlgNone_Refused;
    procedure Decode_Malformed;
    procedure Decode_Expired;
    procedure Decode_ExpBoundary;
    procedure Decode_NotYetValid;
    procedure Decode_ExpNotANumber_Malformed;
    procedure Validate_MatchesDecode;
    procedure UnixNow_FollowsTClock;
  end;

implementation

const
  JWT_IO_TOKEN = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.' +
    'eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.' +
    'SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c';
  JWT_IO_CLAIMS = '{"sub":"1234567890","name":"John Doe","iat":1516239022}';
  JWT_IO_SECRET = 'your-256-bit-secret';

function Utf8(const S: string): TBytes;
begin
  Result := PaStringToUtf8Bytes(S);
end;

function Repeated(AByte: Byte; ACount: Integer): TBytes;
begin
  Result := nil;
  SetLength(Result, ACount);
  if ACount > 0 then
    FillChar(Result[0], ACount, AByte);
end;

function Sha256Hex(const ABytes: TBytes): string;
begin
  Result := PaBytesToHex(PaDigestToBytes(PaSha256(ABytes)));
end;

function HmacHex(const AKey, AData: TBytes): string;
begin
  Result := PaBytesToHex(PaDigestToBytes(PaHmacSha256(AKey, AData)));
end;

function Encode(const S: string): string;
begin
  Result := PaBase64UrlEncode(Utf8(S));
end;

procedure UseClock(AUnix: Int64);
begin
  TClock.SetClock(TJwtClock.Create(AUnix));
end;

function DecodeResult(const AToken, ASecret: string): TJwtResult;
var
  LClaims: TJsonValue;
begin
  Result := TJwt.Decode(AToken, ASecret, LClaims);
  if (Result = jrValid) <> Assigned(LClaims) then
    Result := jrMalformed; // claims must come exactly with jrValid
  LClaims.Free;
end;

{ TJwtClock }

constructor TJwtClock.Create(AUnix: Int64);
begin
  inherited Create;
  FTime := UnixToDateTime(AUnix, False);
end;

function TJwtClock.Now: TDateTime;
begin
  Result := FTime;
end;

function TJwtClock.Date: TDateTime;
begin
  Result := Trunc(FTime);
end;

{ TCryptoTests }

procedure TCryptoTests.Sha256_Fips180Examples;
begin
  TAssert.AssertEquals('e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855',
    Sha256Hex(nil));
  TAssert.AssertEquals('ba7816bf8f01cfea414140de5dae2223b00361a396177a9cb410ff61f20015ad',
    Sha256Hex(Utf8('abc')));
  TAssert.AssertEquals('248d6a61d20638b8e5c026930c3e6039a33ce45964ff2167f6ecedd419db06c1',
    Sha256Hex(Utf8('abcdbcdecdefdefgefghfghighijhijkijkljklmklmnlmnomnopnopq')));
end;

procedure TCryptoTests.Sha256_AroundBlockBoundary;
begin
  TAssert.AssertEquals('55', '9f4390f8d30c2dd92ec9f095b65e2b9ae9b0a925a5258e241c9f1e910f734318',
    Sha256Hex(Repeated(Ord('a'), 55)));
  TAssert.AssertEquals('56', 'b35439a4ac6f0948b6d6f9e3c6af0f5f590ce20f1bde7090ef7970686ec6738a',
    Sha256Hex(Repeated(Ord('a'), 56)));
  TAssert.AssertEquals('63', '7d3e74a05d7db15bce4ad9ec0658ea98e3f06eeecf16b4c6fff2da457ddc2f34',
    Sha256Hex(Repeated(Ord('a'), 63)));
  TAssert.AssertEquals('64', 'ffe054fe7ae0cb6dc65c3af9b61d5209f439851db43d0ba5997337df154668eb',
    Sha256Hex(Repeated(Ord('a'), 64)));
  TAssert.AssertEquals('65', '635361c48bb9eab14198e76ea8ab7f1a41685d6ad62aa9146d301d4f17eb0ae0',
    Sha256Hex(Repeated(Ord('a'), 65)));
  TAssert.AssertEquals('119', '31eba51c313a5c08226adf18d4a359cfdfd8d2e816b13f4af952f7ea6584dcfb',
    Sha256Hex(Repeated(Ord('a'), 119)));
  TAssert.AssertEquals('120', '2f3d335432c70b580af0e8e1b3674a7c020d683aa5f73aaaedfdc55af904c21c',
    Sha256Hex(Repeated(Ord('a'), 120)));
end;

procedure TCryptoTests.Sha256_OneMillionA;
begin
  TAssert.AssertEquals('cdc76e5c9914fb9281a1c7e284d73e67f1809a48a497200e046d39ccc7112cd0',
    Sha256Hex(Repeated(Ord('a'), 1000000)));
end;

procedure TCryptoTests.Sha256_NonAsciiHashesUtf8;
begin
  TAssert.AssertEquals('99c3d6caccd648574aa0f41f7ae30f7529df276183e187d5db4262f292843b7f',
    Sha256Hex(Utf8('São Paulo → ok')));
end;

procedure TCryptoTests.Hmac_Rfc4231;
begin
  TAssert.AssertEquals('case 1', 'b0344c61d8db38535ca8afceaf0bf12b881dc200c9833da726e9376c2e32cff7',
    HmacHex(Repeated($0b, 20), Utf8('Hi There')));
  TAssert.AssertEquals('case 2', '5bdcc146bf60754e6a042426089575c75a003f089d2739839dec58b964ec3843',
    HmacHex(Utf8('Jefe'), Utf8('what do ya want for nothing?')));
  TAssert.AssertEquals('case 3', '773ea91e36800e46854db8ebd09181a72959098b3ef8c122d9635514ced565fe',
    HmacHex(Repeated($aa, 20), Repeated($dd, 50)));
  TAssert.AssertEquals('case 6', '60e431591ee0b67f0d8a26aacbf5b77f8e0bc6213728c5140546040f0ee37f54',
    HmacHex(Repeated($aa, 131), Utf8('Test Using Larger Than Block-Size Key - Hash Key First')));
  TAssert.AssertEquals('case 7', '9b09ffa71b942fcb27635fbcd5b0e944bfdc63644f0713938a7f51535c3a35e2',
    HmacHex(Repeated($aa, 131), Utf8('This is a test using a larger than block-size key and a ' +
      'larger than block-size data. The key needs to be hashed before being used by the HMAC ' +
      'algorithm.')));
end;

procedure TCryptoTests.Base64Url_Rfc4648;
begin
  TAssert.AssertEquals('', Encode(''));
  TAssert.AssertEquals('Zg', Encode('f'));
  TAssert.AssertEquals('Zm8', Encode('fo'));
  TAssert.AssertEquals('Zm9v', Encode('foo'));
  TAssert.AssertEquals('Zm9vYg', Encode('foob'));
  TAssert.AssertEquals('Zm9vYmE', Encode('fooba'));
  TAssert.AssertEquals('Zm9vYmFy', Encode('foobar'));
end;

procedure TCryptoTests.Base64Url_UrlAlphabet;
var
  LBytes: TBytes;
begin
  // FB FF BF is "+/+/" in standard Base64.
  LBytes := nil;
  SetLength(LBytes, 3);
  LBytes[0] := $FB;
  LBytes[1] := $FF;
  LBytes[2] := $BF;
  TAssert.AssertEquals('-_-_', PaBase64UrlEncode(LBytes));
  TAssert.AssertEquals('-_8', PaBase64UrlEncode(Copy(LBytes, 0, 2)));
end;

procedure TCryptoTests.Base64Url_DecodeRoundTrip;
var
  LBytes: TBytes;
  I: Integer;
begin
  for I := 0 to 6 do
  begin
    TAssert.AssertTrue(PaBase64UrlDecode(Encode(Copy('foobar', 1, I)), LBytes));
    TAssert.AssertEquals(Copy('foobar', 1, I), PaUtf8BytesToString(LBytes, 'test'));
  end;
  TAssert.AssertTrue('padding accepted', PaBase64UrlDecode('Zg==', LBytes));
  TAssert.AssertEquals('f', PaUtf8BytesToString(LBytes, 'test'));
end;

procedure TCryptoTests.Base64Url_DecodeRejectsInvalid;
var
  LBytes: TBytes;
begin
  TAssert.AssertFalse('standard alphabet', PaBase64UrlDecode('ab+/', LBytes));
  TAssert.AssertFalse('space', PaBase64UrlDecode('Zm 9v', LBytes));
  TAssert.AssertFalse('4n+1 characters', PaBase64UrlDecode('Zm9vY', LBytes));
end;

procedure TCryptoTests.SameBytes;
begin
  TAssert.AssertTrue(PaSameBytes(Utf8('abc'), Utf8('abc')));
  TAssert.AssertFalse(PaSameBytes(Utf8('abc'), Utf8('abd')));
  TAssert.AssertFalse(PaSameBytes(Utf8('abc'), Utf8('abcd')));
  TAssert.AssertTrue(PaSameBytes(nil, nil));
end;

{ TJwtTests }

procedure TJwtTests.TearDown;
begin
  TClock.Reset;
end;

procedure TJwtTests.Sign_JwtIoExample;
begin
  TAssert.AssertEquals(JWT_IO_TOKEN, TJwt.SignHS256(JWT_IO_CLAIMS, JWT_IO_SECRET));
end;

procedure TJwtTests.Decode_Valid_ReturnsClaims;
var
  LClaims: TJsonValue;
begin
  TAssert.AssertTrue(TJwt.Decode(JWT_IO_TOKEN, JWT_IO_SECRET, LClaims) = jrValid);
  try
    TAssert.AssertEquals('1234567890', LClaims.Find('sub').AsString);
    TAssert.AssertEquals('John Doe', LClaims.Find('name').AsString);
    TAssert.AssertEquals(Int64(1516239022), LClaims.Find('iat').AsInt64);
  finally
    LClaims.Free;
  end;
end;

procedure TJwtTests.Decode_NonAsciiClaimsAndSecret;
const
  // Computed with Python: claims {"sub":"42","name":"João"}, secret 'segredo-ç'.
  TOKEN = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI0MiIsIm5hbWUiOiJKb8OjbyJ9.' +
    'IgY1EuntlNAsJo45zwvAw7u4DMpXsOX2LxlVDg-2jzc';
var
  LClaims: TJsonValue;
begin
  TAssert.AssertEquals(TOKEN, TJwt.SignHS256('{"sub":"42","name":"João"}', 'segredo-ç'));
  TAssert.AssertTrue(TJwt.Decode(TOKEN, 'segredo-ç', LClaims) = jrValid);
  try
    TAssert.AssertEquals('João', LClaims.Find('name').AsString);
  finally
    LClaims.Free;
  end;
end;

procedure TJwtTests.Decode_WrongSecret_BadSignature;
begin
  TAssert.AssertTrue(DecodeResult(JWT_IO_TOKEN, 'other-secret') = jrBadSignature);
end;

procedure TJwtTests.Decode_TamperedPayload_BadSignature;
var
  LToken: string;
begin
  // Same header and signature, payload with another subject.
  LToken := Copy(JWT_IO_TOKEN, 1, Pos('.', JWT_IO_TOKEN)) +
    Encode('{"sub":"admin","name":"John Doe","iat":1516239022}') +
    Copy(JWT_IO_TOKEN, LastDelimiter('.', JWT_IO_TOKEN), MaxInt);
  TAssert.AssertTrue(DecodeResult(LToken, JWT_IO_SECRET) = jrBadSignature);
end;

procedure TJwtTests.Decode_AlgNone_Refused;
begin
  TAssert.AssertTrue(DecodeResult(Encode('{"alg":"none","typ":"JWT"}') + '.' +
    Encode(JWT_IO_CLAIMS) + '.', JWT_IO_SECRET) = jrUnsupportedAlg);
  TAssert.AssertTrue(DecodeResult(Encode('{"alg":"HS512"}') + '.' + Encode(JWT_IO_CLAIMS) +
    '.abc', JWT_IO_SECRET) = jrUnsupportedAlg);
end;

procedure TJwtTests.Decode_Malformed;
begin
  TAssert.AssertTrue('empty', DecodeResult('', JWT_IO_SECRET) = jrMalformed);
  TAssert.AssertTrue('two parts', DecodeResult('abc.def', JWT_IO_SECRET) = jrMalformed);
  TAssert.AssertTrue('four parts', DecodeResult(JWT_IO_TOKEN + '.x', JWT_IO_SECRET) = jrMalformed);
  TAssert.AssertTrue('header not base64url', DecodeResult('a+b.' + Encode(JWT_IO_CLAIMS) + '.x',
    JWT_IO_SECRET) = jrMalformed);
  TAssert.AssertTrue('header not JSON', DecodeResult(Encode('hello') + '.' +
    Encode(JWT_IO_CLAIMS) + '.x', JWT_IO_SECRET) = jrMalformed);
  TAssert.AssertTrue('payload not an object', DecodeResult(
    TJwt.SignHS256('[1,2]', JWT_IO_SECRET), JWT_IO_SECRET) = jrMalformed);
end;

procedure TJwtTests.Decode_Expired;
begin
  UseClock(2000000000);
  TAssert.AssertTrue(DecodeResult(TJwt.SignHS256('{"exp":1999999999}', 's'), 's') = jrExpired);
  TAssert.AssertTrue(DecodeResult(TJwt.SignHS256('{"exp":2000000100}', 's'), 's') = jrValid);
end;

procedure TJwtTests.Decode_ExpBoundary;
begin
  // RFC 7519: the token must not be accepted on or after exp.
  UseClock(2000000000);
  TAssert.AssertTrue(DecodeResult(TJwt.SignHS256('{"exp":2000000000}', 's'), 's') = jrExpired);
  TAssert.AssertTrue(DecodeResult(TJwt.SignHS256('{"exp":2000000001}', 's'), 's') = jrValid);
end;

procedure TJwtTests.Decode_NotYetValid;
begin
  UseClock(2000000000);
  TAssert.AssertTrue(DecodeResult(TJwt.SignHS256('{"nbf":2000000001}', 's'), 's') = jrNotYetValid);
  TAssert.AssertTrue(DecodeResult(TJwt.SignHS256('{"nbf":2000000000}', 's'), 's') = jrValid);
end;

procedure TJwtTests.Decode_ExpNotANumber_Malformed;
begin
  TAssert.AssertTrue(DecodeResult(TJwt.SignHS256('{"exp":"tomorrow"}', 's'), 's') = jrMalformed);
end;

procedure TJwtTests.Validate_MatchesDecode;
begin
  TAssert.AssertTrue(TJwt.Validate(JWT_IO_TOKEN, JWT_IO_SECRET));
  TAssert.AssertFalse(TJwt.Validate(JWT_IO_TOKEN, 'x'));
end;

procedure TJwtTests.UnixNow_FollowsTClock;
begin
  UseClock(1767225600);
  TAssert.AssertEquals(Int64(1767225600), TJwt.UnixNow);
end;

initialization
  RegisterTest(TCryptoTests);
  RegisterTest(TJwtTests);

end.
