unit PascalApi.PaginationTests;

{$mode delphi}{$H+}

{ GENERATED FILE — produced by tools/gen_fpc_mirror.py from
  tests/Unit/PascalApi.PaginationTests.pas (DUnitX). Do not edit by hand: edit the DUnitX
  master and run the script again. }

{ Tests for PascalApi.Pagination: query-string parsing, page request from
  optionals, and the JSON envelope. TPageRequest/TPageMeta themselves are
  tested in pascal-db-faa.

  DUnitX master. The FPCUnit mirror (tests/Unit/fpc) is generated by
  tools/gen_fpc_mirror.py; never edit the mirror by hand. }

interface

uses
  fpcunit, testregistry,
  SysUtils,
  PascalCommon.Optionals,
  PascalDb.Paging,
  PascalApi.Pagination;

type
  TPaginationTests = class(TTestCase)
  published
    procedure ParseQueryInt_Number;
    procedure ParseQueryInt_EmptyOrInvalid_IsAbsentNotNil;
    procedure ParseQueryStr_Text;
    procedure ParseQueryStr_Empty_IsAbsentNotNil;

    procedure PageRequestFrom_Nil_UsesDefaults;
    procedure PageRequestFrom_Values;
    procedure PageRequestFrom_Offset;
    procedure PageRequestFrom_LimitAboveMax_IsClamped;
    procedure PageRequestFrom_PageBelowOne_IsOne;
    procedure PageRequestFrom_LimitBelowOne_IsDefault;
    procedure PageRequestFrom_CustomDefaults;

    procedure Envelope_ExactText;
    procedure Envelope_LastPage;
    procedure Envelope_Empty_HasOnePage;
    procedure Envelope_TotalAboveInt32;
  end;

implementation

function Meta(APage, ALimit: Integer; ATotal: Int64): TPageMeta;
begin
  Result := TPageMeta.Create(TPageRequest.Create(APage, ALimit), ATotal);
end;

procedure TPaginationTests.ParseQueryInt_Number;
var
  LValue: IOptInteger;
begin
  LValue := ParseQueryInt('42');
  TAssert.AssertTrue(Assigned(LValue) and LValue.HasValue);
  TAssert.AssertEquals(42, LValue.Value);
end;

procedure TPaginationTests.ParseQueryInt_EmptyOrInvalid_IsAbsentNotNil;
var
  LText: string;
  LValue: IOptInteger;
begin
  for LText in TArray<string>.Create('', 'abc', '1.5') do
  begin
    LValue := ParseQueryInt(LText);
    TAssert.AssertTrue('assigned: "' + LText + '"', Assigned(LValue));
    TAssert.AssertFalse('absent: "' + LText + '"', LValue.HasValue);
  end;
end;

procedure TPaginationTests.ParseQueryStr_Text;
var
  LValue: IOptString;
begin
  LValue := ParseQueryStr('São');
  TAssert.AssertTrue(Assigned(LValue) and LValue.HasValue);
  TAssert.AssertEquals('São', LValue.Value);
end;

procedure TPaginationTests.ParseQueryStr_Empty_IsAbsentNotNil;
var
  LValue: IOptString;
begin
  LValue := ParseQueryStr('');
  TAssert.AssertTrue(Assigned(LValue));
  TAssert.AssertFalse(LValue.HasValue);
end;

procedure TPaginationTests.PageRequestFrom_Nil_UsesDefaults;
var
  LPage: TPageRequest;
begin
  LPage := PageRequestFrom(nil, nil);
  TAssert.AssertEquals(1, LPage.Page);
  TAssert.AssertEquals(PDB_PAGE_DEFAULT_LIMIT, LPage.Limit);
end;

procedure TPaginationTests.PageRequestFrom_Values;
var
  LPage: TPageRequest;
begin
  LPage := PageRequestFrom(TOptNullInteger.From(3), TOptNullInteger.From(15));
  TAssert.AssertEquals(3, LPage.Page);
  TAssert.AssertEquals(15, LPage.Limit);
end;

procedure TPaginationTests.PageRequestFrom_Offset;
begin
  TAssert.AssertEquals(Int64(20),
    PageRequestFrom(TOptNullInteger.From(3), TOptNullInteger.From(10)).Offset);
  TAssert.AssertEquals(Int64(0),
    PageRequestFrom(TOptNullInteger.From(1), TOptNullInteger.From(20)).Offset);
end;

procedure TPaginationTests.PageRequestFrom_LimitAboveMax_IsClamped;
begin
  TAssert.AssertEquals(PDB_PAGE_MAX_LIMIT,
    PageRequestFrom(nil, TOptNullInteger.From(PDB_PAGE_MAX_LIMIT + 1)).Limit);
end;

procedure TPaginationTests.PageRequestFrom_PageBelowOne_IsOne;
begin
  TAssert.AssertEquals(1, PageRequestFrom(TOptNullInteger.From(0), nil).Page);
  TAssert.AssertEquals(1, PageRequestFrom(TOptNullInteger.From(-5), nil).Page);
end;

procedure TPaginationTests.PageRequestFrom_LimitBelowOne_IsDefault;
begin
  TAssert.AssertEquals(PDB_PAGE_DEFAULT_LIMIT,
    PageRequestFrom(nil, TOptNullInteger.From(0)).Limit);
end;

procedure TPaginationTests.PageRequestFrom_CustomDefaults;
var
  LPage: TPageRequest;
begin
  LPage := PageRequestFrom(nil, nil, 5, 50);
  TAssert.AssertEquals(5, LPage.Limit);
  LPage := PageRequestFrom(nil, TOptNullInteger.From(80), 5, 50);
  TAssert.AssertEquals(50, LPage.Limit);
end;

procedure TPaginationTests.Envelope_ExactText;
begin
  TAssert.AssertEquals(
    '{"page":2,"limit":10,"total":25,"totalPages":3,"hasNext":true,"hasPrev":true,"items":[1,2]}',
    PageEnvelopeJson(Meta(2, 10, 25), '[1,2]'));
end;

procedure TPaginationTests.Envelope_LastPage;
begin
  TAssert.AssertEquals(
    '{"page":3,"limit":10,"total":25,"totalPages":3,"hasNext":false,"hasPrev":true,"items":[]}',
    PageEnvelopeJson(Meta(3, 10, 25), '[]'));
end;

procedure TPaginationTests.Envelope_Empty_HasOnePage;
begin
  TAssert.AssertEquals(
    '{"page":1,"limit":20,"total":0,"totalPages":1,"hasNext":false,"hasPrev":false,"items":[]}',
    PageEnvelopeJson(Meta(1, 20, 0), '[]'));
end;

procedure TPaginationTests.Envelope_TotalAboveInt32;
begin
  TAssert.AssertEquals(
    '{"page":1,"limit":100,"total":5000000000,"totalPages":50000000,"hasNext":true,"hasPrev":false,"items":[]}',
    PageEnvelopeJson(Meta(1, 100, 5000000000), '[]'));
end;

initialization
  RegisterTest(TPaginationTests);

end.
