unit PascalApi.OrderByTests;

{$mode delphi}{$H+}

{ GENERATED FILE — produced by tools/gen_fpc_mirror.py from
  tests/Unit/PascalApi.OrderByTests.pas (DUnitX). Do not edit by hand: edit the DUnitX
  master and run the script again. }

{ Tests for PascalApi.OrderBy: client expression to ORDER BY fragment, the
  allow-list, the default, the tiebreaker and the documentation hint.

  DUnitX master. The FPCUnit mirror (tests/Unit/fpc) is generated by
  tools/gen_fpc_mirror.py; never edit the mirror by hand. }

interface

uses
  fpcunit, testregistry,
  SysUtils,
  PascalApi.OrderBy;

type
  TOrderByTests = class(TTestCase)
  private
    function Spec: TOrderBySpec;
    function BuildError(const ASpec: TOrderBySpec; const AExpr: string): string;
  published
    procedure Build_Field_Ascending;
    procedure Build_Field_Descending;
    procedure Build_SeveralFields;
    procedure Build_Empty_UsesDefault;
    procedure Build_Blank_UsesDefault;
    procedure Build_FieldNameIgnoresCase;
    procedure Build_SkipsEmptyItemsAndSpaces;
    procedure Build_TiebreakerComesLast;
    procedure Build_DescendingDefault;
    procedure Build_UnknownField_Raises;
    procedure Build_UnknownField_MessageListsAllowedNames;
    procedure Build_SqlInjectionAttempt_Raises;
    procedure Build_NoDefaultNoTiebreaker_Raises;
    procedure Build_OnlyTiebreaker;

    procedure DocHint_ListsAllowedFields;
    procedure DocHint_ShowsDefault;
    procedure DocHint_TiebreakerByClientName;
    procedure DocHint_NeverShowsSqlColumns;
  end;

implementation

// Shared spec: name -> NAME, ibgeCode -> IBGE_CODE, state -> STATE; default
// name; tiebreaker IBGE_CODE ASC.
function TOrderByTests.Spec: TOrderBySpec;
begin
  Result := TOrderBySpec.New
    .Allow('name', 'NAME')
    .Allow('ibgeCode', 'IBGE_CODE')
    .Allow('state', 'STATE')
    .Default('name')
    .AlwaysLast('IBGE_CODE');
end;

// The message of the EOrderByException Build raises, or '' if none.
function TOrderByTests.BuildError(const ASpec: TOrderBySpec; const AExpr: string): string;
begin
  Result := '';
  try
    ASpec.Build(AExpr);
  except
    on E: EOrderByException do
      Result := E.Message;
  end;
end;

procedure TOrderByTests.Build_Field_Ascending;
begin
  TAssert.AssertEquals('NAME ASC, IBGE_CODE ASC', Spec.Build('name'));
end;

procedure TOrderByTests.Build_Field_Descending;
begin
  TAssert.AssertEquals('NAME DESC, IBGE_CODE ASC', Spec.Build('-name'));
end;

procedure TOrderByTests.Build_SeveralFields;
begin
  TAssert.AssertEquals('STATE ASC, NAME DESC, IBGE_CODE ASC', Spec.Build('state,-name'));
end;

procedure TOrderByTests.Build_Empty_UsesDefault;
begin
  TAssert.AssertEquals('NAME ASC, IBGE_CODE ASC', Spec.Build(''));
end;

procedure TOrderByTests.Build_Blank_UsesDefault;
begin
  TAssert.AssertEquals('NAME ASC, IBGE_CODE ASC', Spec.Build('   '));
end;

procedure TOrderByTests.Build_FieldNameIgnoresCase;
begin
  TAssert.AssertEquals('NAME ASC, IBGE_CODE ASC', Spec.Build('NAME'));
  TAssert.AssertEquals('STATE DESC, IBGE_CODE ASC', Spec.Build('-State'));
end;

procedure TOrderByTests.Build_SkipsEmptyItemsAndSpaces;
begin
  TAssert.AssertEquals('STATE ASC, NAME DESC, IBGE_CODE ASC', Spec.Build(' state , ,- name,'));
end;

procedure TOrderByTests.Build_TiebreakerComesLast;
begin
  TAssert.AssertEquals('STATE ASC, IBGE_CODE ASC', Spec.Build('state'));
end;

procedure TOrderByTests.Build_DescendingDefault;
begin
  TAssert.AssertEquals('NAME DESC',
    TOrderBySpec.New.Allow('name', 'NAME').Default('-name').Build(''));
end;

procedure TOrderByTests.Build_UnknownField_Raises;
begin
  TAssert.AssertTrue(BuildError(Spec, 'nope') <> '');
end;

procedure TOrderByTests.Build_UnknownField_MessageListsAllowedNames;
var
  LMessage: string;
begin
  LMessage := BuildError(Spec, 'nope');
  TAssert.AssertTrue('names the field', Pos('"nope"', LMessage) > 0);
  TAssert.AssertTrue('lists name', Pos('name', LMessage) > 0);
  TAssert.AssertTrue('lists ibgeCode', Pos('ibgeCode', LMessage) > 0);
  TAssert.AssertTrue('lists state', Pos('state', LMessage) > 0);
end;

procedure TOrderByTests.Build_SqlInjectionAttempt_Raises;
begin
  TAssert.AssertTrue(BuildError(Spec, 'name; DROP TABLE CITIES') <> '');
end;

procedure TOrderByTests.Build_NoDefaultNoTiebreaker_Raises;
begin
  TAssert.AssertTrue(BuildError(TOrderBySpec.New.Allow('name', 'NAME'), '') <> '');
end;

procedure TOrderByTests.Build_OnlyTiebreaker;
begin
  TAssert.AssertEquals('ID DESC', TOrderBySpec.New.AlwaysLast('ID', odDesc).Build(''));
end;

procedure TOrderByTests.DocHint_ListsAllowedFields;
begin
  TAssert.AssertTrue(Pos('Available fields: name, ibgeCode, state.', Spec.DocHint) > 0);
end;

procedure TOrderByTests.DocHint_ShowsDefault;
begin
  TAssert.AssertTrue(Pos('Default: name.', Spec.DocHint) > 0);
end;

procedure TOrderByTests.DocHint_TiebreakerByClientName;
begin
  TAssert.AssertTrue(Pos('Fixed tiebreaker: ibgeCode ASC.', Spec.DocHint) > 0);
end;

procedure TOrderByTests.DocHint_NeverShowsSqlColumns;
begin
  TAssert.AssertTrue(Pos('IBGE_CODE', Spec.DocHint) = 0);
end;

initialization
  RegisterTest(TOrderByTests);

end.
