unit PascalApi.OpenApiTests;

{$mode delphi}{$H+}

{ GENERATED FILE — produced by tools/gen_fpc_mirror.py from
  tests/Unit/PascalApi.OpenApiTests.pas (DUnitX). Do not edit by hand: edit the DUnitX
  master and run the script again. }

{ Tests for PascalApi.OpenApi: every row of the inference table (plain types,
  enumerations, the optional interfaces, nested DTOs, arrays), the names the
  mapper uses (naming applied), metadata (typed examples, enum, pattern,
  limits), responses (object, array, paged, error, none), path conversion
  and undeclared path parameters, and the errors of TApiSchema.Describe.

  The documents are checked through pascal-jsonmapper-faa's DOM, member by
  member, plus one exact text for the minimal document. Each test uses its
  own TJsonMapper, so nothing leaks into TJsonMapper.Shared.

  DUnitX master. The FPCUnit mirror (tests/Unit/fpc) is generated by
  tools/gen_fpc_mirror.py; never edit the mirror by hand. }

interface

uses
  fpcunit, testregistry,
  SysUtils,
  TypInfo,
  PascalCommon.Optionals,
  PascalJsonMapper.Json,
  PascalJsonMapper.Mapper,
  PascalApi.OpenApi;

type
  TColor = (clRed, clGreen, clBlue);

  IPart = interface
    ['{21EA456A-1F51-4F3D-937D-81BE60505CF3}']
  end;

  IFind = interface
    ['{46B7FB9E-122D-4C82-9C1B-AEE1E1C8104D}']
  end;

  IKitchen = interface
    ['{58BC8241-D29B-430C-B096-882FC6A7723D}']
  end;

{$M+}
  TPart = class(TInterfacedObject, IPart)
  private
    FLabel: string;
  published
    property Label_: string read FLabel write FLabel;
  end;

  TPartArray = array of IPart;

  TFind = class(TInterfacedObject, IFind)
  private
    FPage: IOptInteger;
    FName: IOptString;
    FActive: Boolean;
    FColor: TColor;
    FParts: TPartArray;
  published
    property Page: IOptInteger read FPage write FPage;
    property Name: IOptString read FName write FName;
    property Active: Boolean read FActive write FActive;
    property Color: TColor read FColor write FColor;
    property Parts: TPartArray read FParts write FParts;
  end;
  TTagArray = array of string;

  TKitchen = class(TInterfacedObject, IKitchen)
  private
    FText: string;
    FCount: Integer;
    FBig: Int64;
    FRatio: Double;
    FSmall: Single;
    FPrice: Currency;
    FActive: Boolean;
    FAt: TDateTime;
    FDay: TDate;
    FHour: TTime;
    FColor: TColor;
    FNick: IOptString;
    FAge: INullInteger;
    FScore: IOptNullDouble;
    FPart: IPart;
    FParts: TPartArray;
    FTags: TTagArray;
  published
    property Text: string read FText write FText;
    property Count: Integer read FCount write FCount;
    property Big: Int64 read FBig write FBig;
    property Ratio: Double read FRatio write FRatio;
    property Small: Single read FSmall write FSmall;
    property Price: Currency read FPrice write FPrice;
    property Active: Boolean read FActive write FActive;
    property At: TDateTime read FAt write FAt;
    property Day: TDate read FDay write FDay;
    property Hour: TTime read FHour write FHour;
    property Color: TColor read FColor write FColor;
    property Nick: IOptString read FNick write FNick;
    property Age: INullInteger read FAge write FAge;
    property Score: IOptNullDouble read FScore write FScore;
    property Part: IPart read FPart write FPart;
    property Parts: TPartArray read FParts write FParts;
    property Tags: TTagArray read FTags write FTags;
  end;
{$M-}

  TOpenApiTests = class(TTestCase)
  private
    FMapper: TJsonMapper;
    FDoc: TApiDocument;
    FParsed: TJsonValue;
    function Op(const AMethod, APath: string): TApiOperation;
    procedure AddResponse(AOp: TApiOperation; ACode: Integer; AKind: TApiResponseKind;
      ASchema: PTypeInfo; const ADescription: string = '');
    function Parse: TJsonValue;
    function Node(const APath: array of string): TJsonValue;
    function Prop(const AName: string): TJsonValue;
    function Text(const APath: array of string): string;
    function Has(const APath: array of string): Boolean;
    function Required(const ASchema: string): string;
  protected
    procedure SetUp; override;
    procedure TearDown; override;
  published

    procedure MinimalDocument_ExactText;
    procedure PlainTypes;
    procedure Enumeration_ListsValueNames;
    procedure Optionals_RequiredAndNullable;
    procedure NestedDtoAndArrays;
    procedure NamesFollowTheMapper;
    procedure Metadata_DescriptionExampleLimits;
    procedure Metadata_EnumOverridesTypeEnum;
    procedure Responses_ArrayPagedErrorNone;
    procedure ErrorSchema_OnlyWhenUsed;
    procedure Path_ConvertedAndUndeclaredParamsAdded;
    procedure RequestBody_AndQueryParams;
    procedure QueryDto_ExpandsToQueryParams;
    procedure Describe_UnknownProperty_Raises;
    procedure Describe_UnregisteredInterface_Raises;
    procedure SchemaName_DropsLeadingI;
  end;

implementation

{ TOpenApiTests }

procedure TOpenApiTests.SetUp;
begin
  FMapper := TJsonMapper.Create;
  FMapper.RegisterMapping<IPart, TPart>;
  FMapper.RegisterMapping<IKitchen, TKitchen>;
  FMapper.RegisterMapping<IFind, TFind>;
  FMapper.RenameMember(TPart, 'Label_', 'label');
  FDoc := TApiDocument.Create(FMapper);
  FDoc.Title := 'T';
  FDoc.Version := '1';
  FParsed := nil;
end;

procedure TOpenApiTests.TearDown;
begin
  FreeAndNil(FParsed);
  FreeAndNil(FDoc);
  FreeAndNil(FMapper);
  TApiSchema.Clear;
end;

function TOpenApiTests.Op(const AMethod, APath: string): TApiOperation;
begin
  Result := TApiOperation.Create;
  Result.Method := AMethod;
  Result.Path := APath;
  FDoc.Add(Result);
end;

procedure TOpenApiTests.AddResponse(AOp: TApiOperation; ACode: Integer; AKind: TApiResponseKind;
  ASchema: PTypeInfo; const ADescription: string);
begin
  SetLength(AOp.Responses, Length(AOp.Responses) + 1);
  AOp.Responses[High(AOp.Responses)].Code := ACode;
  AOp.Responses[High(AOp.Responses)].Kind := AKind;
  AOp.Responses[High(AOp.Responses)].Schema := ASchema;
  AOp.Responses[High(AOp.Responses)].Description := ADescription;
end;

function TOpenApiTests.Parse: TJsonValue;
begin
  FreeAndNil(FParsed);
  FParsed := ParseJson(FDoc.ToJson);
  Result := FParsed;
end;

function TOpenApiTests.Node(const APath: array of string): TJsonValue;
var
  I: Integer;
begin
  if FParsed = nil then
    Parse;
  Result := FParsed;
  for I := 0 to High(APath) do
  begin
    if Result = nil then
      Exit;
    if Result.Kind = jkArray then
      Result := Result.Items[StrToInt(APath[I])]
    else
      Result := Result.Find(APath[I]);
  end;
end;

function TOpenApiTests.Prop(const AName: string): TJsonValue;
begin
  Result := Node(['components', 'schemas', 'Kitchen', 'properties', AName]);
end;

function TOpenApiTests.Text(const APath: array of string): string;
var
  LNode: TJsonValue;
begin
  LNode := Node(APath);
  if LNode = nil then
    Result := '<absent>'
  else if LNode.Kind = jkString then
    Result := LNode.AsString
  else
    Result := LNode.ToJson;
end;

function TOpenApiTests.Has(const APath: array of string): Boolean;
begin
  Result := Node(APath) <> nil;
end;

function TOpenApiTests.Required(const ASchema: string): string;
begin
  Result := Text(['components', 'schemas', ASchema, 'required']);
end;

procedure TOpenApiTests.MinimalDocument_ExactText;
begin
  TAssert.AssertEquals('{"openapi":"3.0.3","info":{"title":"T","version":"1"},"paths":{}}',
    FDoc.ToJson);
end;

procedure TOpenApiTests.PlainTypes;
begin
  AddResponse(Op('get', '/k'), 200, rkObject, TypeInfo(IKitchen));
  TAssert.AssertEquals('{"type":"string"}', Prop('text').ToJson);
  TAssert.AssertEquals('{"type":"integer","format":"int32"}', Prop('count').ToJson);
  TAssert.AssertEquals('{"type":"integer","format":"int64"}', Prop('big').ToJson);
  TAssert.AssertEquals('{"type":"number","format":"double"}', Prop('ratio').ToJson);
  TAssert.AssertEquals('{"type":"number","format":"float"}', Prop('small').ToJson);
  TAssert.AssertEquals('{"type":"number"}', Prop('price').ToJson);
  TAssert.AssertEquals('{"type":"boolean"}', Prop('active').ToJson);
  TAssert.AssertEquals('{"type":"string","format":"date-time"}', Prop('at').ToJson);
  TAssert.AssertEquals('{"type":"string","format":"date"}', Prop('day').ToJson);
  TAssert.AssertEquals('{"type":"string","format":"time"}', Prop('hour').ToJson);
end;

procedure TOpenApiTests.Enumeration_ListsValueNames;
begin
  AddResponse(Op('get', '/k'), 200, rkObject, TypeInfo(IKitchen));
  TAssert.AssertEquals('{"type":"string","enum":["clRed","clGreen","clBlue"]}', Prop('color').ToJson);
end;

procedure TOpenApiTests.Optionals_RequiredAndNullable;
begin
  AddResponse(Op('get', '/k'), 200, rkObject, TypeInfo(IKitchen));
  TAssert.AssertEquals('IOptString: base type', '{"type":"string"}', Prop('nick').ToJson);
  TAssert.AssertEquals('INullInteger: nullable',
    '{"type":"integer","format":"int32","nullable":true}', Prop('age').ToJson);
  TAssert.AssertEquals('IOptNullDouble: nullable',
    '{"type":"number","format":"double","nullable":true}', Prop('score').ToJson);
  // Not required: IOptXxx and IOptNullXxx. Required: everything else, INullXxx included.
  TAssert.AssertEquals('["text","count","big","ratio","small","price","active","at","day",' +
    '"hour","color","age","part","parts","tags"]', Required('Kitchen'));
end;

procedure TOpenApiTests.NestedDtoAndArrays;
begin
  AddResponse(Op('get', '/k'), 200, rkObject, TypeInfo(IKitchen));
  TAssert.AssertEquals('{"$ref":"#/components/schemas/Part"}', Prop('part').ToJson);
  TAssert.AssertEquals('{"type":"array","items":{"$ref":"#/components/schemas/Part"}}',
    Prop('parts').ToJson);
  TAssert.AssertEquals('{"type":"array","items":{"type":"string"}}', Prop('tags').ToJson);
  TAssert.AssertTrue('the nested schema is collected', Has(['components', 'schemas', 'Part']));
end;

procedure TOpenApiTests.NamesFollowTheMapper;
begin
  FMapper.Naming := jnSnakeCase;
  AddResponse(Op('get', '/k'), 200, rkObject, TypeInfo(IKitchen));
  // RenameMember beats Naming: 'label', not snake_case's 'label_'.
  TAssert.AssertTrue('the renamed member', Has(['components', 'schemas', 'Part', 'properties', 'label']));
  TAssert.AssertFalse('never the Pascal name', Has(['components', 'schemas', 'Part', 'properties', 'Label_']));
end;

procedure TOpenApiTests.Metadata_DescriptionExampleLimits;
begin
  TApiSchema.Describe(TypeInfo(IKitchen), 'Everything', FMapper)
    .Prop('Text').Desc('Free text').Example('4205407').Pattern('^[0-9]+$').MinLength(1).MaxLength(7)
    .Prop('Count').Example('42').Minimum(0).Maximum(10)
    .Prop('Ratio').Example('0.5')
    .Prop('Active').Example('true')
    .Prop('Age').Desc('Years');
  AddResponse(Op('get', '/k'), 200, rkObject, TypeInfo(IKitchen));
  TAssert.AssertEquals('Everything', Text(['components', 'schemas', 'Kitchen', 'description']));
  TAssert.AssertEquals('a string example stays a string',
    '{"type":"string","description":"Free text","example":"4205407","pattern":"^[0-9]+$",' +
    '"minLength":1,"maxLength":7}', Prop('text').ToJson);
  TAssert.AssertEquals('an integer example is a number',
    '{"type":"integer","format":"int32","example":42,"minimum":0,"maximum":10}', Prop('count').ToJson);
  TAssert.AssertEquals('{"type":"number","format":"double","example":0.5}', Prop('ratio').ToJson);
  TAssert.AssertEquals('{"type":"boolean","example":true}', Prop('active').ToJson);
  TAssert.AssertEquals('{"type":"integer","format":"int32","nullable":true,"description":"Years"}',
    Prop('age').ToJson);
end;

procedure TOpenApiTests.Metadata_EnumOverridesTypeEnum;
begin
  TApiSchema.Describe(TypeInfo(IKitchen), '', FMapper).Prop('Color').Enum(['red', 'green']);
  AddResponse(Op('get', '/k'), 200, rkObject, TypeInfo(IKitchen));
  TAssert.AssertEquals('{"type":"string","enum":["red","green"]}', Prop('color').ToJson);
end;

procedure TOpenApiTests.Responses_ArrayPagedErrorNone;
var
  LOp: TApiOperation;
begin
  LOp := Op('get', '/parts');
  AddResponse(LOp, 200, rkArray, TypeInfo(IPart));
  AddResponse(LOp, 206, rkPaged, TypeInfo(IPart));
  AddResponse(LOp, 404, rkError, nil, 'Gone');
  AddResponse(LOp, 204, rkNone, nil);
  TAssert.AssertEquals('{"type":"array","items":{"$ref":"#/components/schemas/Part"}}',
    Text(['paths', '/parts', 'get', 'responses', '200', 'content', 'application/json', 'schema']));
  TAssert.AssertEquals('{"type":"array","items":{"$ref":"#/components/schemas/Part"}}',
    Text(['paths', '/parts', 'get', 'responses', '206', 'content', 'application/json', 'schema',
      'properties', 'items']));
  TAssert.AssertEquals('["page","limit","total","totalPages","hasNext","hasPrev","items"]',
    Text(['paths', '/parts', 'get', 'responses', '206', 'content', 'application/json', 'schema',
      'required']));
  TAssert.AssertEquals('{"$ref":"#/components/schemas/Error"}',
    Text(['paths', '/parts', 'get', 'responses', '404', 'content', 'application/json', 'schema']));
  TAssert.AssertEquals('Gone', Text(['paths', '/parts', 'get', 'responses', '404', 'description']));
  TAssert.AssertEquals('{"description":"No Content"}',
    Text(['paths', '/parts', 'get', 'responses', '204']));
end;

procedure TOpenApiTests.ErrorSchema_OnlyWhenUsed;
var
  LOp: TApiOperation;
begin
  LOp := Op('get', '/parts');
  AddResponse(LOp, 200, rkArray, TypeInfo(IPart));
  TAssert.AssertFalse(Has(['components', 'schemas', 'Error']));
  AddResponse(LOp, 400, rkError, nil);
  Parse;
  TAssert.AssertEquals('{"type":"object","properties":{"error":{"type":"string"}},"required":["error"]}',
    Text(['components', 'schemas', 'Error']));
end;

procedure TOpenApiTests.Path_ConvertedAndUndeclaredParamsAdded;
var
  LOp: TApiOperation;
begin
  LOp := Op('get', '/cities/:code/parts/:id');
  SetLength(LOp.Params, 1);
  LOp.Params[0].Name := 'id';
  LOp.Params[0].Description := 'Part id';
  LOp.Params[0].Location := plPath;
  LOp.Params[0].ParamType := ptInteger;
  LOp.Params[0].Required := True;
  TAssert.AssertEquals('/cities/{code}/parts/{id}', LOp.OpenApiPath);
  TAssert.AssertEquals(
    '[{"name":"id","in":"path","description":"Part id","required":true,"schema":{"type":"integer"}},' +
    '{"name":"code","in":"path","required":true,"schema":{"type":"string"}}]',
    Text(['paths', '/cities/{code}/parts/{id}', 'get', 'parameters']));
  TAssert.AssertEquals('{"default":{"description":"Response"}}',
    Text(['paths', '/cities/{code}/parts/{id}', 'get', 'responses']));
end;

procedure TOpenApiTests.RequestBody_AndQueryParams;
var
  LOp: TApiOperation;
begin
  LOp := Op('post', '/parts');
  LOp.Body := TypeInfo(IPart);
  LOp.BodyDescription := 'The part';
  LOp.Summary := 'Create';
  SetLength(LOp.Tags, 1);
  LOp.Tags[0] := 'parts';
  SetLength(LOp.Params, 1);
  LOp.Params[0].Name := 'dryRun';
  LOp.Params[0].Location := plQuery;
  LOp.Params[0].ParamType := ptBoolean;
  LOp.Params[0].Required := False;
  TAssert.AssertEquals('{"description":"The part","required":true,"content":{"application/json":' +
    '{"schema":{"$ref":"#/components/schemas/Part"}}}}',
    Text(['paths', '/parts', 'post', 'requestBody']));
  TAssert.AssertEquals('{"name":"dryRun","in":"query","required":false,"schema":{"type":"boolean"}}',
    Text(['paths', '/parts', 'post', 'parameters', '0']));
  TAssert.AssertEquals('["parts"]', Text(['paths', '/parts', 'post', 'tags']));
  TAssert.AssertEquals('Create', Text(['paths', '/parts', 'post', 'summary']));
end;

procedure TOpenApiTests.QueryDto_ExpandsToQueryParams;
var
  LOp: TApiOperation;
begin
  TApiSchema.Describe(TypeInfo(IFind), '', FMapper).Prop('Name').Desc('Part of the name');
  LOp := Op('get', '/finds');
  SetLength(LOp.Params, 1);
  LOp.Params[0].Name := 'extra';
  LOp.Params[0].Location := plQuery;
  LOp.Params[0].ParamType := ptString;
  LOp.Params[0].Required := False;
  LOp.QueryDto := TypeInfo(IFind);
  // Declared parameters first; then one per member: IOptXxx not required,
  // a plain type required, an enumeration a string, the array left out.
  TAssert.AssertEquals(
    '[{"name":"extra","in":"query","required":false,"schema":{"type":"string"}},' +
    '{"name":"page","in":"query","required":false,"schema":{"type":"integer"}},' +
    '{"name":"name","in":"query","description":"Part of the name","required":false,"schema":{"type":"string"}},' +
    '{"name":"active","in":"query","required":true,"schema":{"type":"boolean"}},' +
    '{"name":"color","in":"query","required":true,"schema":{"type":"string"}}]',
    Text(['paths', '/finds', 'get', 'parameters']));
  TAssert.AssertFalse('a query DTO is not a component schema', Has(['components']));
end;

procedure TOpenApiTests.Describe_UnknownProperty_Raises;
var
  LMessage: string;
begin
  LMessage := '';
  try
    TApiSchema.Describe(TypeInfo(IKitchen), '', FMapper).Prop('Txet');
  except
    on E: EApiSchemaError do
      LMessage := E.Message;
  end;
  TAssert.AssertTrue(LMessage, Pos('"Txet"', LMessage) > 0);
end;

procedure TOpenApiTests.Describe_UnregisteredInterface_Raises;
var
  LMessage: string;
  LOther: TJsonMapper;
begin
  LMessage := '';
  LOther := TJsonMapper.Create;
  try
    try
      TApiSchema.Describe(TypeInfo(IKitchen), '', LOther);
    except
      on E: EApiSchemaError do
        LMessage := E.Message;
    end;
  finally
    LOther.Free;
  end;
  TAssert.AssertTrue(LMessage, Pos('RegisterMapping', LMessage) > 0);
end;

procedure TOpenApiTests.SchemaName_DropsLeadingI;
begin
  TAssert.AssertEquals('Kitchen', TApiSchema.SchemaName(TypeInfo(IKitchen)));
  TAssert.AssertEquals('Part', TApiSchema.SchemaName(TypeInfo(IPart)));
end;

initialization
  RegisterTest(TOpenApiTests);

end.
