unit PascalApi.RateLimitStateTests;

{$mode delphi}{$H+}

{ GENERATED FILE — produced by tools/gen_fpc_mirror.py from
  tests/Unit/PascalApi.RateLimitStateTests.pas (DUnitX). Do not edit by hand: edit the DUnitX
  master and run the script again. }

{ Tests for PascalApi.RateLimitState: the sliding window, refused requests
  taking no slot, independent keys, ResetUnix, and the window surviving a
  change of the system time (monotonic ticker vs wall clock).

  Time is a manual clock installed in TClock and TTicker
  (PascalCommon.SystemContext): no real waits. SetTime moves both, like real
  time; ShiftWall moves only the wall clock (daylight saving time, NTP),
  which the monotonic ticker doesn't see.

  Ported from RateLimitTests (delphi-api-infra-faa).

  DUnitX master. The FPCUnit mirror (tests/Unit/fpc) is generated by
  tools/gen_fpc_mirror.py; never edit the mirror by hand. }

interface

uses
  fpcunit, testregistry,
  SysUtils,
  DateUtils,
  PascalCommon.SystemContext,
  PascalApi.RateLimitState;

type
  TManualClock = class(TInterfacedObject, IClock, ITicker)
  private
    FTime: TDateTime;
    FWallShift: TDateTime;
  public
    constructor Create(ATime: TDateTime);
    procedure SetTime(ATime: TDateTime);
    procedure ShiftWall(ADelta: TDateTime);
    function Now: TDateTime;
    function Date: TDateTime;
    function NowMs: UInt64;
  end;

  TRateLimitStateTests = class(TTestCase)
  private
    FState: IRateLimitState;
    FClock: TManualClock;
    FClockRef: IClock;
    FT0: TDateTime;
    procedure FillBucket(const AKey: string; ALimit, AWindowSeconds, ACount: Integer);
  protected
    procedure SetUp; override;
    procedure TearDown; override;
  published

    procedure FirstRequest_NotExceeded;
    procedure FirstRequest_RemainingIsLimitMinusOne;
    procedure AtLimit_LastRequestPasses;
    procedure AtLimit_NextRemainingIsZero;
    procedure OverLimit_Exceeded;
    procedure OverLimit_TakesNoSlot;
    procedure Remaining_DecrementsWithEachRequest;
    procedure AfterWindow_NotExceeded;
    procedure AfterWindow_FullQuotaBack;
    procedure DifferentKeys_AreIndependent;
    procedure ResetUnix_IsOldestEntryPlusWindow;
    procedure ResetUnix_AdvancesWhenOldestExpires;
    procedure LimitOfOne_SecondRequestRefused;
    procedure WallClockMovesBack_DoesNotExtendBlock;
    procedure WallClockMovesForward_DoesNotEndBlockEarly;
  end;

implementation

const
  SECS_PER_DAY = 86400;

{ TManualClock }

constructor TManualClock.Create(ATime: TDateTime);
begin
  inherited Create;
  FTime := ATime;
end;

procedure TManualClock.SetTime(ATime: TDateTime);
begin
  FTime := ATime;
end;

procedure TManualClock.ShiftWall(ADelta: TDateTime);
begin
  FWallShift := FWallShift + ADelta;
end;

function TManualClock.Now: TDateTime;
begin
  Result := FTime + FWallShift;
end;

function TManualClock.Date: TDateTime;
begin
  Result := Trunc(Now);
end;

function TManualClock.NowMs: UInt64;
begin
  Result := UInt64(Round(FTime * MSecsPerDay));
end;

{ TRateLimitStateTests }

procedure TRateLimitStateTests.Setup;
begin
  FT0 := EncodeDate(2025, 1, 1) + EncodeTime(12, 0, 0, 0);
  FClock := TManualClock.Create(FT0);
  FClockRef := FClock; // keeps it alive; TClock and TTicker hold references too
  TClock.SetClock(FClock);
  TTicker.SetTicker(FClock);
  FState := TRateLimitState.Create;
end;

procedure TRateLimitStateTests.TearDown;
begin
  FState := nil;
  TClock.Reset;
  TTicker.Reset;
  FClockRef := nil;
end;

procedure TRateLimitStateTests.FillBucket(const AKey: string;
  ALimit, AWindowSeconds, ACount: Integer);
var
  I, LRem: Integer;
  LReset: Int64;
  LExc: Boolean;
begin
  for I := 1 to ACount do
    FState.CheckAndRecord(AKey, ALimit, AWindowSeconds, LRem, LReset, LExc);
end;

procedure TRateLimitStateTests.FirstRequest_NotExceeded;
var
  LRem: Integer; LReset: Int64; LExc: Boolean;
begin
  FState.CheckAndRecord('ip1', 10, 60, LRem, LReset, LExc);
  TAssert.AssertFalse(LExc);
end;

procedure TRateLimitStateTests.FirstRequest_RemainingIsLimitMinusOne;
var
  LRem: Integer; LReset: Int64; LExc: Boolean;
begin
  FState.CheckAndRecord('ip1', 10, 60, LRem, LReset, LExc);
  TAssert.AssertEquals(9, LRem);
end;

procedure TRateLimitStateTests.AtLimit_LastRequestPasses;
var
  LRem: Integer; LReset: Int64; LExc: Boolean;
begin
  FillBucket('ip1', 10, 60, 9);
  FState.CheckAndRecord('ip1', 10, 60, LRem, LReset, LExc);
  TAssert.AssertFalse('the 10th request (exactly the limit) passes', LExc);
  TAssert.AssertEquals(0, LRem);
end;

procedure TRateLimitStateTests.AtLimit_NextRemainingIsZero;
var
  LRem: Integer; LReset: Int64; LExc: Boolean;
begin
  FillBucket('ip1', 10, 60, 10);
  FState.CheckAndRecord('ip1', 10, 60, LRem, LReset, LExc);
  TAssert.AssertEquals(0, LRem);
end;

procedure TRateLimitStateTests.OverLimit_Exceeded;
var
  LRem: Integer; LReset: Int64; LExc: Boolean;
begin
  FillBucket('ip1', 10, 60, 10);
  FState.CheckAndRecord('ip1', 10, 60, LRem, LReset, LExc);
  TAssert.AssertTrue('the 11th request is refused', LExc);
end;

procedure TRateLimitStateTests.OverLimit_TakesNoSlot;
var
  LRem: Integer; LReset: Int64; LExc: Boolean;
begin
  FillBucket('ip1', 10, 60, 15); // 5 refused
  FClock.SetTime(FT0 + 61 / SECS_PER_DAY);
  FState.CheckAndRecord('ip1', 10, 60, LRem, LReset, LExc);
  TAssert.AssertFalse(LExc);
  TAssert.AssertEquals('refused requests took no slot', 9, LRem);
end;

procedure TRateLimitStateTests.Remaining_DecrementsWithEachRequest;
var
  I, LRem: Integer; LReset: Int64; LExc: Boolean;
begin
  for I := 1 to 5 do
  begin
    FState.CheckAndRecord('ip1', 10, 60, LRem, LReset, LExc);
    TAssert.AssertEquals(Format('after %d requests', [I]), 10 - I, LRem);
  end;
end;

procedure TRateLimitStateTests.AfterWindow_NotExceeded;
var
  LRem: Integer; LReset: Int64; LExc: Boolean;
begin
  FillBucket('ip1', 10, 60, 10);
  FClock.SetTime(FT0 + 61 / SECS_PER_DAY);
  FState.CheckAndRecord('ip1', 10, 60, LRem, LReset, LExc);
  TAssert.AssertFalse(LExc);
end;

procedure TRateLimitStateTests.AfterWindow_FullQuotaBack;
var
  LRem: Integer; LReset: Int64; LExc: Boolean;
begin
  FillBucket('ip1', 10, 60, 10);
  FClock.SetTime(FT0 + 61 / SECS_PER_DAY);
  FState.CheckAndRecord('ip1', 10, 60, LRem, LReset, LExc);
  TAssert.AssertEquals(9, LRem);
end;

procedure TRateLimitStateTests.DifferentKeys_AreIndependent;
var
  LRem: Integer; LReset: Int64; LExc: Boolean;
begin
  FillBucket('ip1', 10, 60, 10);
  FState.CheckAndRecord('ip2', 10, 60, LRem, LReset, LExc);
  TAssert.AssertFalse(LExc);
  TAssert.AssertEquals(9, LRem);
end;

procedure TRateLimitStateTests.ResetUnix_IsOldestEntryPlusWindow;
var
  LRem: Integer; LReset: Int64; LExc: Boolean;
begin
  FState.CheckAndRecord('ip1', 10, 60, LRem, LReset, LExc);
  TAssert.AssertEquals(DateTimeToUnix(FT0 + 60 / SECS_PER_DAY, False), LReset);
end;

procedure TRateLimitStateTests.ResetUnix_AdvancesWhenOldestExpires;
var
  LRem: Integer; LReset, LReset2: Int64; LExc: Boolean;
begin
  FState.CheckAndRecord('ip1', 10, 60, LRem, LReset, LExc);
  FClock.SetTime(FT0 + 10 / SECS_PER_DAY);
  FState.CheckAndRecord('ip1', 10, 60, LRem, LReset2, LExc);
  TAssert.AssertEquals('still the oldest entry', LReset, LReset2);

  FClock.SetTime(FT0 + 61 / SECS_PER_DAY);
  FState.CheckAndRecord('ip1', 10, 60, LRem, LReset2, LExc);
  TAssert.AssertTrue('advances once the oldest entry expires', LReset2 > LReset);
end;

procedure TRateLimitStateTests.LimitOfOne_SecondRequestRefused;
var
  LRem: Integer; LReset: Int64; LExc: Boolean;
begin
  FState.CheckAndRecord('ip1', 1, 60, LRem, LReset, LExc);
  TAssert.AssertFalse(LExc);
  TAssert.AssertEquals(0, LRem);
  FState.CheckAndRecord('ip1', 1, 60, LRem, LReset, LExc);
  TAssert.AssertTrue(LExc);
end;

procedure TRateLimitStateTests.WallClockMovesBack_DoesNotExtendBlock;
var
  LRem: Integer; LReset: Int64; LExc: Boolean;
begin
  // With the window on the wall clock, setting the time back 1h left the 10
  // entries "in the future": the client stayed blocked 1h past the window.
  FillBucket('ip1', 10, 60, 10);
  FClock.ShiftWall(-1 / HoursPerDay);
  FClock.SetTime(FT0 + 61 / SECS_PER_DAY);

  FState.CheckAndRecord('ip1', 10, 60, LRem, LReset, LExc);
  TAssert.AssertFalse('past the window, the time change must not keep the block', LExc);
  TAssert.AssertEquals('full quota back', 9, LRem);
  TAssert.AssertEquals('ResetUnix: wall-clock now (already moved back) + window',
    DateTimeToUnix(FT0 - 1 / HoursPerDay + 121 / SECS_PER_DAY, False), LReset);
end;

procedure TRateLimitStateTests.WallClockMovesForward_DoesNotEndBlockEarly;
var
  LRem: Integer; LReset: Int64; LExc: Boolean;
begin
  // With the window on the wall clock, moving the time 1h forward ended the
  // window at once.
  FillBucket('ip1', 10, 60, 10);
  FClock.ShiftWall(1 / HoursPerDay);
  FClock.SetTime(FT0 + 10 / SECS_PER_DAY);

  FState.CheckAndRecord('ip1', 10, 60, LRem, LReset, LExc);
  TAssert.AssertTrue('moving the time forward must not end the window early', LExc);
  TAssert.AssertEquals('ResetUnix: wall-clock now (already moved forward) + the 50s left',
    DateTimeToUnix(FT0 + 1 / HoursPerDay + 60 / SECS_PER_DAY, False), LReset);
end;

initialization
  RegisterTest(TRateLimitStateTests);

end.
