unit PascalApi.DtoTests;

{$mode delphi}{$H+}

{ GENERATED FILE — produced by tools/gen_fpc_mirror.py from
  tests/Unit/PascalApi.DtoTests.pas (DUnitX). Do not edit by hand: edit the DUnitX
  master and run the script again. }

{ Tests for PascalApi.Dto through pascal-jsonmapper-faa: the base classes'
  published properties reach JSON, are inherited by a concrete DTO, and the
  optional members of a paged search keep "absent" apart from a value. Also
  PascalApi.Messaging's registry.

  The JSON converter for the optional types is pascal-common-faa's bridge
  (PascalCommon.JsonMapper.Optionals), registered when its unit is used.

  DUnitX master. The FPCUnit mirror (tests/Unit/fpc) is generated by
  tools/gen_fpc_mirror.py; never edit the mirror by hand. }

interface

uses
  fpcunit, testregistry,
  SysUtils,
  PascalCommon.Optionals,
  PascalJsonMapper.Mapper,
  PascalCommon.JsonMapper.Optionals,
  PascalDb.Paging,
  PascalApi.Pagination,
  PascalApi.Dto,
  PascalApi.Messaging;

type
  ICityFind = interface(IFindPaginationDTOBase)
    ['{C462411C-51C3-4872-8E57-A9E20211C892}']
    function GetState: IOptString;
  end;

  ICityPage = interface(IResponsePaginationDTOBase)
    ['{71CDDDFD-82C8-41D7-B24E-9E83D2019C5E}']
  end;

{$M+}
  TCityFind = class(TFindPaginationDTOBase, ICityFind)
  private
    FState: IOptString;
  public
    function GetState: IOptString;
  published
    property State: IOptString read FState write FState;
  end;

  TCityPage = class(TResponsePaginationDTOBase, ICityPage)
  end;
{$M-}

  TDtoTests = class(TTestCase)
  published
    procedure Find_FromJson_FillsInheritedMembers;
    procedure Find_AbsentMembers_AreSafeAndEmpty;
    procedure Find_FeedsPageRequest;
    procedure Find_ToJson_OmitsAbsentMembers;
    procedure Page_ToJson_InheritedMembers;
    procedure Page_TotalAboveInt32_RoundTrips;
  end;

  TFakeFactory = class(TInterfacedObject, IMessagingFactory)
  public
    function CreateConsumer(const AConfig: TMessagingConfig): IMessageConsumer;
    function CreatePublisher(const AConfig: TMessagingConfig): IMessagePublisher;
  end;

  TMessagingTests = class(TTestCase)
  published
    procedure Registry_UnknownName_IsNil;
    procedure Registry_ReturnsRegisteredFactory;
    procedure Registry_RegisterAgain_Replaces;
    procedure Config_Defaults;
  end;

implementation

{ TCityFind }

function TCityFind.GetState: IOptString;
begin
  Result := TOptionals.Safe(FState);
end;

{ TDtoTests }

procedure TDtoTests.Find_FromJson_FillsInheritedMembers;
var
  LFind: ICityFind;
begin
  LFind := TJsonMapper.Shared.FromJson<ICityFind>(
    '{"page":2,"limit":15,"orderBy":"-name","search":"São","state":"SP"}');
  TAssert.AssertEquals(2, LFind.Page.Value);
  TAssert.AssertEquals(15, LFind.Limit.Value);
  TAssert.AssertEquals('-name', LFind.OrderBy.Value);
  TAssert.AssertEquals('São', LFind.Search.Value);
  TAssert.AssertEquals('SP', LFind.GetState.Value);
end;

procedure TDtoTests.Find_AbsentMembers_AreSafeAndEmpty;
var
  LFind: ICityFind;
begin
  LFind := TJsonMapper.Shared.FromJson<ICityFind>('{"page":3}');
  TAssert.AssertTrue(LFind.Page.HasValue);
  // Absent members: the getters never return nil (TOptionals.Safe).
  TAssert.AssertTrue('Limit', Assigned(LFind.Limit) and not LFind.Limit.HasValue);
  TAssert.AssertTrue('OrderBy', Assigned(LFind.OrderBy) and not LFind.OrderBy.HasValue);
  TAssert.AssertTrue('Search', Assigned(LFind.Search) and not LFind.Search.HasValue);
  TAssert.AssertTrue('State', Assigned(LFind.GetState) and not LFind.GetState.HasValue);
end;

procedure TDtoTests.Find_FeedsPageRequest;
var
  LFind: ICityFind;
  LPage: TPageRequest;
begin
  LFind := TJsonMapper.Shared.FromJson<ICityFind>('{"page":3}');
  LPage := PageRequestFrom(LFind.Page, LFind.Limit);
  TAssert.AssertEquals(3, LPage.Page);
  TAssert.AssertEquals(PDB_PAGE_DEFAULT_LIMIT, LPage.Limit);
end;

procedure TDtoTests.Find_ToJson_OmitsAbsentMembers;
var
  LFind: ICityFind;
begin
  LFind := TJsonMapper.Shared.FromJson<ICityFind>('{"page":1,"state":"RS"}');
  TAssert.AssertEquals('{"page":1,"state":"RS"}', TJsonMapper.Shared.ToJson<ICityFind>(LFind));
end;

procedure TDtoTests.Page_ToJson_InheritedMembers;
var
  LPage: ICityPage;
begin
  LPage := TCityPage.Create;
  LPage.Page := 2;
  LPage.Limit := 10;
  LPage.Total := 25;
  TAssert.AssertEquals('{"page":2,"limit":10,"total":25}',
    TJsonMapper.Shared.ToJson<ICityPage>(LPage));
end;

procedure TDtoTests.Page_TotalAboveInt32_RoundTrips;
var
  LPage: ICityPage;
begin
  LPage := TJsonMapper.Shared.FromJson<ICityPage>('{"page":1,"limit":100,"total":5000000000}');
  TAssert.AssertEquals(Int64(5000000000), LPage.Total);
end;

{ TFakeFactory }

function TFakeFactory.CreateConsumer(const AConfig: TMessagingConfig): IMessageConsumer;
begin
  Result := nil;
end;

function TFakeFactory.CreatePublisher(const AConfig: TMessagingConfig): IMessagePublisher;
begin
  Result := nil;
end;

{ TMessagingTests }

procedure TMessagingTests.Registry_UnknownName_IsNil;
begin
  TAssert.AssertTrue(TMessagingRegistry.GetFactory('pascalapi-test-unknown') = nil);
end;

procedure TMessagingTests.Registry_ReturnsRegisteredFactory;
var
  LFactory: IMessagingFactory;
begin
  LFactory := TFakeFactory.Create;
  TMessagingRegistry.RegisterFactory('pascalapi-test-a', LFactory);
  TAssert.AssertTrue(TMessagingRegistry.GetFactory('pascalapi-test-a') = LFactory);
end;

procedure TMessagingTests.Registry_RegisterAgain_Replaces;
var
  LFirst, LSecond: IMessagingFactory;
begin
  LFirst := TFakeFactory.Create;
  LSecond := TFakeFactory.Create;
  TMessagingRegistry.RegisterFactory('pascalapi-test-b', LFirst);
  TMessagingRegistry.RegisterFactory('pascalapi-test-b', LSecond);
  TAssert.AssertTrue(TMessagingRegistry.GetFactory('pascalapi-test-b') = LSecond);
end;

procedure TMessagingTests.Config_Defaults;
var
  LConfig: TMessagingConfig;
begin
  LConfig := TMessagingConfig.Create;
  try
    TAssert.AssertEquals('localhost', LConfig.Host);
    TAssert.AssertEquals(5672, LConfig.Port);
    TAssert.AssertEquals('guest', LConfig.User);
    TAssert.AssertEquals('guest', LConfig.Password);
    TAssert.AssertEquals('/', LConfig.VHost);
  finally
    LConfig.Free;
  end;
end;

initialization
  TJsonMapper.Shared.RegisterMapping<ICityFind, TCityFind>;
  TJsonMapper.Shared.RegisterMapping<ICityPage, TCityPage>;
  RegisterTest(TDtoTests);
  RegisterTest(TMessagingTests);

end.
