unit PascalApi.FileLogTests;

{ Tests for PascalApi.FileLog (queue, files per category, line prefix, ids
  shared across categories, bounded queue, rotation, shutdown, the real flush
  thread, concurrency) and TLogTruncate, plus the MD5 and UTF-8 prefix
  helpers of PascalApi.Text it relies on.

  Most tests build the logger with AAutoFlush = False and call FlushNow:
  synchronous, no real waits. Two tests are about the real thread and use
  real time on purpose, with generous limits. Timestamps come from a fixed
  clock installed in TClock, so the rotation archive name is known.

  Ported from Common.FileLogTests (delphi-api-infra-faa), without
  System.RegularExpressions/IOUtils/Diagnostics (Delphi only).

  DUnitX master. The FPCUnit mirror (tests/Unit/fpc) is generated by
  tools/gen_fpc_mirror.py; never edit the mirror by hand. }

interface

uses
  DUnitX.TestFramework,
  PascalApi.DUnitXCompat,
  {$IFNDEF FPC}
  IOUtils,
  {$ENDIF}
  Classes,
  SysUtils,
  PascalCommon.SystemContext,
  PascalCommon.Threading,
  PascalApi.Text,
  PascalApi.FileLog;

type
  TFixedClock = class(TInterfacedObject, IClock)
  private
    FTime: TDateTime;
  public
    constructor Create(ATime: TDateTime);
    function Now: TDateTime;
    function Date: TDateTime;
  end;

  TFileLogStressThread = class(TThread)
  private
    FLogger: IFileLogger;
    FTag, FIterations: Integer;
    FError: string;
  protected
    procedure Execute; override;
  public
    constructor Create(const ALogger: IFileLogger; ATag, AIterations: Integer);
    property Error: string read FError;
  end;

  [TestFixture]
  TFileLogTests = class
  private
    FDir: string;
    function NewLogger(ACapacity: Integer; AMaxFileSize: Int64 = 2 * 1024 * 1024): IFileLogger;
    function ReadLog(const AName: string): string;
    function LogPath(const AName: string): string;
  public
    [Setup] procedure Setup;
    [TearDown] procedure TearDown;

    [Test] procedure Log_Queues;
    [Test] procedure FlushNow_WritesFileAndEmptiesQueue;
    [Test] procedure Categories_GoToSeparateFiles;
    [Test] procedure Line_StartsWithIdAndTimestamp;
    [Test] procedure SeveralCategories_SameLineInEach;
    [Test] procedure SeveralCategories_SameId;
    [Test] procedure DifferentCalls_DifferentIds;
    [Test] procedure FullQueue_DropsOldest;
    [Test] procedure Rotation_BySize;
    [Test] procedure Rotation_SameSecond_KeepsBothArchives;
    [Test] procedure NonAscii_WrittenAsUtf8;
    [Test] procedure Destroy_DrainsQueue;
    [Test] procedure Destroy_WithThread_DoesNotWaitForInterval;
    [Test] procedure RealThread_FlushesByItself;
    [Test] procedure Concurrency_NoLineLost;
  end;

  [TestFixture]
  TLogTruncateTests = class
  public
    [Test] procedure Short_Unchanged;
    [Test] procedure ExactlyAtLimit_Unchanged;
    [Test] procedure Long_CutAndAnnotated;
    [Test] procedure SameContent_SameResult;
    [Test] procedure SamePrefixDifferentTail_DifferentHash;
    [Test] procedure NonAscii_NeverSplitsACharacter;
  end;

  [TestFixture]
  TTextHashTests = class
  public
    [Test] procedure Md5_Rfc1321Vectors;
    [Test] procedure Md5_NonAsciiHashesUtf8Bytes;
    [Test] procedure Utf8Prefix_Ascii;
    [Test] procedure Utf8Prefix_BacksOffToCharacterStart;
  end;

implementation

const
  T0_TEXT = '2025-01-01 12:00:00';

function TempFolder: string;
begin
  {$IFDEF FPC}
  Result := IncludeTrailingPathDelimiter(GetTempDir(False));
  {$ELSE}
  Result := IncludeTrailingPathDelimiter(TPath.GetTempPath);
  {$ENDIF}
end;

procedure DeleteTree(const ADir: string);
var
  LRec: TSearchRec;
  LPath: string;
begin
  if not DirectoryExists(ADir) then
    Exit;
  if FindFirst(IncludeTrailingPathDelimiter(ADir) + '*', faAnyFile, LRec) = 0 then
  try
    repeat
      if (LRec.Name = '.') or (LRec.Name = '..') then
        Continue;
      LPath := IncludeTrailingPathDelimiter(ADir) + LRec.Name;
      if (LRec.Attr and faDirectory) <> 0 then
        DeleteTree(LPath)
      else
        DeleteFile(LPath);
    until FindNext(LRec) <> 0;
  finally
    FindClose(LRec);
  end;
  RemoveDir(ADir);
end;

function ReadText(const APath: string): string;
var
  LStream: TFileStream;
  LBytes: TBytes;
begin
  LStream := TFileStream.Create(APath, fmOpenRead or fmShareDenyNone);
  try
    LBytes := nil;
    SetLength(LBytes, LStream.Size);
    if Length(LBytes) > 0 then
      LStream.ReadBuffer(LBytes[0], Length(LBytes));
  finally
    LStream.Free;
  end;
  Result := PaUtf8BytesToString(LBytes, APath);
end;

function Contains(const AText, APart: string): Boolean;
begin
  Result := Pos(APart, AText) > 0;
end;

// The id of a line: "[" + 8 lower-case hex digits + " ". '' if the line
// doesn't start like that.
function LineId(const ALine: string): string;
var
  I: Integer;
begin
  Result := '';
  if (Length(ALine) < 10) or (ALine[1] <> '[') or (ALine[10] <> ' ') then
    Exit;
  for I := 2 to 9 do
    if not CharInSet(ALine[I], ['0'..'9', 'a'..'f']) then
      Exit;
  Result := Copy(ALine, 2, 8);
end;

function Lines(const AText: string): TStringList;
var
  I: Integer;
begin
  Result := TStringList.Create;
  Result.Text := AText;
  for I := Result.Count - 1 downto 0 do
    if Result[I] = '' then
      Result.Delete(I);
end;

function CountFiles(const ADir, AMask: string): Integer;
var
  LRec: TSearchRec;
begin
  Result := 0;
  if FindFirst(IncludeTrailingPathDelimiter(ADir) + AMask, faAnyFile, LRec) = 0 then
  try
    repeat
      Inc(Result);
    until FindNext(LRec) <> 0;
  finally
    FindClose(LRec);
  end;
end;

{ TFixedClock }

constructor TFixedClock.Create(ATime: TDateTime);
begin
  inherited Create;
  FTime := ATime;
end;

function TFixedClock.Now: TDateTime;
begin
  Result := FTime;
end;

function TFixedClock.Date: TDateTime;
begin
  Result := Trunc(FTime);
end;

{ TFileLogStressThread }

constructor TFileLogStressThread.Create(const ALogger: IFileLogger; ATag, AIterations: Integer);
begin
  inherited Create(True);
  FLogger := ALogger;
  FTag := ATag;
  FIterations := AIterations;
  FreeOnTerminate := False;
end;

procedure TFileLogStressThread.Execute;
var
  I: Integer;
begin
  try
    for I := 1 to FIterations do
      FLogger.Log('app', Format('t%d-i%d', [FTag, I]));
  except
    on E: Exception do
      FError := E.ClassName + ': ' + E.Message;
  end;
  FLogger := nil;
end;

{ TFileLogTests }

procedure TFileLogTests.Setup;
begin
  FDir := TempFolder + 'PascalApiFileLogTests_' + IntToStr(PcTickUs);
  TClock.SetClock(TFixedClock.Create(EncodeDate(2025, 1, 1) + EncodeTime(12, 0, 0, 0)));
end;

procedure TFileLogTests.TearDown;
begin
  TClock.Reset;
  DeleteTree(FDir);
end;

function TFileLogTests.NewLogger(ACapacity: Integer; AMaxFileSize: Int64): IFileLogger;
begin
  Result := TFileLogger.Create(FDir, ACapacity, 999999999, AMaxFileSize, False);
end;

function TFileLogTests.LogPath(const AName: string): string;
begin
  Result := IncludeTrailingPathDelimiter(FDir) + AName;
end;

function TFileLogTests.ReadLog(const AName: string): string;
begin
  Result := ReadText(LogPath(AName));
end;

procedure TFileLogTests.Log_Queues;
var
  LLogger: IFileLogger;
begin
  LLogger := NewLogger(100);
  TAssert.AssertEquals(0, LLogger.PendingCount);
  LLogger.Log('app', 'one');
  LLogger.Log('app', 'two');
  TAssert.AssertEquals(2, LLogger.PendingCount);
  TAssert.AssertFalse('nothing written before a flush', FileExists(LogPath('app.log')));
end;

procedure TFileLogTests.FlushNow_WritesFileAndEmptiesQueue;
var
  LLogger: IFileLogger;
begin
  LLogger := NewLogger(100);
  LLogger.Log('app', 'test message');
  LLogger.FlushNow;
  TAssert.AssertEquals(0, LLogger.PendingCount);
  TAssert.AssertTrue(Contains(ReadLog('app.log'), 'test message'));
end;

procedure TFileLogTests.Categories_GoToSeparateFiles;
var
  LLogger: IFileLogger;
  LPipe, LAmqp: string;
begin
  LLogger := NewLogger(100);
  LLogger.Log('pipe', 'pipe event');
  LLogger.Log('amqp', 'amqp event');
  LLogger.FlushNow;
  LPipe := ReadLog('pipe.log');
  LAmqp := ReadLog('amqp.log');
  TAssert.AssertTrue(Contains(LPipe, 'pipe event'));
  TAssert.AssertFalse(Contains(LPipe, 'amqp event'));
  TAssert.AssertTrue(Contains(LAmqp, 'amqp event'));
  TAssert.AssertFalse(Contains(LAmqp, 'pipe event'));
end;

procedure TFileLogTests.Line_StartsWithIdAndTimestamp;
var
  LLogger: IFileLogger;
  LLine: string;
begin
  LLogger := NewLogger(100);
  LLogger.Log('app', 'prefixed message');
  LLogger.FlushNow;
  LLine := ReadLog('app.log');
  TAssert.AssertTrue('id', LineId(LLine) <> '');
  TAssert.AssertEquals(T0_TEXT + '] prefixed message' + sLineBreak, Copy(LLine, 11, MaxInt));
end;

procedure TFileLogTests.SeveralCategories_SameLineInEach;
var
  LLogger: IFileLogger;
begin
  LLogger := NewLogger(100);
  LLogger.Log(['exception', 'startup'], 'could not connect');
  LLogger.FlushNow;
  TAssert.AssertTrue(Contains(ReadLog('exception.log'), 'could not connect'));
  TAssert.AssertTrue(Contains(ReadLog('startup.log'), 'could not connect'));
end;

procedure TFileLogTests.SeveralCategories_SameId;
var
  LLogger: IFileLogger;
  LId: string;
begin
  LLogger := NewLogger(100);
  LLogger.Log(['exception', 'startup'], 'correlated event');
  LLogger.FlushNow;
  LId := LineId(ReadLog('exception.log'));
  TAssert.AssertTrue(LId <> '');
  TAssert.AssertEquals(LId, LineId(ReadLog('startup.log')));
end;

procedure TFileLogTests.DifferentCalls_DifferentIds;
var
  LLogger: IFileLogger;
  LLines: TStringList;
begin
  LLogger := NewLogger(100);
  LLogger.Log('app', 'first call');
  LLogger.Log('app', 'second call');
  LLogger.FlushNow;
  LLines := Lines(ReadLog('app.log'));
  try
    TAssert.AssertEquals(2, LLines.Count);
    TAssert.AssertTrue(LineId(LLines[0]) <> '');
    TAssert.AssertTrue(LineId(LLines[1]) <> '');
    TAssert.AssertTrue(LineId(LLines[0]) <> LineId(LLines[1]));
  finally
    LLines.Free;
  end;
end;

procedure TFileLogTests.FullQueue_DropsOldest;
var
  LLogger: IFileLogger;
  LContent: string;
  I: Integer;
begin
  LLogger := NewLogger(3);
  for I := 1 to 5 do
    LLogger.Log('app', 'msg' + IntToStr(I));
  TAssert.AssertEquals(3, LLogger.PendingCount);
  LLogger.FlushNow;
  LContent := ReadLog('app.log');
  TAssert.AssertFalse('msg1', Contains(LContent, 'msg1'));
  TAssert.AssertFalse('msg2', Contains(LContent, 'msg2'));
  TAssert.AssertTrue('msg3', Contains(LContent, 'msg3'));
  TAssert.AssertTrue('msg4', Contains(LContent, 'msg4'));
  TAssert.AssertTrue('msg5', Contains(LContent, 'msg5'));
end;

procedure TFileLogTests.Rotation_BySize;
var
  LLogger: IFileLogger;
  LContent: string;
begin
  // A tiny limit: the size is checked BEFORE writing a batch, so the first
  // flush never rotates (no file yet); the second finds the file over the
  // limit and rotates before writing.
  LLogger := NewLogger(100, 10);
  LLogger.Log('rot', 'first message');
  LLogger.FlushNow;
  LLogger.Log('rot', 'second message');
  LLogger.FlushNow;

  LContent := ReadLog('rot.log');
  TAssert.AssertTrue(Contains(LContent, 'second message'));
  TAssert.AssertFalse(Contains(LContent, 'first message'));
  TAssert.AssertEquals(1, CountFiles(FDir, 'rot_*.log'));
  TAssert.AssertTrue(Contains(ReadLog('rot_20250101120000.log'), 'first message'));
end;

procedure TFileLogTests.Rotation_SameSecond_KeepsBothArchives;
var
  LLogger: IFileLogger;
begin
  // The clock is fixed: both rotations happen "in the same second".
  LLogger := NewLogger(100, 10);
  LLogger.Log('rot', 'first');
  LLogger.FlushNow;
  LLogger.Log('rot', 'second');
  LLogger.FlushNow;
  LLogger.Log('rot', 'third');
  LLogger.FlushNow;

  TAssert.AssertTrue(Contains(ReadLog('rot_20250101120000.log'), 'first'));
  TAssert.AssertTrue(Contains(ReadLog('rot_20250101120000_1.log'), 'second'));
  TAssert.AssertTrue(Contains(ReadLog('rot.log'), 'third'));
end;

procedure TFileLogTests.NonAscii_WrittenAsUtf8;
var
  LLogger: IFileLogger;
begin
  LLogger := NewLogger(100);
  LLogger.Log('app', 'São Paulo → ok');
  LLogger.FlushNow;
  TAssert.AssertTrue(Contains(ReadLog('app.log'), '] São Paulo → ok'));
end;

procedure TFileLogTests.Destroy_DrainsQueue;
var
  LLogger: IFileLogger;
begin
  LLogger := NewLogger(100);
  LLogger.Log('app', 'before destroy');
  LLogger := nil; // Destroy drains the queue without an explicit FlushNow
  TAssert.AssertTrue(Contains(ReadLog('app.log'), 'before destroy'));
end;

procedure TFileLogTests.Destroy_WithThread_DoesNotWaitForInterval;
var
  LLogger: IFileLogger;
  LStart: UInt64;
begin
  // A real thread with a huge interval: it would never fire by itself in
  // time. Destroy wakes it through the event instead of waiting.
  LLogger := TFileLogger.Create(FDir, 100, 999999999, 2 * 1024 * 1024, True);
  LLogger.Log('app', 'message');
  LStart := PcTickMs;
  LLogger := nil;
  TAssert.AssertTrue(Format('took %d ms', [PcTickMs - LStart]), PcTickMs - LStart < 2000);
  TAssert.AssertTrue(Contains(ReadLog('app.log'), 'message'));
end;

procedure TFileLogTests.RealThread_FlushesByItself;
var
  LLogger: IFileLogger;
  LStart: UInt64;
  LFound: Boolean;
begin
  // No FlushNow on purpose: the real background thread (short interval)
  // must write by itself.
  LLogger := TFileLogger.Create(FDir, 100, 20, 2 * 1024 * 1024, True);
  LLogger.Log('app', 'written by the thread');
  LFound := False;
  LStart := PcTickMs;
  while (not LFound) and (PcTickMs - LStart < 5000) do
  begin
    Sleep(10);
    LFound := FileExists(LogPath('app.log')) and
      Contains(ReadLog('app.log'), 'written by the thread');
  end;
  LLogger := nil;
  TAssert.AssertTrue('the thread wrote the file within 5 s', LFound);
end;

procedure TFileLogTests.Concurrency_NoLineLost;
const
  THREADS = 10;
  ITERATIONS = 100;
var
  LLogger: IFileLogger;
  LThreads: array[1..THREADS] of TFileLogStressThread;
  LLines: TStringList;
  I: Integer;
begin
  LLogger := NewLogger(THREADS * ITERATIONS + 10);
  for I := 1 to THREADS do
    LThreads[I] := TFileLogStressThread.Create(LLogger, I, ITERATIONS);
  for I := 1 to THREADS do
    LThreads[I].Start;
  for I := 1 to THREADS do
  begin
    LThreads[I].WaitFor;
    TAssert.AssertEquals(Format('thread %d', [I]), '', LThreads[I].Error);
    LThreads[I].Free;
  end;
  TAssert.AssertEquals(THREADS * ITERATIONS, LLogger.PendingCount);
  LLogger.FlushNow;
  LLines := Lines(ReadLog('app.log'));
  try
    TAssert.AssertEquals(THREADS * ITERATIONS, LLines.Count);
  finally
    LLines.Free;
  end;
end;

{ TLogTruncateTests }

procedure TLogTruncateTests.Short_Unchanged;
begin
  TAssert.AssertEquals('short message', TLogTruncate.Apply('short message', 250));
end;

procedure TLogTruncateTests.ExactlyAtLimit_Unchanged;
var
  LContent: string;
begin
  LContent := StringOfChar('x', 250);
  TAssert.AssertEquals(LContent, TLogTruncate.Apply(LContent, 250));
end;

procedure TLogTruncateTests.Long_CutAndAnnotated;
var
  LContent: string;
begin
  LContent := StringOfChar('a', 4832);
  TAssert.AssertEquals(StringOfChar('a', 250) + ' [cut; total_bytes=4832; hash=' +
    Copy(PaMd5Hex(PaStringToUtf8Bytes(LContent)), 1, 8) + ']', TLogTruncate.Apply(LContent, 250));
end;

procedure TLogTruncateTests.SameContent_SameResult;
var
  LContent: string;
begin
  LContent := StringOfChar('b', 1000);
  TAssert.AssertEquals(TLogTruncate.Apply(LContent, 250), TLogTruncate.Apply(LContent, 250));
end;

procedure TLogTruncateTests.SamePrefixDifferentTail_DifferentHash;
begin
  // Same visible prefix and same total size: only the hash can differ, so
  // it covers the whole content, not just the part kept.
  TAssert.AssertTrue(TLogTruncate.Apply(StringOfChar('c', 250) + 'AAAA', 250) <>
    TLogTruncate.Apply(StringOfChar('c', 250) + 'BBBB', 250));
end;

procedure TLogTruncateTests.NonAscii_NeverSplitsACharacter;
begin
  // 'ã' is 2 bytes: a 5-byte limit over 'aaaãb' (6 bytes) keeps 'aaa' and
  // backs off before the 'ã', on both compilers.
  TAssert.AssertTrue(Pos('aaa [cut; total_bytes=6; hash=', TLogTruncate.Apply('aaaãb', 4)) = 1);
  TAssert.AssertTrue(Pos('aaaã [cut; total_bytes=6; hash=', TLogTruncate.Apply('aaaãb', 5)) = 1);
end;

{ TTextHashTests }

procedure TTextHashTests.Md5_Rfc1321Vectors;
begin
  TAssert.AssertEquals('d41d8cd98f00b204e9800998ecf8427e', PaMd5Hex(nil));
  TAssert.AssertEquals('0cc175b9c0f1b6a831c399e269772661', PaMd5Hex(PaStringToUtf8Bytes('a')));
  TAssert.AssertEquals('900150983cd24fb0d6963f7d28e17f72', PaMd5Hex(PaStringToUtf8Bytes('abc')));
  TAssert.AssertEquals('f96b697d7cb7938d525a2f31aaf161d0',
    PaMd5Hex(PaStringToUtf8Bytes('message digest')));
end;

procedure TTextHashTests.Md5_NonAsciiHashesUtf8Bytes;
var
  LBytes: TBytes;
begin
  // 'ã' = C3 A3: hashing the string is hashing those two bytes.
  LBytes := nil;
  SetLength(LBytes, 2);
  LBytes[0] := $C3;
  LBytes[1] := $A3;
  TAssert.AssertEquals(PaMd5Hex(LBytes), PaMd5Hex(PaStringToUtf8Bytes('ã')));
end;

procedure TTextHashTests.Utf8Prefix_Ascii;
begin
  TAssert.AssertEquals('abc', PaUtf8Prefix('abcdef', 3));
  TAssert.AssertEquals('abcdef', PaUtf8Prefix('abcdef', 6));
  TAssert.AssertEquals('', PaUtf8Prefix('abcdef', 0));
end;

procedure TTextHashTests.Utf8Prefix_BacksOffToCharacterStart;
begin
  // '→' is 3 bytes (E2 86 92): any cut inside it drops the whole character.
  TAssert.AssertEquals('a', PaUtf8Prefix('a→b', 1));
  TAssert.AssertEquals('a', PaUtf8Prefix('a→b', 2));
  TAssert.AssertEquals('a', PaUtf8Prefix('a→b', 3));
  TAssert.AssertEquals('a→', PaUtf8Prefix('a→b', 4));
end;

initialization
  TDUnitX.RegisterTestFixture(TFileLogTests);
  TDUnitX.RegisterTestFixture(TLogTruncateTests);
  TDUnitX.RegisterTestFixture(TTextHashTests);

end.
