unit PascalApi.HttpTests;

{ Tests for PascalApi.Http: exception to status/message/log line, the error
  body, CORS headers, the Bearer header, excluded paths (whole segments),
  client IP, the access log line, Retry-After and the replaceable messages.

  DUnitX master. The FPCUnit mirror (tests/Unit/fpc) is generated by
  tools/gen_fpc_mirror.py; never edit the mirror by hand. }

interface

uses
  DUnitX.TestFramework,
  PascalApi.DUnitXCompat,
  SysUtils,
  PascalJsonMapper.Json,
  PascalJsonMapper.Mapper,
  PascalDb.Interfaces,
  PascalApi.OrderBy,
  PascalApi.Text,
  PascalApi.Http;

type
  [TestFixture]
  TErrorMappingTests = class
  private
    function Map(E: Exception): TErrorResponse;
  public
    [TearDown] procedure TearDown;
    [Test] procedure HttpExceptions_KeepStatusAndMessage;
    [Test] procedure NotFound_DefaultMessage;
    [Test] procedure OrderBy_Is400;
    [Test] procedure Encoding_Is400_NotLogged;
    [Test] procedure JsonParseError_Is400;
    [Test] procedure JsonMapperErrorWithPath_Is400;
    [Test] procedure JsonMapperErrorWithoutPath_Is500;
    [Test] procedure ConstraintUniqueAndForeignKey_Are409_NotLogged;
    [Test] procedure ConstraintNotNullAndCheck_Are422_Logged;
    [Test] procedure LockConflict_Is409_Logged;
    [Test] procedure DatabaseUnavailable_Is503_DetailOnlyInLog;
    [Test] procedure Other_Is500_Logged;
    [Test] procedure Messages_CanBeReplaced;
    [Test] procedure ErrorJson_EscapesAndKeepsNonAscii;
  end;

  [TestFixture]
  THttpHelpersTests = class
  private
    function HeaderValue(const AHeaders: TArray<THttpHeader>; const AName: string): string;
  public
    [Test] procedure Cors_AnyOrigin;
    [Test] procedure Cors_ExactOrigin_Matches;
    [Test] procedure Cors_ExactOrigin_OtherOrigin_NoHeaders;
    [Test] procedure Cors_ExactOrigin_NoOrigin_NoHeaders;
    [Test] procedure Cors_OptionalHeaders;
    [Test] procedure Bearer_Results;
    [Test] procedure PathMatches_WholeSegments;
    [Test] procedure PathMatches_TrailingSlashPrefix;
    [Test] procedure PathMatches_IgnoresCase_AndEmpty;
    [Test] procedure ClientIp_Order;
    [Test] procedure RequestId_EightHexDigits_Different;
    [Test] procedure AccessLogLine_Format;
    [Test] procedure RetryAfter_NeverNegative;
  end;

implementation

{ TErrorMappingTests }

function TErrorMappingTests.Map(E: Exception): TErrorResponse;
begin
  try
    Result := MapException(E, 'POST', '/cities');
  finally
    E.Free;
  end;
end;

procedure TErrorMappingTests.TearDown;
begin
  TApiMessages.Current := TApiMessages.English;
end;

procedure TErrorMappingTests.HttpExceptions_KeepStatusAndMessage;
var
  R: TErrorResponse;
begin
  R := Map(EValidationException.Create('name is required'));
  TAssert.AssertEquals(400, R.Status);
  TAssert.AssertEquals('name is required', R.Message);
  TAssert.AssertEquals('', R.LogLine);
  TAssert.AssertEquals(409, Map(EConflictException.Create('x')).Status);
  TAssert.AssertEquals(418, Map(EHttpException.Create(418, 'teapot')).Status);
end;

procedure TErrorMappingTests.NotFound_DefaultMessage;
var
  R: TErrorResponse;
begin
  R := Map(ENotFoundException.Create);
  TAssert.AssertEquals(404, R.Status);
  TAssert.AssertEquals('Resource not found.', R.Message);
  TAssert.AssertEquals('City 7 not found.', Map(ENotFoundException.Create('City 7 not found.')).Message);
end;

procedure TErrorMappingTests.OrderBy_Is400;
var
  R: TErrorResponse;
begin
  R := Map(EOrderByException.Create('Invalid order field: "x"'));
  TAssert.AssertEquals(400, R.Status);
  TAssert.AssertEquals('Invalid order field: "x"', R.Message);
end;

procedure TErrorMappingTests.Encoding_Is400_NotLogged;
var
  R: TErrorResponse;
begin
  R := Map(EEncodingError.Create('No mapping for the Unicode character'));
  TAssert.AssertEquals(400, R.Status);
  TAssert.AssertEquals('The request text is not valid UTF-8.', R.Message);
  TAssert.AssertEquals('', R.LogLine);
  TAssert.AssertEquals(400, Map(ETextEncodingException.Create('x')).Status);
end;

procedure TErrorMappingTests.JsonParseError_Is400;
var
  R: TErrorResponse;
begin
  R := Map(EJsonParseError.CreatePos('Member name expected', 2));
  TAssert.AssertEquals(400, R.Status);
  TAssert.AssertEquals('Invalid request body: Member name expected (at position 2)', R.Message);
  TAssert.AssertEquals('', R.LogLine);
end;

procedure TErrorMappingTests.JsonMapperErrorWithPath_Is400;
var
  R: TErrorResponse;
begin
  R := Map(EJsonMapperError.Create('$.age: expected a number, found JSON string'));
  TAssert.AssertEquals(400, R.Status);
  TAssert.AssertEquals('Invalid request body: $.age: expected a number, found JSON string', R.Message);
end;

procedure TErrorMappingTests.JsonMapperErrorWithoutPath_Is500;
var
  R: TErrorResponse;
begin
  R := Map(EJsonMapperError.Create('Interface ICity has no mapping'));
  TAssert.AssertEquals(500, R.Status);
  TAssert.AssertTrue(R.LogLine <> '');
end;

procedure TErrorMappingTests.ConstraintUniqueAndForeignKey_Are409_NotLogged;
var
  R: TErrorResponse;
begin
  R := Map(EConstraintViolationException.Create(cvUnique, nil));
  TAssert.AssertEquals(409, R.Status);
  TAssert.AssertEquals('A record with these values already exists.', R.Message);
  TAssert.AssertEquals('', R.LogLine);
  R := Map(EConstraintViolationException.Create(cvForeignKey, nil));
  TAssert.AssertEquals(409, R.Status);
  TAssert.AssertEquals('', R.LogLine);
end;

procedure TErrorMappingTests.ConstraintNotNullAndCheck_Are422_Logged;
var
  R: TErrorResponse;
  LDriver: Exception;
begin
  LDriver := Exception.Create('NAME cannot be NULL');
  try
    R := Map(EConstraintViolationException.Create(cvNotNull, LDriver));
  finally
    LDriver.Free;
  end;
  TAssert.AssertEquals(422, R.Status);
  TAssert.AssertEquals('A required field is missing.', R.Message);
  TAssert.AssertTrue('method, path, status', Pos('POST /cities -> 422: EConstraintViolationException',
    R.LogLine) = 1);
  TAssert.AssertTrue('driver detail', Pos('(Exception: NAME cannot be NULL)', R.LogLine) > 0);
  TAssert.AssertEquals(422, Map(EConstraintViolationException.Create(cvCheck, nil)).Status);
end;

procedure TErrorMappingTests.LockConflict_Is409_Logged;
var
  R: TErrorResponse;
begin
  R := Map(ELockConflictException.Create(nil));
  TAssert.AssertEquals(409, R.Status);
  TAssert.AssertEquals('The record is locked or was changed by another operation. Try again.',
    R.Message);
  TAssert.AssertTrue(R.LogLine <> '');
end;

procedure TErrorMappingTests.DatabaseUnavailable_Is503_DetailOnlyInLog;
var
  R: TErrorResponse;
  LDriver: Exception;
begin
  LDriver := Exception.Create('connection refused 10.0.0.5:3050');
  try
    R := Map(EDatabaseUnavailableException.Create(LDriver));
  finally
    LDriver.Free;
  end;
  TAssert.AssertEquals(503, R.Status);
  TAssert.AssertEquals('The database is unavailable. Try again shortly.', R.Message);
  TAssert.AssertTrue('detail in the log', Pos('10.0.0.5', R.LogLine) > 0);
  TAssert.AssertTrue('never in the message', Pos('10.0.0.5', R.Message) = 0);
end;

procedure TErrorMappingTests.Other_Is500_Logged;
var
  R: TErrorResponse;
begin
  R := Map(EAccessViolation.Create('boom'));
  TAssert.AssertEquals(500, R.Status);
  TAssert.AssertEquals('boom', R.Message);
  TAssert.AssertEquals('POST /cities -> 500: EAccessViolation: boom', R.LogLine);
end;

procedure TErrorMappingTests.Messages_CanBeReplaced;
begin
  TApiMessages.Current := TApiMessages.Portuguese;
  TAssert.AssertEquals('Já existe um registro com estes dados.',
    Map(EConstraintViolationException.Create(cvUnique, nil)).Message);
  TAssert.AssertEquals('Recurso não encontrado.', Map(ENotFoundException.Create).Message);
end;

procedure TErrorMappingTests.ErrorJson_EscapesAndKeepsNonAscii;
var
  LParsed: TJsonValue;
begin
  TAssert.AssertEquals('{"error":"não encontrado"}', ErrorJson('não encontrado'));
  LParsed := ParseJson(ErrorJson('say "hi"\ now'#10));
  try
    TAssert.AssertEquals('say "hi"\ now'#10, LParsed.Find('error').AsString);
  finally
    LParsed.Free;
  end;
end;

{ THttpHelpersTests }

function THttpHelpersTests.HeaderValue(const AHeaders: TArray<THttpHeader>;
  const AName: string): string;
var
  I: Integer;
begin
  Result := '<absent>';
  for I := 0 to High(AHeaders) do
    if AHeaders[I].Name = AName then
      Exit(AHeaders[I].Value);
end;

procedure THttpHelpersTests.Cors_AnyOrigin;
var
  H: TArray<THttpHeader>;
begin
  H := CorsHeaders(TCorsOptions.Default, 'https://a.example');
  TAssert.AssertEquals('*', HeaderValue(H, 'Access-Control-Allow-Origin'));
  TAssert.AssertEquals('GET,POST,PUT,PATCH,DELETE,OPTIONS', HeaderValue(H, 'Access-Control-Allow-Methods'));
  TAssert.AssertEquals('Content-Type,Authorization', HeaderValue(H, 'Access-Control-Allow-Headers'));
  TAssert.AssertEquals('86400', HeaderValue(H, 'Access-Control-Max-Age'));
  TAssert.AssertEquals('no Vary with *', '<absent>', HeaderValue(H, 'Vary'));
  TAssert.AssertEquals('<absent>', HeaderValue(H, 'Access-Control-Allow-Credentials'));
  TAssert.AssertEquals('also without Origin', '*',
    HeaderValue(CorsHeaders(TCorsOptions.Default, ''), 'Access-Control-Allow-Origin'));
end;

procedure THttpHelpersTests.Cors_ExactOrigin_Matches;
var
  LOptions: TCorsOptions;
  H: TArray<THttpHeader>;
begin
  LOptions := TCorsOptions.Default;
  LOptions.AllowOrigin := 'https://app.example.com';
  H := CorsHeaders(LOptions, 'https://APP.example.com');
  TAssert.AssertEquals('https://APP.example.com', HeaderValue(H, 'Access-Control-Allow-Origin'));
  TAssert.AssertEquals('Origin', HeaderValue(H, 'Vary'));
end;

procedure THttpHelpersTests.Cors_ExactOrigin_OtherOrigin_NoHeaders;
var
  LOptions: TCorsOptions;
begin
  LOptions := TCorsOptions.Default;
  LOptions.AllowOrigin := 'https://app.example.com';
  TAssert.AssertEquals(0, Length(CorsHeaders(LOptions, 'https://evil.example')));
end;

procedure THttpHelpersTests.Cors_ExactOrigin_NoOrigin_NoHeaders;
var
  LOptions: TCorsOptions;
begin
  LOptions := TCorsOptions.Default;
  LOptions.AllowOrigin := 'https://app.example.com';
  TAssert.AssertEquals(0, Length(CorsHeaders(LOptions, '')));
end;

procedure THttpHelpersTests.Cors_OptionalHeaders;
var
  LOptions: TCorsOptions;
  H: TArray<THttpHeader>;
begin
  LOptions := TCorsOptions.Default;
  LOptions.AllowOrigin := 'https://app.example.com';
  LOptions.AllowCredentials := True;
  LOptions.ExposeHeaders := 'X-Total-Count';
  LOptions.MaxAge := 0;
  H := CorsHeaders(LOptions, 'https://app.example.com');
  TAssert.AssertEquals('true', HeaderValue(H, 'Access-Control-Allow-Credentials'));
  TAssert.AssertEquals('X-Total-Count', HeaderValue(H, 'Access-Control-Expose-Headers'));
  TAssert.AssertEquals('<absent>', HeaderValue(H, 'Access-Control-Max-Age'));
end;

procedure THttpHelpersTests.Bearer_Results;
var
  LToken: string;
begin
  TAssert.AssertTrue('ok', ParseBearer('Bearer abc.def', LToken) = brOk);
  TAssert.AssertEquals('abc.def', LToken);
  TAssert.AssertTrue('scheme case', ParseBearer('bearer   xyz  ', LToken) = brOk);
  TAssert.AssertEquals('xyz', LToken);
  TAssert.AssertTrue('missing', ParseBearer('', LToken) = brMissing);
  TAssert.AssertTrue('basic', ParseBearer('Basic dXNlcjpwYXNz', LToken) = brNotBearer);
  TAssert.AssertTrue('no space', ParseBearer('Bearerabc', LToken) = brNotBearer);
  TAssert.AssertTrue('empty token', ParseBearer('Bearer    ', LToken) = brEmpty);
end;

procedure THttpHelpersTests.PathMatches_WholeSegments;
begin
  TAssert.AssertTrue('equal', PathMatchesAny('/auth/login', ['/health', '/auth/login']));
  TAssert.AssertTrue('below', PathMatchesAny('/swagger/index.html', ['/swagger']));
  TAssert.AssertFalse('sibling with longer name', PathMatchesAny('/auth/login-admin', ['/auth/login']));
  TAssert.AssertFalse('healthz', PathMatchesAny('/healthz', ['/health']));
  TAssert.AssertFalse('other', PathMatchesAny('/cities', ['/health', '/swagger']));
end;

procedure THttpHelpersTests.PathMatches_TrailingSlashPrefix;
begin
  TAssert.AssertTrue(PathMatchesAny('/public/x', ['/public/']));
  TAssert.AssertFalse(PathMatchesAny('/public', ['/public/']));
end;

procedure THttpHelpersTests.PathMatches_IgnoresCase_AndEmpty;
begin
  TAssert.AssertTrue(PathMatchesAny('/Health', ['/health']));
  TAssert.AssertFalse('an empty prefix matches nothing', PathMatchesAny('/cities', ['']));
  TAssert.AssertFalse('no prefixes', PathMatchesAny('/cities', []));
end;

procedure THttpHelpersTests.ClientIp_Order;
begin
  TAssert.AssertEquals('203.0.113.7', ClientIp('203.0.113.7, 10.0.0.1', '10.0.0.2', '-'));
  TAssert.AssertEquals('203.0.113.7', ClientIp(' 203.0.113.7 ', '10.0.0.2', '-'));
  TAssert.AssertEquals('10.0.0.2', ClientIp('', '10.0.0.2', '-'));
  TAssert.AssertEquals('unknown', ClientIp('', '', 'unknown'));
end;

procedure THttpHelpersTests.RequestId_EightHexDigits_Different;
var
  A, B: string;
  I: Integer;
begin
  A := NewRequestId;
  B := NewRequestId;
  TAssert.AssertEquals(8, Length(A));
  for I := 1 to 8 do
    TAssert.AssertTrue(CharInSet(A[I], ['0'..'9', 'a'..'f']));
  TAssert.AssertTrue(A <> B);
end;

procedure THttpHelpersTests.AccessLogLine_Format;
begin
  TAssert.AssertEquals(
    '[2025-01-01 12:00:05] GET /cities 200 12ms 10.0.0.2 512 "page=2" "curl/8.0" 1a2b3c4d',
    AccessLogLine(EncodeDate(2025, 1, 1) + EncodeTime(12, 0, 5, 0), 'GET', '/cities', 200, 12,
      '10.0.0.2', '512', 'page=2', 'curl/8.0', '1a2b3c4d'));
  TAssert.AssertEquals('[2025-01-01 00:00:00] POST /x 500 0ms - - "-" "-" id',
    AccessLogLine(EncodeDate(2025, 1, 1), 'POST', '/x', 500, 0, '', '', '', '', 'id'));
end;

procedure THttpHelpersTests.RetryAfter_NeverNegative;
begin
  TAssert.AssertEquals(Int64(30), RetryAfterSeconds(1030, 1000));
  TAssert.AssertEquals(Int64(0), RetryAfterSeconds(1000, 1005));
end;

initialization
  TDUnitX.RegisterTestFixture(TErrorMappingTests);
  TDUnitX.RegisterTestFixture(THttpHelpersTests);

end.
