unit PascalApi.VersionTests;

{ Tests for PascalApi.Version: the version constants agree with each other,
  so a release that bumps one and forgets another fails here.

  DUnitX master. The FPCUnit mirror (tests/Unit/fpc) is generated by
  tools/gen_fpc_mirror.py; never edit the mirror by hand. }

interface

uses
  DUnitX.TestFramework,
  PascalApi.DUnitXCompat,
  SysUtils,
  PascalApi.Version;

type
  [TestFixture]
  TVersionTests = class
  public
    [Test] procedure Number_MatchesTheParts;
    [Test] procedure Text_MatchesTheParts;
  end;

implementation

procedure TVersionTests.Number_MatchesTheParts;
begin
  TAssert.AssertEquals(PASCALAPI_VERSION_MAJOR * 10000 + PASCALAPI_VERSION_MINOR * 100 +
    PASCALAPI_VERSION_PATCH, PASCALAPI_VERSION);
end;

procedure TVersionTests.Text_MatchesTheParts;
begin
  TAssert.AssertEquals(Format('%d.%d.%d', [PASCALAPI_VERSION_MAJOR, PASCALAPI_VERSION_MINOR,
    PASCALAPI_VERSION_PATCH]), PASCALAPI_VERSION_STRING);
end;

initialization
  TDUnitX.RegisterTestFixture(TVersionTests);

end.
