unit PascalApi.OtlpTests;

{ Tests for PascalApi.Otlp: the OTLP/HTTP JSON body of a batch of spans,
  byte for byte (ids as hex, enums as numbers, 64-bit integers as strings,
  typed attribute values), the resource attributes and the traces endpoint.
  The body is also checked by a real OpenTelemetry Collector in CI
  (tools/test_http_docker.sh).

  DUnitX master. The FPCUnit mirror (tests/Unit/fpc) is generated by
  tools/gen_fpc_mirror.py; never edit the mirror by hand. }

interface

uses
  DUnitX.TestFramework,
  PascalApi.DUnitXCompat,
  SysUtils,
  PascalApi.Http,
  PascalApi.Tracing,
  PascalApi.Otlp,
  PascalApi.Version;

type
  [TestFixture]
  TOtlpTests = class
  public
    [Test] procedure TracesJson_FullSpan;
    [Test] procedure TracesJson_RootSpan_NoParentNoMessage;
    [Test] procedure Resource_ExtraAttributesAddAndReplace;
    [Test] procedure Endpoint_TracesThenBaseThenDefault;
  end;

implementation

function Attr(const AKey: string; AType: TSpanAttributeType): TSpanAttribute;
begin
  Result.Key := AKey;
  Result.ValueType := AType;
  Result.StringValue := '';
  Result.IntValue := 0;
  Result.DoubleValue := 0;
  Result.BoolValue := False;
end;

function SampleSpan: TSpanData;
begin
  Result.TraceId := '4bf92f3577b34da6a3ce929d0e0e4736';
  Result.SpanId := 'b7ad6b7169203331';
  Result.ParentSpanId := '00f067aa0ba902b7';
  Result.TraceState := 'vendor=1';
  Result.Name := 'GET /cities/:id';
  Result.Kind := skServer;
  Result.StartUnixNano := 1767323045678000000;
  Result.EndUnixNano := 1767323045680500000;
  Result.Attributes := nil;
  SetLength(Result.Attributes, 4);
  Result.Attributes[0] := Attr('http.route', satString);
  Result.Attributes[0].StringValue := '/cities/:id';
  Result.Attributes[1] := Attr('http.response.status_code', satInt);
  Result.Attributes[1].IntValue := 500;
  Result.Attributes[2] := Attr('ratio', satDouble);
  Result.Attributes[2].DoubleValue := 0.5;
  Result.Attributes[3] := Attr('cached', satBool);
  Result.Attributes[3].BoolValue := True;
  Result.Status := ssError;
  Result.StatusMessage := 'say "no"';
end;

function Resource(const AExtra: string): string;
begin
  Result := '"resource":{"attributes":[' +
    '{"key":"service.name","value":{"stringValue":"svc"}},' +
    '{"key":"service.version","value":{"stringValue":"1.2.3"}},' +
    '{"key":"telemetry.sdk.name","value":{"stringValue":"pascal-api-infra-faa"}},' +
    '{"key":"telemetry.sdk.version","value":{"stringValue":"' + PASCALAPI_VERSION_STRING + '"}}' +
    AExtra + ']}';
end;

function Scope: string;
begin
  Result := '"scope":{"name":"pascal-api-infra-faa","version":"' + PASCALAPI_VERSION_STRING + '"}';
end;

procedure TOtlpTests.TracesJson_FullSpan;
var
  LSpans: TSpanDataArray;
begin
  LSpans := nil;
  SetLength(LSpans, 1);
  LSpans[0] := SampleSpan;
  TAssert.AssertEquals('{"resourceSpans":[{' + Resource('') + ',"scopeSpans":[{' + Scope +
    ',"spans":[{"traceId":"4bf92f3577b34da6a3ce929d0e0e4736","spanId":"b7ad6b7169203331",' +
    '"traceState":"vendor=1","parentSpanId":"00f067aa0ba902b7","name":"GET /cities/:id",' +
    '"kind":2,"startTimeUnixNano":"1767323045678000000","endTimeUnixNano":"1767323045680500000",' +
    '"attributes":[' +
    '{"key":"http.route","value":{"stringValue":"/cities/:id"}},' +
    '{"key":"http.response.status_code","value":{"intValue":"500"}},' +
    '{"key":"ratio","value":{"doubleValue":0.5}},' +
    '{"key":"cached","value":{"boolValue":true}}],' +
    '"status":{"message":"say \"no\"","code":2}}]}]}]}',
    OtlpTracesJson(TTracingOptions.Default('svc', '1.2.3'), LSpans));
end;

procedure TOtlpTests.TracesJson_RootSpan_NoParentNoMessage;
var
  LSpans: TSpanDataArray;
begin
  LSpans := nil;
  SetLength(LSpans, 1);
  LSpans[0] := SampleSpan;
  LSpans[0].ParentSpanId := '';
  LSpans[0].TraceState := '';
  LSpans[0].Kind := skClient;
  LSpans[0].Attributes := nil;
  LSpans[0].Status := ssUnset;
  LSpans[0].StatusMessage := '';
  TAssert.AssertEquals('{"resourceSpans":[{' + Resource('') + ',"scopeSpans":[{' + Scope +
    ',"spans":[{"traceId":"4bf92f3577b34da6a3ce929d0e0e4736","spanId":"b7ad6b7169203331",' +
    '"name":"GET /cities/:id","kind":3,"startTimeUnixNano":"1767323045678000000",' +
    '"endTimeUnixNano":"1767323045680500000","attributes":[],"status":{"code":0}}]}]}]}',
    OtlpTracesJson(TTracingOptions.Default('svc', '1.2.3'), LSpans));
end;

procedure TOtlpTests.Resource_ExtraAttributesAddAndReplace;
var
  O: TTracingOptions;
  L: TArray<THttpHeader>;
begin
  O := TTracingOptions.Default('svc', '1.2.3');
  O.ResourceAttributes := 'deployment.environment=test, service.name=other';
  L := OtlpResourceAttributes(O);
  TAssert.AssertEquals(5, Length(L));
  TAssert.AssertEquals('service.name', L[0].Name);
  TAssert.AssertEquals('other', L[0].Value);
  TAssert.AssertEquals('deployment.environment', L[4].Name);
  TAssert.AssertEquals('test', L[4].Value);
  O := TTracingOptions.Default('svc', '');
  TAssert.AssertEquals(3, Length(OtlpResourceAttributes(O)));
end;

procedure TOtlpTests.Endpoint_TracesThenBaseThenDefault;
begin
  TAssert.AssertEquals('http://c:4318/custom', OtlpTracesEndpoint(' http://c:4318/custom ', 'http://b:4318'));
  TAssert.AssertEquals('http://b:4318/v1/traces', OtlpTracesEndpoint('', 'http://b:4318/'));
  TAssert.AssertEquals('http://localhost:4318/v1/traces', OtlpTracesEndpoint('', ''));
end;

initialization
  TDUnitX.RegisterTestFixture(TOtlpTests);

end.
