unit PascalApi.OrderByTests;

{ Tests for PascalApi.OrderBy: client expression to ORDER BY fragment, the
  allow-list, the default, the tiebreaker and the documentation hint.

  DUnitX master. The FPCUnit mirror (tests/Unit/fpc) is generated by
  tools/gen_fpc_mirror.py; never edit the mirror by hand. }

interface

uses
  DUnitX.TestFramework,
  PascalApi.DUnitXCompat,
  SysUtils,
  PascalApi.OrderBy;

type
  [TestFixture]
  TOrderByTests = class
  private
    function Spec: TOrderBySpec;
    function BuildError(const ASpec: TOrderBySpec; const AExpr: string): string;
  public
    [Test] procedure Build_Field_Ascending;
    [Test] procedure Build_Field_Descending;
    [Test] procedure Build_SeveralFields;
    [Test] procedure Build_Empty_UsesDefault;
    [Test] procedure Build_Blank_UsesDefault;
    [Test] procedure Build_FieldNameIgnoresCase;
    [Test] procedure Build_SkipsEmptyItemsAndSpaces;
    [Test] procedure Build_TiebreakerComesLast;
    [Test] procedure Build_DescendingDefault;
    [Test] procedure Build_UnknownField_Raises;
    [Test] procedure Build_UnknownField_MessageListsAllowedNames;
    [Test] procedure Build_SqlInjectionAttempt_Raises;
    [Test] procedure Build_NoDefaultNoTiebreaker_Raises;
    [Test] procedure Build_OnlyTiebreaker;

    [Test] procedure DocHint_ListsAllowedFields;
    [Test] procedure DocHint_ShowsDefault;
    [Test] procedure DocHint_TiebreakerByClientName;
    [Test] procedure DocHint_NeverShowsSqlColumns;
    [Test] procedure DocHint_TiebreakerNotAllowed_IsLeftOut;
  end;

implementation

// Shared spec: name -> NAME, ibgeCode -> IBGE_CODE, state -> STATE; default
// name; tiebreaker IBGE_CODE ASC.
function TOrderByTests.Spec: TOrderBySpec;
begin
  Result := TOrderBySpec.New
    .Allow('name', 'NAME')
    .Allow('ibgeCode', 'IBGE_CODE')
    .Allow('state', 'STATE')
    .Default('name')
    .AlwaysLast('IBGE_CODE');
end;

// The message of the EOrderByException Build raises, or '' if none.
function TOrderByTests.BuildError(const ASpec: TOrderBySpec; const AExpr: string): string;
begin
  Result := '';
  try
    ASpec.Build(AExpr);
  except
    on E: EOrderByException do
      Result := E.Message;
  end;
end;

procedure TOrderByTests.Build_Field_Ascending;
begin
  TAssert.AssertEquals('NAME ASC, IBGE_CODE ASC', Spec.Build('name'));
end;

procedure TOrderByTests.Build_Field_Descending;
begin
  TAssert.AssertEquals('NAME DESC, IBGE_CODE ASC', Spec.Build('-name'));
end;

procedure TOrderByTests.Build_SeveralFields;
begin
  TAssert.AssertEquals('STATE ASC, NAME DESC, IBGE_CODE ASC', Spec.Build('state,-name'));
end;

procedure TOrderByTests.Build_Empty_UsesDefault;
begin
  TAssert.AssertEquals('NAME ASC, IBGE_CODE ASC', Spec.Build(''));
end;

procedure TOrderByTests.Build_Blank_UsesDefault;
begin
  TAssert.AssertEquals('NAME ASC, IBGE_CODE ASC', Spec.Build('   '));
end;

procedure TOrderByTests.Build_FieldNameIgnoresCase;
begin
  TAssert.AssertEquals('NAME ASC, IBGE_CODE ASC', Spec.Build('NAME'));
  TAssert.AssertEquals('STATE DESC, IBGE_CODE ASC', Spec.Build('-State'));
end;

procedure TOrderByTests.Build_SkipsEmptyItemsAndSpaces;
begin
  TAssert.AssertEquals('STATE ASC, NAME DESC, IBGE_CODE ASC', Spec.Build(' state , ,- name,'));
end;

procedure TOrderByTests.Build_TiebreakerComesLast;
begin
  TAssert.AssertEquals('STATE ASC, IBGE_CODE ASC', Spec.Build('state'));
end;

procedure TOrderByTests.Build_DescendingDefault;
begin
  TAssert.AssertEquals('NAME DESC',
    TOrderBySpec.New.Allow('name', 'NAME').Default('-name').Build(''));
end;

procedure TOrderByTests.Build_UnknownField_Raises;
begin
  TAssert.AssertTrue(BuildError(Spec, 'nope') <> '');
end;

procedure TOrderByTests.Build_UnknownField_MessageListsAllowedNames;
var
  LMessage: string;
begin
  LMessage := BuildError(Spec, 'nope');
  TAssert.AssertTrue('names the field', Pos('"nope"', LMessage) > 0);
  TAssert.AssertTrue('lists name', Pos('name', LMessage) > 0);
  TAssert.AssertTrue('lists ibgeCode', Pos('ibgeCode', LMessage) > 0);
  TAssert.AssertTrue('lists state', Pos('state', LMessage) > 0);
end;

procedure TOrderByTests.Build_SqlInjectionAttempt_Raises;
begin
  TAssert.AssertTrue(BuildError(Spec, 'name; DROP TABLE CITIES') <> '');
end;

procedure TOrderByTests.Build_NoDefaultNoTiebreaker_Raises;
begin
  TAssert.AssertTrue(BuildError(TOrderBySpec.New.Allow('name', 'NAME'), '') <> '');
end;

procedure TOrderByTests.Build_OnlyTiebreaker;
begin
  TAssert.AssertEquals('ID DESC', TOrderBySpec.New.AlwaysLast('ID', odDesc).Build(''));
end;

procedure TOrderByTests.DocHint_ListsAllowedFields;
begin
  TAssert.AssertTrue(Pos('Available fields: name, ibgeCode, state.', Spec.DocHint) > 0);
end;

procedure TOrderByTests.DocHint_ShowsDefault;
begin
  TAssert.AssertTrue(Pos('Default: name.', Spec.DocHint) > 0);
end;

procedure TOrderByTests.DocHint_TiebreakerByClientName;
begin
  TAssert.AssertTrue(Pos('Fixed tiebreaker: ibgeCode ASC.', Spec.DocHint) > 0);
end;

procedure TOrderByTests.DocHint_NeverShowsSqlColumns;
begin
  TAssert.AssertTrue(Pos('IBGE_CODE', Spec.DocHint) = 0);
end;

procedure TOrderByTests.DocHint_TiebreakerNotAllowed_IsLeftOut;
var
  LHint: string;
begin
  // CODE is a tiebreaker but not a field the client may use: its SQL must
  // not appear in the documentation.
  LHint := TOrderBySpec.New.Allow('name', 'NAME').Default('name').AlwaysLast('CODE').DocHint;
  TAssert.AssertTrue('no SQL column', Pos('CODE', LHint) = 0);
  TAssert.AssertTrue('no tiebreaker sentence', Pos('tiebreaker', LHint) = 0);
  TAssert.AssertTrue('still lists the fields', Pos('Available fields: name.', LHint) = 1);
end;

initialization
  TDUnitX.RegisterTestFixture(TOrderByTests);

end.
