unit PascalApi.ConfigTests;

{ Tests for PascalApi.Config (environment, then .env, then default) and for
  the UTF-8 helpers it reads the file with (PascalApi.Text).

  The environment is replaced through SetEnvironmentReader with a fake backed
  by a string list, not changed for real: FPC on Unix doesn't see a setenv
  made after startup. One test reads a variable that every OS sets, to cover
  the real reader too.

  DUnitX master. The FPCUnit mirror (tests/Unit/fpc) is generated by
  tools/gen_fpc_mirror.py; never edit the mirror by hand. }

interface

uses
  DUnitX.TestFramework,
  PascalApi.DUnitXCompat,
  {$IFNDEF FPC}
  IOUtils,
  {$ENDIF}
  Classes,
  SysUtils,
  PascalApi.Text,
  PascalApi.Config;

type
  [TestFixture]
  TAppConfigTests = class
  private
    FSavedEnvPath: string;
    FTempEnv: string;
    procedure WriteEnvFile(const AContent: string);
  public
    [Setup] procedure Setup;
    [TearDown] procedure TearDown;

    [Test] procedure Get_NoEnvironmentNoFile_ReturnsDefault;
    [Test] procedure Get_NoDefaultNoSource_ReturnsEmpty;
    [Test] procedure Get_NotInEnvironment_ReadsFile;
    [Test] procedure Get_EnvironmentWinsOverFile;
    [Test] procedure Get_SkipsCommentsAndBlankLines;
    [Test] procedure Get_RemovesDoubleAndSingleQuotes;
    [Test] procedure Get_FileKeyIgnoresCase;
    [Test] procedure Get_ValueMayContainEqualsSign;
    [Test] procedure Get_FileWithBomAndNonAscii;
    [Test] procedure Get_FileWithCrLf;
    [Test] procedure Get_RealEnvironmentReader_SeesPath;

    [Test] procedure GetInt_ParsesNumber;
    [Test] procedure GetInt_NotNumeric_ReturnsDefault;
    [Test] procedure GetInt_Absent_ReturnsDefault;

    [Test] procedure GetBool_TrueOneYes_AreTrue;
    [Test] procedure GetBool_OtherValue_IsFalse;
    [Test] procedure GetBool_Absent_ReturnsDefault;
  end;

  [TestFixture]
  TTextTests = class
  public
    [Test] procedure RoundTrip_NonAscii;
    [Test] procedure Decode_SkipsBom;
    [Test] procedure Decode_Empty;
    [Test] procedure Encode_IsUtf8Bytes;
  end;

implementation

const
  KEY_A = 'PASCALAPI_TEST_KEY_A';
  KEY_B = 'PASCALAPI_TEST_KEY_B';

var
  GFakeEnv: TStringList;

function FakeEnvironment(const AName: string): string;
begin
  Result := GFakeEnv.Values[AName];
end;

function TempFolder: string;
begin
  {$IFDEF FPC}
  Result := IncludeTrailingPathDelimiter(GetTempDir(False));
  {$ELSE}
  Result := IncludeTrailingPathDelimiter(TPath.GetTempPath);
  {$ENDIF}
end;

procedure WriteBytes(const APath: string; const ABytes: TBytes);
var
  LStream: TFileStream;
begin
  LStream := TFileStream.Create(APath, fmCreate);
  try
    if Length(ABytes) > 0 then
      LStream.WriteBuffer(ABytes[0], Length(ABytes));
  finally
    LStream.Free;
  end;
end;

{ TAppConfigTests }

procedure TAppConfigTests.Setup;
begin
  FSavedEnvPath := TAppConfig.EnvFilePath;
  FTempEnv := TempFolder + 'pascalapi_config_test.env';
  TAppConfig.SetEnvFile(FTempEnv);
  GFakeEnv := TStringList.Create;
  TAppConfig.SetEnvironmentReader(FakeEnvironment);
end;

procedure TAppConfigTests.TearDown;
begin
  TAppConfig.SetEnvironmentReader(nil);
  TAppConfig.SetEnvFile(FSavedEnvPath);
  FreeAndNil(GFakeEnv);
  if FileExists(FTempEnv) then
    DeleteFile(FTempEnv);
end;

procedure TAppConfigTests.WriteEnvFile(const AContent: string);
begin
  WriteBytes(FTempEnv, PaStringToUtf8Bytes(AContent));
end;

procedure TAppConfigTests.Get_NoEnvironmentNoFile_ReturnsDefault;
begin
  TAssert.AssertEquals('fallback', TAppConfig.Get(KEY_A, 'fallback'));
end;

procedure TAppConfigTests.Get_NoDefaultNoSource_ReturnsEmpty;
begin
  TAssert.AssertEquals('', TAppConfig.Get(KEY_A));
end;

procedure TAppConfigTests.Get_NotInEnvironment_ReadsFile;
begin
  WriteEnvFile(KEY_A + '=from_file');
  TAssert.AssertEquals('from_file', TAppConfig.Get(KEY_A));
end;

procedure TAppConfigTests.Get_EnvironmentWinsOverFile;
begin
  WriteEnvFile(KEY_A + '=from_file');
  GFakeEnv.Values[KEY_A] := 'from_env';
  TAssert.AssertEquals('from_env', TAppConfig.Get(KEY_A));
end;

procedure TAppConfigTests.Get_SkipsCommentsAndBlankLines;
begin
  WriteEnvFile('# comment' + #10 + #10 + '   ' + #10 + KEY_A + '=ok');
  TAssert.AssertEquals('ok', TAppConfig.Get(KEY_A));
end;

procedure TAppConfigTests.Get_RemovesDoubleAndSingleQuotes;
begin
  WriteEnvFile(KEY_A + '="quoted value"' + #10 + KEY_B + '=''single''');
  TAssert.AssertEquals('quoted value', TAppConfig.Get(KEY_A));
  TAssert.AssertEquals('single', TAppConfig.Get(KEY_B));
end;

procedure TAppConfigTests.Get_FileKeyIgnoresCase;
begin
  WriteEnvFile(LowerCase(KEY_A) + '=ok');
  TAssert.AssertEquals('ok', TAppConfig.Get(KEY_A));
end;

procedure TAppConfigTests.Get_ValueMayContainEqualsSign;
begin
  WriteEnvFile(KEY_A + '=a=b=c');
  TAssert.AssertEquals('a=b=c', TAppConfig.Get(KEY_A));
end;

procedure TAppConfigTests.Get_FileWithBomAndNonAscii;
var
  LText, LBytes: TBytes;
begin
  LText := PaStringToUtf8Bytes(KEY_A + '=São Paulo → ok');
  LBytes := nil;
  SetLength(LBytes, 3 + Length(LText));
  LBytes[0] := $EF;
  LBytes[1] := $BB;
  LBytes[2] := $BF;
  Move(LText[0], LBytes[3], Length(LText));
  WriteBytes(FTempEnv, LBytes);
  TAssert.AssertEquals('São Paulo → ok', TAppConfig.Get(KEY_A));
end;

procedure TAppConfigTests.Get_FileWithCrLf;
begin
  WriteEnvFile('# comment' + #13#10 + KEY_A + '=one' + #13#10 + KEY_B + '=two' + #13#10);
  TAssert.AssertEquals('one', TAppConfig.Get(KEY_A));
  TAssert.AssertEquals('two', TAppConfig.Get(KEY_B));
end;

procedure TAppConfigTests.Get_RealEnvironmentReader_SeesPath;
begin
  TAppConfig.SetEnvironmentReader(nil);
  TAssert.AssertTrue('PATH should come from the process environment',
    TAppConfig.Get('PATH') <> '');
end;

procedure TAppConfigTests.GetInt_ParsesNumber;
begin
  WriteEnvFile(KEY_A + '=9000');
  TAssert.AssertEquals(9000, TAppConfig.GetInt(KEY_A, 0));
end;

procedure TAppConfigTests.GetInt_NotNumeric_ReturnsDefault;
begin
  WriteEnvFile(KEY_A + '=abc');
  TAssert.AssertEquals(42, TAppConfig.GetInt(KEY_A, 42));
end;

procedure TAppConfigTests.GetInt_Absent_ReturnsDefault;
begin
  TAssert.AssertEquals(8080, TAppConfig.GetInt(KEY_A, 8080));
end;

procedure TAppConfigTests.GetBool_TrueOneYes_AreTrue;
begin
  GFakeEnv.Values[KEY_A] := 'TRUE';
  TAssert.AssertTrue('TRUE', TAppConfig.GetBool(KEY_A, False));
  GFakeEnv.Values[KEY_A] := '1';
  TAssert.AssertTrue('1', TAppConfig.GetBool(KEY_A, False));
  GFakeEnv.Values[KEY_A] := 'yes';
  TAssert.AssertTrue('yes', TAppConfig.GetBool(KEY_A, False));
end;

procedure TAppConfigTests.GetBool_OtherValue_IsFalse;
begin
  GFakeEnv.Values[KEY_A] := 'false';
  TAssert.AssertFalse('false', TAppConfig.GetBool(KEY_A, True));
  GFakeEnv.Values[KEY_A] := 'on';
  TAssert.AssertFalse('on', TAppConfig.GetBool(KEY_A, True));
end;

procedure TAppConfigTests.GetBool_Absent_ReturnsDefault;
begin
  TAssert.AssertTrue(TAppConfig.GetBool(KEY_A, True));
  TAssert.AssertFalse(TAppConfig.GetBool(KEY_B, False));
end;

{ TTextTests }

procedure TTextTests.RoundTrip_NonAscii;
const
  TEXT = 'São Paulo → ok ✓';
begin
  TAssert.AssertEquals(TEXT, PaUtf8BytesToString(PaStringToUtf8Bytes(TEXT), 'test'));
end;

procedure TTextTests.Decode_SkipsBom;
var
  LBytes: TBytes;
begin
  LBytes := nil;
  SetLength(LBytes, 5);
  LBytes[0] := $EF;
  LBytes[1] := $BB;
  LBytes[2] := $BF;
  LBytes[3] := Ord('o');
  LBytes[4] := Ord('k');
  TAssert.AssertEquals('ok', PaUtf8BytesToString(LBytes, 'test'));
end;

procedure TTextTests.Decode_Empty;
begin
  TAssert.AssertEquals('', PaUtf8BytesToString(nil, 'test'));
end;

procedure TTextTests.Encode_IsUtf8Bytes;
var
  LBytes: TBytes;
begin
  // 'ã' is C3 A3 in UTF-8; '→' is E2 86 92.
  LBytes := PaStringToUtf8Bytes('ã→');
  TAssert.AssertEquals(5, Length(LBytes));
  TAssert.AssertEquals($C3, Integer(LBytes[0]));
  TAssert.AssertEquals($A3, Integer(LBytes[1]));
  TAssert.AssertEquals($E2, Integer(LBytes[2]));
  TAssert.AssertEquals($86, Integer(LBytes[3]));
  TAssert.AssertEquals($92, Integer(LBytes[4]));
end;

initialization
  TDUnitX.RegisterTestFixture(TAppConfigTests);
  TDUnitX.RegisterTestFixture(TTextTests);

end.
