unit PascalApi.PaginationTests;

{ Tests for PascalApi.Pagination: query-string parsing, page request from
  optionals, and the JSON envelope. TPageRequest/TPageMeta themselves are
  tested in pascal-db-faa.

  DUnitX master. The FPCUnit mirror (tests/Unit/fpc) is generated by
  tools/gen_fpc_mirror.py; never edit the mirror by hand. }

interface

uses
  DUnitX.TestFramework,
  PascalApi.DUnitXCompat,
  SysUtils,
  PascalCommon.Optionals,
  PascalDb.Paging,
  PascalApi.Pagination;

type
  [TestFixture]
  TPaginationTests = class
  public
    [Test] procedure ParseQueryInt_Number;
    [Test] procedure ParseQueryInt_EmptyOrInvalid_IsNil;
    [Test] procedure ParseQueryStr_Text;
    [Test] procedure ParseQueryStr_Empty_IsNil;

    [Test] procedure PageRequestFrom_Nil_UsesDefaults;
    [Test] procedure PageRequestFrom_Values;
    [Test] procedure PageRequestFrom_Offset;
    [Test] procedure PageRequestFrom_LimitAboveMax_IsClamped;
    [Test] procedure PageRequestFrom_PageBelowOne_IsOne;
    [Test] procedure PageRequestFrom_LimitBelowOne_IsDefault;
    [Test] procedure PageRequestFrom_CustomDefaults;

    [Test] procedure Envelope_ExactText;
    [Test] procedure Envelope_LastPage;
    [Test] procedure Envelope_Empty_HasOnePage;
    [Test] procedure Envelope_TotalAboveInt32;
  end;

implementation

function Meta(APage, ALimit: Integer; ATotal: Int64): TPageMeta;
begin
  Result := TPageMeta.Create(TPageRequest.Create(APage, ALimit), ATotal);
end;

procedure TPaginationTests.ParseQueryInt_Number;
var
  LValue: IOptInteger;
begin
  LValue := ParseQueryInt('42');
  TAssert.AssertTrue(Assigned(LValue) and LValue.HasValue);
  TAssert.AssertEquals(42, LValue.Value);
end;

procedure TPaginationTests.ParseQueryInt_EmptyOrInvalid_IsNil;
begin
  TAssert.AssertTrue('empty', ParseQueryInt('') = nil);
  TAssert.AssertTrue('text', ParseQueryInt('abc') = nil);
  TAssert.AssertTrue('decimal', ParseQueryInt('1.5') = nil);
end;

procedure TPaginationTests.ParseQueryStr_Text;
var
  LValue: IOptString;
begin
  LValue := ParseQueryStr('São');
  TAssert.AssertTrue(Assigned(LValue) and LValue.HasValue);
  TAssert.AssertEquals('São', LValue.Value);
end;

procedure TPaginationTests.ParseQueryStr_Empty_IsNil;
begin
  TAssert.AssertTrue(ParseQueryStr('') = nil);
end;

procedure TPaginationTests.PageRequestFrom_Nil_UsesDefaults;
var
  LPage: TPageRequest;
begin
  LPage := PageRequestFrom(nil, nil);
  TAssert.AssertEquals(1, LPage.Page);
  TAssert.AssertEquals(PDB_PAGE_DEFAULT_LIMIT, LPage.Limit);
end;

procedure TPaginationTests.PageRequestFrom_Values;
var
  LPage: TPageRequest;
begin
  LPage := PageRequestFrom(TOptNullInteger.From(3), TOptNullInteger.From(15));
  TAssert.AssertEquals(3, LPage.Page);
  TAssert.AssertEquals(15, LPage.Limit);
end;

procedure TPaginationTests.PageRequestFrom_Offset;
begin
  TAssert.AssertEquals(Int64(20),
    PageRequestFrom(TOptNullInteger.From(3), TOptNullInteger.From(10)).Offset);
  TAssert.AssertEquals(Int64(0),
    PageRequestFrom(TOptNullInteger.From(1), TOptNullInteger.From(20)).Offset);
end;

procedure TPaginationTests.PageRequestFrom_LimitAboveMax_IsClamped;
begin
  TAssert.AssertEquals(PDB_PAGE_MAX_LIMIT,
    PageRequestFrom(nil, TOptNullInteger.From(PDB_PAGE_MAX_LIMIT + 1)).Limit);
end;

procedure TPaginationTests.PageRequestFrom_PageBelowOne_IsOne;
begin
  TAssert.AssertEquals(1, PageRequestFrom(TOptNullInteger.From(0), nil).Page);
  TAssert.AssertEquals(1, PageRequestFrom(TOptNullInteger.From(-5), nil).Page);
end;

procedure TPaginationTests.PageRequestFrom_LimitBelowOne_IsDefault;
begin
  TAssert.AssertEquals(PDB_PAGE_DEFAULT_LIMIT,
    PageRequestFrom(nil, TOptNullInteger.From(0)).Limit);
end;

procedure TPaginationTests.PageRequestFrom_CustomDefaults;
var
  LPage: TPageRequest;
begin
  LPage := PageRequestFrom(nil, nil, 5, 50);
  TAssert.AssertEquals(5, LPage.Limit);
  LPage := PageRequestFrom(nil, TOptNullInteger.From(80), 5, 50);
  TAssert.AssertEquals(50, LPage.Limit);
end;

procedure TPaginationTests.Envelope_ExactText;
begin
  TAssert.AssertEquals(
    '{"page":2,"limit":10,"total":25,"totalPages":3,"hasNext":true,"hasPrev":true,"items":[1,2]}',
    PageEnvelopeJson(Meta(2, 10, 25), '[1,2]'));
end;

procedure TPaginationTests.Envelope_LastPage;
begin
  TAssert.AssertEquals(
    '{"page":3,"limit":10,"total":25,"totalPages":3,"hasNext":false,"hasPrev":true,"items":[]}',
    PageEnvelopeJson(Meta(3, 10, 25), '[]'));
end;

procedure TPaginationTests.Envelope_Empty_HasOnePage;
begin
  TAssert.AssertEquals(
    '{"page":1,"limit":20,"total":0,"totalPages":1,"hasNext":false,"hasPrev":false,"items":[]}',
    PageEnvelopeJson(Meta(1, 20, 0), '[]'));
end;

procedure TPaginationTests.Envelope_TotalAboveInt32;
begin
  TAssert.AssertEquals(
    '{"page":1,"limit":100,"total":5000000000,"totalPages":50000000,"hasNext":true,"hasPrev":false,"items":[]}',
    PageEnvelopeJson(Meta(1, 100, 5000000000), '[]'));
end;

initialization
  TDUnitX.RegisterTestFixture(TPaginationTests);

end.
