unit PascalApi.DtoTests;

{ Tests for PascalApi.Dto through pascal-jsonmapper-faa: the base classes'
  published properties reach JSON, are inherited by a concrete DTO, and the
  optional members of a paged search keep "absent" apart from a value.

  The JSON converter for the optional types is pascal-common-faa's bridge
  (PascalCommon.JsonMapper.Optionals), registered when its unit is used.

  DUnitX master. The FPCUnit mirror (tests/Unit/fpc) is generated by
  tools/gen_fpc_mirror.py; never edit the mirror by hand. }

interface

uses
  DUnitX.TestFramework,
  PascalApi.DUnitXCompat,
  SysUtils,
  PascalCommon.Optionals,
  PascalJsonMapper.Mapper,
  PascalCommon.JsonMapper.Optionals,
  PascalDb.Paging,
  PascalApi.Pagination,
  PascalApi.Dto;

type
  ICityFind = interface(IFindPaginationDTOBase)
    ['{C462411C-51C3-4872-8E57-A9E20211C892}']
    function GetState: IOptString;
  end;

  ICityPage = interface(IResponsePaginationDTOBase)
    ['{71CDDDFD-82C8-41D7-B24E-9E83D2019C5E}']
  end;

{$M+}
  TCityFind = class(TFindPaginationDTOBase, ICityFind)
  private
    FState: IOptString;
  public
    function GetState: IOptString;
  published
    property State: IOptString read FState write FState;
  end;

  TCityPage = class(TResponsePaginationDTOBase, ICityPage)
  end;
{$M-}

  [TestFixture]
  TDtoTests = class
  public
    [Test] procedure Find_FromJson_FillsInheritedMembers;
    [Test] procedure Find_AbsentMembers_AreSafeAndEmpty;
    [Test] procedure Find_FeedsPageRequest;
    [Test] procedure Find_ToJson_OmitsAbsentMembers;
    [Test] procedure Page_ToJson_InheritedMembers;
    [Test] procedure Page_TotalAboveInt32_RoundTrips;
  end;

implementation

{ TCityFind }

function TCityFind.GetState: IOptString;
begin
  Result := TOptionals.Safe(FState);
end;

{ TDtoTests }

procedure TDtoTests.Find_FromJson_FillsInheritedMembers;
var
  LFind: ICityFind;
begin
  LFind := TJsonMapper.Shared.FromJson<ICityFind>(
    '{"page":2,"limit":15,"orderBy":"-name","search":"São","state":"SP"}');
  TAssert.AssertEquals(2, LFind.Page.Value);
  TAssert.AssertEquals(15, LFind.Limit.Value);
  TAssert.AssertEquals('-name', LFind.OrderBy.Value);
  TAssert.AssertEquals('São', LFind.Search.Value);
  TAssert.AssertEquals('SP', LFind.GetState.Value);
end;

procedure TDtoTests.Find_AbsentMembers_AreSafeAndEmpty;
var
  LFind: ICityFind;
begin
  LFind := TJsonMapper.Shared.FromJson<ICityFind>('{"page":3}');
  TAssert.AssertTrue(LFind.Page.HasValue);
  // Absent members: the getters never return nil (TOptionals.Safe).
  TAssert.AssertTrue('Limit', Assigned(LFind.Limit) and not LFind.Limit.HasValue);
  TAssert.AssertTrue('OrderBy', Assigned(LFind.OrderBy) and not LFind.OrderBy.HasValue);
  TAssert.AssertTrue('Search', Assigned(LFind.Search) and not LFind.Search.HasValue);
  TAssert.AssertTrue('State', Assigned(LFind.GetState) and not LFind.GetState.HasValue);
end;

procedure TDtoTests.Find_FeedsPageRequest;
var
  LFind: ICityFind;
  LPage: TPageRequest;
begin
  LFind := TJsonMapper.Shared.FromJson<ICityFind>('{"page":3}');
  LPage := PageRequestFrom(LFind.Page, LFind.Limit);
  TAssert.AssertEquals(3, LPage.Page);
  TAssert.AssertEquals(PDB_PAGE_DEFAULT_LIMIT, LPage.Limit);
end;

procedure TDtoTests.Find_ToJson_OmitsAbsentMembers;
var
  LFind: ICityFind;
begin
  LFind := TJsonMapper.Shared.FromJson<ICityFind>('{"page":1,"state":"RS"}');
  TAssert.AssertEquals('{"page":1,"state":"RS"}', TJsonMapper.Shared.ToJson<ICityFind>(LFind));
end;

procedure TDtoTests.Page_ToJson_InheritedMembers;
var
  LPage: ICityPage;
begin
  LPage := TCityPage.Create;
  LPage.Page := 2;
  LPage.Limit := 10;
  LPage.Total := 25;
  TAssert.AssertEquals('{"page":2,"limit":10,"total":25}',
    TJsonMapper.Shared.ToJson<ICityPage>(LPage));
end;

procedure TDtoTests.Page_TotalAboveInt32_RoundTrips;
var
  LPage: ICityPage;
begin
  LPage := TJsonMapper.Shared.FromJson<ICityPage>('{"page":1,"limit":100,"total":5000000000}');
  TAssert.AssertEquals(Int64(5000000000), LPage.Total);
end;

initialization
  TJsonMapper.Shared.RegisterMapping<ICityFind, TCityFind>;
  TJsonMapper.Shared.RegisterMapping<ICityPage, TCityPage>;
  TDUnitX.RegisterTestFixture(TDtoTests);

end.
